import Mathlib

theorem aime_1990_p15 (a b x y : ℝ) (h₀ : a * x + b * y = 3) (h₁ : a * x ^ 2 + b * y ^ 2 = 7)
    (h₂ : a * x ^ 3 + b * y ^ 3 = 16) (h₃ : a * x ^ 4 + b * y ^ 4 = 42) :
    a * x ^ 5 + b * y ^ 5 = 20 := by

  aesop (config := {
    maxRuleApplications := 400
    maxRuleApplicationDepth := 220
    maxNormIterations := 180
    enableUnfold := false
  }) (rule_sets := [-builtin])
    (add norm 100 (by ring))
    (add norm 100 (by field_simp))
    (add norm 100 (by norm_num))
    (add norm 100 (by norm_cast))
    (add norm 0 (by linarith))
    (add norm 0 (by nlinarith))
    (add norm 0 (by omega))
    (add norm 100 (by abel))
    (add norm 100 (by zify))
    (add norm 100 (by gcongr))
    (add norm 0 (by bound))
    (add norm 100 (by interval_cases))
    (add norm 100 (by ext))
    (add norm 100 (by exfalso))
    (add norm 100 (by ring_nf at *))
    (add norm 100 (by norm_num [*] at *))
    (add norm 100 (by norm_cast at *))
    (add norm 100 (by rfl))
    (add norm 100 (by push_cast))
    (add norm 100 (by assumption_mod_cast))
    (add safe 1 (by ring_nf))
    (add safe 0 (by split))
    (add safe 0 (by simp_all))
    (add safe 0 (by field_simp [*] at *))
    (add norm 0 (by grind only [sq_add_sq_mul]))
    (add norm 0 (by grind only [mul_self_nonneg]))
    (add norm 0 (by grind only [euler_four_squares]))
    (add norm 0 (by grind only [Real.mul_self_sqrt]))
    (add norm 100 (by norm_num [lt_mul_of_one_lt_left'] at *))
    (add safe 1 (by linarith [Pell.Solution₁.x_mul]))
    (add unsafe 10% (by push_cast [sq_pos_of_pos] at *))
    (add unsafe 10% (by push_cast [sq_lt_sq] at *))
    (add unsafe 50% (by simp only [Pell.Solution₁.prop_x]))
    (add unsafe 10% (by push_cast [Real.sq_sqrt] at *))
    (add unsafe 10% (by push_cast [mul_lt_mul_left] at *))
    (add unsafe 10% (by push_cast [Real.sqrt_lt] at *))
    (add unsafe 50% (by solve_by_elim [Pell.Solution₁.y_mul]))
    (add unsafe 10% (by push_cast [EisensteinSeries.r1] at *))
    (add unsafe 10% (by push_cast [sq_abs] at *))
    (add unsafe 10% (by push_cast [mul_lt_mul_right] at *))
    (add unsafe 90% (by grind only [Pell.Solution₁.x_mul_pos]))
    (add unsafe 10% (by push_cast [sq_sub_sq] at *))
    (add unsafe 10% (by push_cast [one_lt_sq_iff_one_lt_abs] at *))
    (add unsafe 10% (by push_cast [sq_eq_sq] at *))
    (add unsafe 90% (by grind only [mul_lt_iff_lt_one_left]))
    (add unsafe 10% (by push_cast [Real.sqrt_sq] at *))
    (add unsafe 10% (by push_cast [Real.lt_sqrt] at *))
    (add unsafe 10% (by push_cast [mul_lt_mul_of_pos_left] at *))
    (add unsafe 10% (by push_cast [Pell.Solution₁.prop_y] at *))
    (add unsafe 50% (by solve_by_elim [Quaternion.sq_eq_normSq]))
    (add unsafe 10% (by push_cast [sq_lt_one_iff] at *))
    (add unsafe 90% (by grind only [Real.mul_pos]))
    (add unsafe 10% (by push_cast [pow_two] at *))
    (add unsafe 10% (by push_cast [zero_lt_two] at *))
    (add unsafe 90% (by grind only [EisensteinSeries.r1_pos]))
    (add unsafe 10% (by push_cast [Pell.Solution₁.prop] at *))