import Mathlib

theorem aime_1989_p8 (a b c d e f g : ℝ)
    (h₀ : a + 4 * b + 9 * c + 16 * d + 25 * e + 36 * f + 49 * g = 1)
    (h₁ : 4 * a + 9 * b + 16 * c + 25 * d + 36 * e + 49 * f + 64 * g = 12)
    (h₂ : 9 * a + 16 * b + 25 * c + 36 * d + 49 * e + 64 * f + 81 * g = 123) :
    16 * a + 25 * b + 36 * c + 49 * d + 64 * e + 81 * f + 100 * g = 334 := by

  aesop (config := {
    maxRuleApplicationDepth := 10
    maxNormIterations := 60
  }) (rule_sets := [-builtin])
    (add norm 100 (by ring))
    (add norm 100 (by field_simp))
    (add norm 100 (by norm_num))
    (add norm 100 (by norm_cast))
    (add norm 0 (by linarith))
    (add norm 0 (by nlinarith))
    (add norm 0 (by omega))
    (add norm 100 (by abel))
    (add norm 100 (by zify))
    (add norm 100 (by gcongr))
    (add norm 0 (by bound))
    (add norm 100 (by interval_cases))
    (add norm 100 (by ext))
    (add norm 100 (by split))
    (add norm 100 (by exfalso))
    (add norm 100 (by ring_nf at *))
    (add norm 100 (by norm_num [*] at *))
    (add norm 100 (by norm_cast at *))
    (add norm 100 (by rfl))
    (add norm 100 (by push_cast))
    (add norm 100 (by assumption_mod_cast))
    (add safe 1 (by ring_nf))
    (add safe 0 (by simp_all))
    (add safe 0 (by field_simp [*] at *))
    (add norm 100 (by simp only [mul_left_comm] at *))
    (add norm 100 (by simp only [mul_right_comm] at *))
    (add norm 100 (by simp only [mul_assoc] at *))
    (add norm 100 (by simp only [mul_comm] at *))
    (add norm 100 (by simp only [mul_add_mul] at *))
    (add norm 0 (by grind only [mul_lt_mul_left]))
    (add norm 0 (by grind only [Pell.isPell_norm]))
    (add norm 0 (by grind only [QuaternionAlgebra.mul_imJ]))
    (add norm 0 (by grind only [mul_mul_mul_comm]))
    (add norm 0 (by grind only [mul_lt_mul_iff_left]))
    (add norm 0 (by grind only [mul_lt_mul_right]))
    (add norm 0 (by grind only [Quaternion.star_add_self]))
    (add norm 0 (by grind only [Quaternion.self_add_star]))
    (add norm 0 (by grind only [mul_lt_mul_iff_right]))
    (add norm 0 (by grind only [Real.arctan_ne_mul_pi_div_two]))
    (add norm 100 (by norm_num [Real.add_lt_add_iff_left] at *))
    (add safe 1 (by linarith [QuaternionAlgebra.mul_re]))
    (add safe 1 (by rw [QuaternionAlgebra.mul_imK]))
    (add safe 0 (by norm_num [Zsqrtd.divides_sq_eq_zero_z] at *))
    (add unsafe 50% (by rw [← QuaternionAlgebra.mul_imI] at *))
    (add unsafe 50% (by rw [← Pell.Solution₁.y_mul] at *))
    (add unsafe 50% (by rw [← Pell.Solution₁.x_mul] at *))
    (add unsafe 50% (by simp_all [lt_div_iff_mul_lt]))
    (add unsafe 50% (by simp_all [lt_div_iff_mul_lt']))
    (add unsafe 50% (by simp_all [mul_lt_mul_of_pos_left]))
    (add unsafe 50% (by simp_all [div_lt_iff_lt_mul']))
    (add unsafe 90% (by grind only [Real.Angle.coe_two_pi]))
    (add unsafe 90% (by norm_num [Quaternion.coe_commutes] at *))
    (add unsafe 50% (by rw [← mul_le_mul_left] at *))
    (add unsafe 50% (by simp_all [div_lt_iff_lt_mul]))
    (add unsafe 50% (by simp_all [div_lt_iff]))
    (add unsafe 50% (by simp_all [lt_div_iff]))