import Mathlib

theorem aime_1990_p4 (x : ℝ) (h₀ : 0 < x) (h₁ : x ^ 2 - 10 * x - 29 ≠ 0)
    (h₂ : x ^ 2 - 10 * x - 45 ≠ 0) (h₃ : x ^ 2 - 10 * x - 69 ≠ 0)
    (h₄ : 1 / (x ^ 2 - 10 * x - 29) + 1 / (x ^ 2 - 10 * x - 45) - 2 / (x ^ 2 - 10 * x - 69) = 0) :
    x = 13 := by

  aesop (config := {
    maxRuleApplications := 100
    maxRuleApplicationDepth := 10
    maxNormIterations := 520
    maxGoals := 1024
  }) (rule_sets := [-builtin])
    (add norm 100 (by ring))
    (add norm 100 (by field_simp))
    (add norm 100 (by norm_num))
    (add norm 0 (by linarith))
    (add norm 0 (by nlinarith))
    (add norm 0 (by omega))
    (add norm 100 (by abel))
    (add norm 100 (by zify))
    (add norm 0 (by bound))
    (add norm 100 (by interval_cases))
    (add norm 100 (by ext))
    (add norm 100 (by split))
    (add norm 100 (by exfalso))
    (add norm 100 (by simp))
    (add norm 100 (by ring_nf at *))
    (add norm 1 (by field_simp [*] at *))
    (add norm 100 (by norm_num [*] at *))
    (add norm 100 (by norm_cast at *))
    (add norm 100 (by rfl))
    (add norm 100 (by decide))
    (add norm 100 (by push_cast))
    (add norm 100 (by assumption_mod_cast))
    (add safe 100 (by norm_cast))
    (add safe 0 (by ring_nf))
    (add norm 100 (by apply mul_right_inj'))
    (add norm 0 (by grind only [irrational_iff_ne_rational]))
    (add norm 0 (by grind only [Iff]))
    (add norm 100 (by apply mul_left_cancel₀))
    (add norm 0 (by grind only [sq_eq_zero_iff]))
    (add norm 0 (by grind only [sq_eq_sq]))
    (add norm 100 (by apply mul_left_inj'))
    (add norm 0 (by simp [div_ne_one_of_ne] at *))
    (add norm 100 (by apply mul_right_cancel₀))
    (add norm 0 (by simp [div_ne_one] at *))
    (add norm 100 (by rw [← pow_ne_zero]))
    (add norm 0 (by grind only [mul_eq_one_iff']))
    (add norm 0 (by grind only [mul_nonneg_iff_of_pos_right]))
    (add norm 100 (by apply mul_ne_zero))
    (add norm 100 (by apply legendreSym.eq_one_of_sq_sub_mul_sq_eq_zero))
    (add norm 100 (by apply legendreSym.eq_zero_mod_of_eq_neg_one))
    (add norm 0 (by grind only [sq_pos_iff]))
    (add norm 0 (by grind only [sq_eq_one_iff]))
    (add norm 1 (by rw [← eq_div_iff_mul_eq]))
    (add norm 100 (by apply legendreSym.eq_one_of_sq_sub_mul_sq_eq_zero'))
    (add norm 100 (by apply div_ne_zero))
    (add safe 0 (by simp_all [Int.sq_of_gcd_eq_one]))
    (add unsafe 10% (by push_cast [sq_pos_of_pos] at *))
    (add unsafe 10% (by linarith [div_eq_one]))
    (add unsafe 10% (by push_cast [two_ne_zero] at *))
    (add unsafe 90% (by grind only [mul_self_pos]))
    (add unsafe 90% (by grind only [mul_pos_iff_of_pos_left]))
    (add unsafe 10% (by push_cast [LucasLehmer.mersenne_int_ne_zero] at *))
    (add unsafe 10% (by linarith [mul_lt_mul_left]))
    (add unsafe 90% (by grind only [WeierstrassCurve.Jacobian.Y_sub_Y_mul_Y_sub_negY]))
    (add unsafe 90% (by grind only [FractionalIdeal.mem_div_iff_of_nonzero]))
    (add unsafe 90% (by grind only [WeierstrassCurve.Affine.Y_eq_of_Y_ne]))