import Mathlib

theorem algebra_2varlineareq_fp3zeq11_3tfm1m5zeqn68_feqn10_zeq7 (f z : ℂ) (h₀ : f + 3 * z = 11)
    (h₁ : 3 * (f - 1) - 5 * z = -68) : f = -10 ∧ z = 7 := by

  aesop (config := {
    maxRuleApplications := 100
    maxRuleApplicationDepth := 10
    maxNormIterations := 30
    maxGoals := 128
    enableSimp := false
  })
    (add norm 100 (by ring))
    (add norm 100 (by field_simp))
    (add norm 100 (by norm_num))
    (add norm 100 (by norm_cast))
    (add norm 0 (by linarith))
    (add norm 0 (by nlinarith))
    (add norm 0 (by omega))
    (add norm 100 (by abel))
    (add norm 100 (by push_neg))
    (add norm 100 (by zify))
    (add norm 100 (by bound))
    (add norm 100 (by interval_cases))
    (add norm 100 (by ext))
    (add norm 100 (by split))
    (add norm 100 (by exfalso))
    (add norm 100 (by ring_nf at *))
    (add norm 100 (by norm_num [*] at *))
    (add norm 100 (by norm_cast at *))
    (add norm 100 (by rfl))
    (add norm 100 (by decide))
    (add norm 100 (by push_cast))
    (add norm 100 (by assumption_mod_cast))
    (add safe 0 (by simp_all))
    (add safe 0 (by field_simp [*] at *))
    (add norm 0 (by grind only [Complex.two_pi_I_ne_zero]))
    (add norm 0 (by grind only [Complex.I_ne_zero]))
    (add norm 0 (by grind only [Complex.I]))
    (add norm 0 (by grind only [Complex.arctan]))
    (add norm 0 (by grind only [neg_div]))
    (add norm 0 (by grind only [mul_neg_one]))
    (add norm 0 (by grind only [Complex.sin]))
    (add norm 0 (by grind only [Complex.cpow_neg_one]))
    (add norm 0 (by grind only [Complex.I_sq]))
    (add norm 0 (by grind only [HurwitzZeta.sinZeta]))
    (add norm 0 (by grind only [Complex.Gammaℂ]))
    (add norm 0 (by grind only [Real.pi_ne_zero]))
    (add norm 0 (by grind only [div_inv_eq_mul]))
    (add norm 0 (by grind only [Complex.exp_ne_zero]))
    (add norm 0 (by grind only [two_ne_zero']))
    (add norm 0 (by grind only [Real.arctan_ne_mul_pi_div_two]))
    (add norm 0 (by grind only [Real.two_pi_pos]))
    (add norm 0 (by grind only [Complex.exp]))
    (add norm 0 (by grind only [Complex.ofReal_cpow_of_nonpos]))
    (add norm 0 (by grind only [mul_div_assoc]))
    (add norm 0 (by grind only [Complex.div_I]))
    (add norm 0 (by grind only [jacobiTheta₂]))
    (add norm 0 (by grind only [Complex.I_mul_I]))
    (add norm 0 (by grind only [jacobiTheta]))
    (add norm 0 (by grind only [Complex.exp_sub]))
    (add norm 0 (by grind only [quadratic_eq_zero_iff]))
    (add norm 0 (by grind only [Complex.exp_log]))
    (add norm 0 (by grind only [div_eq_iff_eq_mul]))
    (add norm 0 (by grind only [div_eq_mul_inv]))
    (add norm 0 (by grind only [div_eq_iff]))
    (add norm 0 (by grind only [jacobiTheta₂_functional_equation]))
    (add norm 0 (by grind only [Real.pi_pos]))