import Mathlib

theorem amc12b_2002_p19 (a b c : ℝ) (h₀ : 0 < a ∧ 0 < b ∧ 0 < c) (h₁ : a * (b + c) = 152)
    (h₂ : b * (c + a) = 162) (h₃ : c * (a + b) = 170) : a * b * c = 720 := by

  aesop (config := {
    maxRuleApplications := 100
    maxRuleApplicationDepth := 220
    maxNormIterations := 60
    enableSimp := false
    enableUnfold := false
  }) (rule_sets := [-builtin])
    (add norm 100 (by ring))
    (add norm 100 (by field_simp))
    (add norm 100 (by norm_num))
    (add norm 0 (by linarith))
    (add norm 0 (by nlinarith))
    (add norm 0 (by omega))
    (add norm 100 (by abel))
    (add norm 100 (by zify))
    (add norm 100 (by gcongr))
    (add norm 0 (by bound))
    (add norm 100 (by interval_cases))
    (add norm 100 (by ext))
    (add norm 100 (by split))
    (add norm 100 (by exfalso))
    (add norm 100 (by simp))
    (add norm 100 (by ring_nf at *))
    (add norm 100 (by norm_num [*] at *))
    (add norm 100 (by norm_cast at *))
    (add norm 0 (by rfl))
    (add norm 100 (by push_cast))
    (add norm 100 (by assumption_mod_cast))
    (add safe 1 (by norm_cast))
    (add safe 1 (by ring_nf))
    (add safe 0 (by simp_all))
    (add safe 0 (by field_simp [*] at *))
    (add norm 0 (by grind only [Real.mul_self_sqrt]))
    (add norm 0 (by grind only [mul_self_nonneg]))
    (add norm 100 (by simp only [mul_left_comm] at *))
    (add norm 100 (by rw [← mabs_of_one_lt]))
    (add norm 100 (by simp only [mul_comm] at *))
    (add norm 100 (by simp only [mul_assoc] at *))
    (add norm 0 (by grind only [Real.sqrt_mul]))
    (add norm 0 (by grind only [Real.sqrt_mul_self]))
    (add norm 0 (by grind only [Real.pi_pos]))
    (add norm 100 (by norm_num [mul_self_inj] at *))
    (add norm 0 (by grind only [mul_self_inj_of_nonneg]))
    (add norm 0 (by grind only [sq_eq_sq]))
    (add norm 0 (by grind only [norm_add_sq_eq_norm_sq_add_norm_sq_real]))
    (add safe 1 (by linarith [abs_mul]))
    (add safe 0 (by norm_num [mul_add_mul] at *))
    (add safe 1 (by linarith [mul_div_cancel₀]))
    (add safe 1 (by rw [Real.sqrt_sq_eq_abs]))
    (add unsafe 50% (by simp only [abs_mul_abs_self]))
    (add unsafe 90% (by grind only [mul_lt_mul_left]))
    (add unsafe 10% (by push_cast [Real.sq_sqrt] at *))
    (add unsafe 90% (by grind only [mul_nonneg_iff_of_pos_left]))
    (add unsafe 10% (by push_cast [Real.sqrt_sq] at *))
    (add unsafe 50% (by solve_by_elim [mul_right_comm]))
    (add unsafe 90% (by norm_num [Quaternion.coe_commutes] at *))
    (add unsafe 10% (by push_cast [sq_lt_sq] at *))
    (add unsafe 90% (by grind only [EisensteinSeries.r1]))
    (add unsafe 90% (by grind only [Real.sqrt_pos]))
    (add unsafe 90% (by grind only [mul_self_lt_mul_self_iff]))
    (add unsafe 10% (by push_cast [sq_pos_of_pos] at *))
    (add unsafe 90% (by grind only [mul_lt_mul_right]))
    (add unsafe 90% (by grind only [mul_self_pos]))
    (add unsafe 10% (by push_cast [sq_abs] at *))