import Mathlib

theorem amc12b_2002_p7 (a b c : ℕ) (h₀ : 0 < a ∧ 0 < b ∧ 0 < c) (h₁ : b = a + 1) (h₂ : c = b + 1)
    (h₃ : a * b * c = 8 * (a + b + c)) : a ^ 2 + (b ^ 2 + c ^ 2) = 77 := by

  aesop (config := {
    maxRuleApplications := 400
    maxRuleApplicationDepth := 10
    maxNormIterations := 520
    maxGoals := 128
    enableUnfold := false
  }) (rule_sets := [-builtin])
    (add norm 100 (by ring))
    (add norm 100 (by field_simp))
    (add norm 100 (by norm_num))
    (add norm 100 (by norm_cast))
    (add norm 0 (by linarith))
    (add norm 0 (by nlinarith))
    (add norm 0 (by omega))
    (add norm 100 (by abel))
    (add norm 100 (by zify))
    (add norm 100 (by bound))
    (add norm 100 (by interval_cases))
    (add norm 100 (by ext))
    (add norm 100 (by split))
    (add norm 100 (by exfalso))
    (add norm 100 (by ring_nf at *))
    (add norm 1 (by field_simp [*] at *))
    (add norm 100 (by norm_num [*] at *))
    (add norm 100 (by norm_cast at *))
    (add norm 100 (by rfl))
    (add norm 100 (by decide))
    (add norm 100 (by push_cast))
    (add norm 100 (by assumption_mod_cast))
    (add safe 0 (by simp_all))
    (add norm 100 (by simp only [mul_assoc] at *))
    (add norm 100 (by simp only [mul_left_comm] at *))
    (add norm 100 (by simp only [mul_comm] at *))
    (add norm 100 (by simp only [mul_right_comm] at *))
    (add norm 0 (by grind only [mul_two]))
    (add norm 0 (by grind only [pow_add]))
    (add norm 100 (by rw [Surreal.nsmul_pow_two_powHalf'] at *))
    (add norm 0 (by grind only [ack_two]))
    (add norm 0 (by grind only [sq_add_sq_mul]))
    (add norm 0 (by grind only [zero_lt_two]))
    (add norm 0 (by grind only [mul_add_mul]))
    (add norm 0 (by grind only [Polynomial.natDegree_mul_mirror]))
    (add norm 100 (by simp only [mul_one] at *))
    (add norm 0 (by grind only [QuaternionGroup.xa_sq]))
    (add norm 0 (by grind only [Quaternion.self_add_star]))
    (add norm 0 (by grind only [Nat.succ_mul]))
    (add norm 0 (by grind only [Nat.sq_add_sq_mul]))
    (add norm 0 (by grind only [Nat.pow_succ']))
    (add norm 0 (by grind only [Nat.two_mul]))
    (add norm 0 (by grind only [quadraticChar_sq_one]))
    (add norm 0 (by grind only [even_two_mul]))
    (add norm 100 (by rw [Surreal.nsmul_pow_two_powHalf] at *))
    (add safe 0 (by simp_all [pow_two]))
    (add safe 1 (by linarith [mul_le_mul_left]))
    (add unsafe 10% (by push_cast [two_mul] at *))
    (add unsafe 10% (by push_cast [mul_pow] at *))
    (add unsafe 10% (by push_cast [Surreal.double_powHalf_succ_eq_powHalf] at *))
    (add unsafe 10% (by push_cast [ArithmeticFunction.moebius_sq] at *))
    (add unsafe 10% (by push_cast [ArithmeticFunction.moebius_sq_eq_one_of_squarefree] at *))
    (add unsafe 10% (by push_cast [even_two] at *))
    (add unsafe 90% (by norm_num [Nat.cast_two] at *))
    (add unsafe 10% (by push_cast [two_ne_zero] at *))