import Mathlib

theorem amc12a_2013_p4 : (2 ^ 2014 + 2 ^ 2012) / (2 ^ 2014 - 2 ^ 2012) = (5 : ℝ) / 3 := by

  aesop (config := {
    maxRuleApplications := 400
    maxRuleApplicationDepth := 10
    maxNormIterations := 180
    maxGoals := 128
  })
    (add norm 100 (by ring))
    (add norm 100 (by field_simp))
    (add norm 100 (by norm_num))
    (add norm 100 (by norm_cast))
    (add norm 0 (by linarith))
    (add norm 100 (by nlinarith))
    (add norm 100 (by abel))
    (add norm 100 (by zify))
    (add norm 100 (by bound))
    (add norm 100 (by interval_cases))
    (add norm 100 (by ext))
    (add norm 100 (by split))
    (add norm 100 (by exfalso))
    (add norm 100 (by ring_nf at *))
    (add norm 100 (by field_simp [*] at *))
    (add norm 100 (by norm_num [*] at *))
    (add norm 100 (by norm_cast at *))
    (add norm 100 (by rfl))
    (add norm 100 (by decide))
    (add norm 100 (by push_cast))
    (add norm 100 (by assumption_mod_cast))
    (add safe 0 (by omega))
    (add safe 0 (by ring_nf))
    (add safe 0 (by simp_all))
    (add norm 0 (by grind only [div_div]))
    (add norm 0 (by grind only [mul_div]))
    (add norm 0 (by grind only [div_eq_one_iff_eq]))
    (add norm 0 (by grind only [CircleDeg1Lift.transnumAuxSeq]))
    (add norm 0 (by grind only [tsub_div]))
    (add norm 0 (by grind only [div_right_comm]))
    (add norm 0 (by grind only [mul_div_assoc]))
    (add norm 0 (by grind only [goldenConj]))
    (add norm 0 (by grind only [half_add_self]))
    (add norm 0 (by grind only [div_eq_iff]))
    (add norm 0 (by grind only [CircleDeg1Lift.transnumAuxSeq_def]))
    (add norm 0 (by grind only [mul_div_right_comm]))
    (add norm 0 (by grind only [div_add']))
    (add safe 0 (by simp_all [mul_div_mul_left]))
    (add safe 0 (by simp_all [div_mul_cancel₀]))
    (add safe 0 (by simp_rw [mul_one_div]))
    (add safe 0 (by simp [mul_div_mul_right] at *))
    (add unsafe 10% (by push_cast [div_self] at *))
    (add unsafe 50% (by simp_all [add_div]))
    (add unsafe 10% (by push_cast [mul_div_cancel_left₀] at *))
    (add unsafe 10% (by push_cast [two_ne_zero'] at *))
    (add unsafe 10% (by push_cast [div_pow] at *))
    (add unsafe 90% (by simp_all [sub_div]))
    (add unsafe 10% (by push_cast [two_ne_zero] at *))
    (add unsafe 10% (by push_cast [mul_div_cancel_right₀] at *))
    (add unsafe 10% (by push_cast [even_two] at *))
    (add unsafe 10% (by rw [Stirling.stirlingSeq_pow_four_div_stirlingSeq_pow_two_eq]))
    (add unsafe 10% (by push_cast [eq_div_iff] at *))
    (add unsafe 50% (by simp_all [Real.cos_sq]))
    (add unsafe 50% (by apply mul_div_cancel₀))
    (add unsafe 10% (by push_cast [sq_sub_sq] at *))
    (add unsafe 50% (by simp_all [Real.sin_sq_eq_half_sub]))