import Mathlib

theorem amc12a_2003_p5 (A M C : ℕ) (h₀ : A ≤ 9 ∧ M ≤ 9 ∧ C ≤ 9)
    (h₁ : Nat.ofDigits 10 [0, 1, C, M, A] + Nat.ofDigits 10 [2, 1, C, M, A] = 123422) :
    A + M + C = 14 := by

  aesop (config := {
    maxRuleApplications := 100
    maxRuleApplicationDepth := 10
    maxNormIterations := 60
    maxGoals := 128
  })
    (add norm 100 (by ring))
    (add norm 100 (by field_simp))
    (add norm 100 (by norm_num))
    (add norm 100 (by norm_cast))
    (add norm 0 (by linarith))
    (add norm 0 (by nlinarith))
    (add norm 0 (by omega))
    (add norm 100 (by abel))
    (add norm 100 (by zify))
    (add norm 100 (by bound))
    (add norm 100 (by interval_cases))
    (add norm 100 (by ext))
    (add norm 100 (by exfalso))
    (add norm 100 (by ring_nf at *))
    (add norm 1 (by field_simp [*] at *))
    (add norm 100 (by norm_num [*] at *))
    (add norm 100 (by norm_cast at *))
    (add norm 100 (by rfl))
    (add norm 100 (by push_cast))
    (add norm 100 (by assumption_mod_cast))
    (add safe 0 (by ring_nf))
    (add safe 0 (by split))
    (add unsafe 90% (by simp_all))
    (add norm 0 (by grind only [Nat.ofDigits_one]))
    (add norm 0 (by grind only [Nat.ofDigits_singleton]))
    (add norm 0 (by grind only [Nat.ofDigits]))
    (add norm 100 (by rw [← Nat.ofDigits_digits]))
    (add norm 0 (by grind only [Nat.digits_ofDigits]))
    (add norm 0 (by grind only [Nat.ofDigits_monotone]))
    (add norm 100 (by simp only [mul_one] at *))
    (add norm 100 (by simp only [one_mul] at *))
    (add norm 0 (by grind only [Nat.sum_le_ofDigits]))
    (add norm 0 (by grind only [mul_right_inj]))
    (add norm 0 (by grind only [Nat.ofDigits_modEq]))
    (add norm 0 (by grind only [Nat.self_div_pow_eq_ofDigits_drop]))
    (add norm 0 (by grind only [Nat.ofDigits_cons]))
    (add norm 0 (by grind only [mul_left_inj]))
    (add norm 0 (by grind only [mul_right_eq_self]))
    (add norm 100 (by simp only [mul_assoc] at *))
    (add norm 0 (by grind only [Nat.ofDigits_zmodeq']))
    (add norm 0 (by grind only [Hindman.FP.mul]))
    (add norm 0 (by grind only [self_eq_mul_left]))
    (add norm 0 (by grind only [Nat.zmodeq_ofDigits_digits]))
    (add safe 0 (by simp_all [add_self]))
    (add safe 100 (by simp_all [Nat.ofDigits_div_pow_eq_ofDigits_drop]))
    (add safe 100 (by simp_all [Nat.ofDigits_mod_eq_head!]))
    (add safe 100 (by simp_all [Nat.ofDigits_div_eq_ofDigits_tail]))
    (add safe 0 (by norm_num [mul_add_mul] at *))
    (add safe 100 (by simp_all [Nat.ofDigits_eq_foldr]))
    (add safe 1 (by rw [Nat.coe_ofDigits]))
    (add unsafe 90% (by grind only [mul_self]))
    (add unsafe 50% (by simp_rw [mul_le_mul_iff_left]))
    (add unsafe 50% (by simp_rw [Nat.ofDigits_zmodeq]))
    (add unsafe 50% (by simp_rw [Nat.ofDigits_mod]))
    (add unsafe 50% (by simp_rw [mul_le_mul_iff_right]))