import Mathlib

theorem amc12a_2021_p3 (x y : ℕ) (h₀ : x + y = 17402) (h₁ : 10 ∣ x) (h₂ : x / 10 = y) :
    ↑x - ↑y = (14238 : ℤ) := by

  aesop (config := {
    maxRuleApplicationDepth := 10
    maxNormIterations := 60
    maxGoals := 128
  })
    (add norm 100 (by ring))
    (add norm 100 (by field_simp))
    (add norm 100 (by norm_num))
    (add norm 100 (by norm_cast))
    (add norm 0 (by linarith))
    (add norm 0 (by nlinarith))
    (add norm 0 (by omega))
    (add norm 100 (by abel))
    (add norm 100 (by zify))
    (add norm 0 (by bound))
    (add norm 100 (by interval_cases))
    (add norm 100 (by ext))
    (add norm 100 (by exfalso))
    (add norm 0 (by simp))
    (add norm 100 (by ring_nf at *))
    (add norm 100 (by field_simp [*] at *))
    (add norm 100 (by norm_num [*] at *))
    (add norm 100 (by norm_cast at *))
    (add norm 100 (by rfl))
    (add norm 0 (by decide))
    (add norm 100 (by push_cast))
    (add norm 100 (by assumption_mod_cast))
    (add safe 0 (by ring_nf))
    (add safe 0 (by split))
    (add unsafe 90% (by simp_all))
    (add norm 100 (by rw [div_eq_one_iff_eq] at *))
    (add norm 0 (by grind only [mul_div_cancel_right]))
    (add norm 100 (by apply sub_div))
    (add norm 0 (by grind only [mul_div_cancel_left]))
    (add norm 0 (by grind only [div_self']))
    (add norm 100 (by rw [div_eq_one] at *))
    (add norm 0 (by grind only [eq_div_iff_mul_eq']))
    (add norm 0 (by grind only [AddConstMapClass.map_sub_const]))
    (add norm 0 (by grind only [mul_div_cancel]))
    (add norm 0 (by grind only [WeakFEPair.functional_equation]))
    (add norm 0 (by grind only [div_eq_iff_mul_eq]))
    (add norm 0 (by grind only [ContinuousAlternatingMap.sub_apply]))
    (add norm 100 (by rw [← div_self] at *))
    (add norm 0 (by grind only [div_eq_iff_eq_mul']))
    (add norm 0 (by grind only [AddConstMapClass.map_sub_one]))
    (add norm 0 (by grind only [AddConstMapClass.map_sub_nsmul]))
    (add norm 0 (by grind only [div_sub_div_same]))
    (add norm 0 (by grind only [CompactlySupportedContinuousMap.sub_apply]))
    (add safe 0 (by simp_all [div_div]))
    (add safe 1 (by rw [mul_div]))
    (add safe 0 (by simp_all [gosperCatalan]))
    (add safe 0 (by simp_all [LinearPMap.map_sub]))
    (add safe 0 (by simp_all [LinearMap.BilinForm.sub_left]))
    (add safe 0 (by simp_all [mul_div_cancel_left₀]))
    (add safe 0 (by simp_all [LinearMap.BilinForm.sub_right]))
    (add unsafe 10% (by push_cast [div_eq_iff_eq_mul] at *))
    (add unsafe 10% (by push_cast [eq_div_iff] at *))
    (add unsafe 10% (by push_cast [div_mul] at *))
    (add unsafe 10% (by push_cast [eq_div_iff_mul_eq] at *))
    (add unsafe 10% (by push_cast [div_eq_iff] at *))
    (add unsafe 90% (by rw [tsub_div] at *))
    (add unsafe 10% (by push_cast [QuaternionGroup.a_mul_xa] at *))