import Mathlib

theorem amc12_2000_p20 (x y z : ℝ) (h₀ : 0 < x ∧ 0 < y ∧ 0 < z) (h₁ : x + 1 / y = 4)
    (h₂ : y + 1 / z = 1) (h₃ : z + 1 / x = 7 / 3) : x * y * z = 1 := by

  aesop (config := {
    maxRuleApplications := 100
    maxRuleApplicationDepth := 10
    maxNormIterations := 60
    maxGoals := 128
    enableSimp := false
  }) (rule_sets := [-builtin])
    (add norm 100 (by ring))
    (add norm 100 (by field_simp))
    (add norm 100 (by norm_num))
    (add norm 100 (by norm_cast))
    (add norm 0 (by linarith))
    (add norm 0 (by nlinarith))
    (add norm 0 (by omega))
    (add norm 100 (by abel))
    (add norm 100 (by zify))
    (add norm 100 (by bound))
    (add norm 100 (by interval_cases))
    (add norm 100 (by ext))
    (add norm 100 (by split))
    (add norm 100 (by exfalso))
    (add norm 100 (by ring_nf at *))
    (add norm 1 (by field_simp [*] at *))
    (add norm 100 (by norm_num [*] at *))
    (add norm 100 (by norm_cast at *))
    (add norm 100 (by rfl))
    (add norm 100 (by decide))
    (add norm 100 (by push_cast))
    (add norm 100 (by assumption_mod_cast))
    (add safe 0 (by simp_all))
    (add norm 100 (by apply div_self))
    (add norm 100 (by apply mul_one_div))
    (add norm 0 (by grind only [mul_div_assoc]))
    (add norm 0 (by grind only [one_div]))
    (add norm 0 (by grind only [mul_div]))
    (add norm 0 (by grind only [div_eq_iff]))
    (add norm 100 (by apply div_mul_cancel₀))
    (add norm 100 (by apply sub_div))
    (add norm 0 (by grind only [eq_div_iff]))
    (add norm 0 (by grind only [div_div]))
    (add norm 0 (by grind only [div_eq_one_iff_eq]))
    (add norm 0 (by grind only [mul_div_cancel_right₀]))
    (add norm 0 (by grind only [mul_div_cancel_left₀]))
    (add norm 100 (by apply Real.rpow_sub))
    (add norm 0 (by grind only [Complex.Gamma_one_half_eq]))
    (add norm 0 (by grind only [Real.Gamma_add_one]))
    (add norm 0 (by grind only [two_ne_zero']))
    (add norm 0 (by grind only [Real.Gamma_one]))
    (add norm 0 (by grind only [mul_div_mul_left]))
    (add norm 0 (by grind only [Complex.cpow_add]))
    (add norm 1 (by linarith [Real.log_div]))
    (add norm 0 (by grind only [Real.div_rpow]))
    (add norm 0 (by grind only [Real.Gamma_two]))
    (add norm 0 (by grind only [add_div]))
    (add norm 0 (by grind only [div_mul]))
    (add norm 0 (by grind only [Complex.log_ofReal_mul]))
    (add norm 100 (by simp only [mul_comm] at *))
    (add norm 0 (by grind only [Complex.ofReal_div]))
    (add unsafe 50% (by apply mul_div_cancel₀))
    (add unsafe 50% (by apply Real.rpow_add_one))
    (add unsafe 10% (by linarith [Real.rpow_sub']))
    (add unsafe 10% (by simp_all [Real.doublingGamma]))