import Mathlib

theorem amc12b_2020_p2 :
    (100 ^ 2 - 7 ^ 2 : ℝ) / (70 ^ 2 - 11 ^ 2) * ((70 - 11) * (70 + 11) / ((100 - 7) * (100 + 7))) =
      1 := by

  aesop (config := {
    maxRuleApplications := 400
    maxRuleApplicationDepth := 10
    maxNormIterations := 180
    maxGoals := 64
  })
    (add norm 100 (by ring))
    (add norm 100 (by field_simp))
    (add norm 100 (by norm_num))
    (add norm 100 (by norm_cast))
    (add norm 0 (by linarith))
    (add norm 0 (by nlinarith))
    (add norm 0 (by omega))
    (add norm 100 (by abel))
    (add norm 100 (by zify))
    (add norm 100 (by bound))
    (add norm 100 (by interval_cases))
    (add norm 100 (by ext))
    (add norm 100 (by split))
    (add norm 100 (by exfalso))
    (add norm 0 (by simp))
    (add norm 100 (by ring_nf at *))
    (add norm 100 (by field_simp [*] at *))
    (add norm 100 (by norm_num [*] at *))
    (add norm 100 (by norm_cast at *))
    (add norm 100 (by rfl))
    (add norm 0 (by decide))
    (add norm 100 (by push_cast))
    (add norm 100 (by assumption_mod_cast))
    (add safe 0 (by ring_nf))
    (add unsafe 90% (by simp_all))
    (add safe 0 (by simp_all [euler_four_squares]))
    (add safe 0 (by simp_all [legendreSym.eq_one_of_sq_sub_mul_sq_eq_zero]))
    (add safe 0 (by simp_all [sum_four_sq_mul_sum_four_sq]))
    (add safe 0 (by simp_all [legendreSym.eq_one_of_sq_sub_mul_sq_eq_zero']))
    (add unsafe 10% (by push_cast [sq_sub_sq] at *))
    (add unsafe 10% (by push_cast [div_self] at *))
    (add unsafe 10% (by push_cast [div_pow] at *))
    (add unsafe 10% (by push_cast [two_ne_zero] at *))
    (add unsafe 10% (by push_cast [mul_div_cancel_left₀] at *))
    (add unsafe 10% (by push_cast [two_ne_zero'] at *))
    (add unsafe 90% (by simp_all [sub_div]))
    (add unsafe 10% (by push_cast [even_two] at *))
    (add unsafe 10% (by push_cast [neg_sq] at *))
    (add unsafe 10% (by rw [Stirling.stirlingSeq_pow_four_div_stirlingSeq_pow_two_eq]))
    (add unsafe 10% (by push_cast [mul_div_mul_left] at *))
    (add unsafe 10% (by push_cast [integral_id] at *))
    (add unsafe 50% (by simp only [sq_add_sq_mul_sq_add_sq]))
    (add unsafe 10% (by push_cast [eq_div_iff] at *))
    (add unsafe 10% (by push_cast [mul_div_cancel_right₀] at *))
    (add unsafe 10% (by push_cast [sub_sq] at *))
    (add unsafe 10% (by push_cast [mul_pow] at *))
    (add unsafe 10% (by rw [quadraticChar_sq_one]))
    (add unsafe 10% (by push_cast [sq_eq_zero_iff] at *))
    (add unsafe 10% (by push_cast [div_mul_cancel₀] at *))
    (add unsafe 10% (by push_cast [div_eq_iff] at *))
    (add unsafe 10% (by push_cast [div_eq_one_iff_eq] at *))
    (add unsafe 10% (by rw [neg_one_sq]))
    (add unsafe 10% (by push_cast [ArithmeticFunction.moebius_sq] at *))
    (add unsafe 10% (by push_cast [Pell.Solution₁.prop] at *))
    (add unsafe 10% (by push_cast [QuaternionGroup.xa_sq] at *))
    (add unsafe 10% (by push_cast [goldenConj] at *))
    (add unsafe 10% (by push_cast [div_div] at *))