import Mathlib

theorem amc12b_2021_p3 (x : ℝ) (h₀ : 2 + 1 / (1 + 1 / (2 + 2 / (3 + x))) = 144 / 53) : x = 3 / 4 := by

  aesop (config := {
    maxRuleApplicationDepth := 10
    maxNormIterations := 60
    maxGoals := 128
  }) (rule_sets := [-builtin])
    (add norm 100 (by ring))
    (add norm 100 (by field_simp))
    (add norm 100 (by norm_num))
    (add norm 100 (by norm_cast))
    (add norm 0 (by linarith))
    (add norm 0 (by nlinarith))
    (add norm 0 (by omega))
    (add norm 100 (by abel))
    (add norm 100 (by zify))
    (add norm 100 (by bound))
    (add norm 100 (by interval_cases))
    (add norm 100 (by ext))
    (add norm 100 (by split))
    (add norm 100 (by exfalso))
    (add norm 100 (by ring_nf at *))
    (add norm 100 (by field_simp [*] at *))
    (add norm 100 (by norm_num [*] at *))
    (add norm 100 (by norm_cast at *))
    (add norm 100 (by rfl))
    (add norm 100 (by push_cast))
    (add norm 100 (by assumption_mod_cast))
    (add safe 0 (by ring_nf))
    (add safe 0 (by simp_all))
    (add norm 100 (by apply div_self))
    (add norm 0 (by grind only [one_div]))
    (add norm 100 (by apply mul_one_div))
    (add norm 1 (by linarith [neg_div]))
    (add norm 100 (by apply sub_div))
    (add norm 0 (by grind only [div_neg]))
    (add norm 0 (by grind only [mul_div]))
    (add norm 0 (by grind only [div_sub']))
    (add norm 0 (by grind only [Real.sqrt_eq_rpow]))
    (add norm 0 (by grind only [inv_eq_one_div]))
    (add norm 1 (by linarith [add_div]))
    (add norm 0 (by grind only [Eq.symm]))
    (add norm 0 (by grind only [Real.pi_pos]))
    (add norm 0 (by grind only [goldenConj]))
    (add norm 0 (by grind only [eq_div_iff_mul_eq]))
    (add safe 0 (by simp_all [two_ne_zero']))
    (add safe 0 (by simp_all [mul_div_cancel₀]))
    (add safe 0 (by simp_all [div_mul_cancel₀]))
    (add safe 1 (by rw [mul_div_assoc]))
    (add safe 1 (by rw [eq_div_iff]))
    (add safe 1 (by rw [div_eq_iff]))
    (add safe 0 (by simp_all [div_eq_one_iff_eq]))
    (add safe 0 (by simp_all [div_div]))
    (add safe 0 (by simp_all [mul_div_cancel_left₀]))
    (add safe 0 (by simp_all [mul_div_cancel_right₀]))
    (add safe 0 (by simp_all [two_ne_zero]))
    (add safe 0 (by simp_all [WeakFEPair.h_feq']))
    (add safe 1 (by rw [Hyperreal.coe_inv]))
    (add safe 0 (by simp_all [mul_div_mul_left]))
    (add unsafe 50% (by field_simp [div_eq_inv_mul] at *))
    (add unsafe 50% (by simp_rw [Complex.ofReal_inv]))
    (add unsafe 50% (by simp_rw [Complex.ofReal_div]))