import Mathlib

theorem mathd_algebra_125 (x y : ℕ) (h₀ : 0 < x ∧ 0 < y) (h₁ : 5 * x = y)
    (h₂ : ↑x - (3 : ℤ) + (y - (3 : ℤ)) = 30) : x = 6 := by

  aesop (config := {
    maxRuleApplications := 700
    maxRuleApplicationDepth := 220
    maxNormIterations := 60
    maxGoals := 1024
  })
    (add norm 100 (by ring))
    (add norm 100 (by field_simp))
    (add norm 100 (by norm_num))
    (add norm 100 (by norm_cast))
    (add norm 0 (by linarith))
    (add norm 0 (by nlinarith))
    (add norm 0 (by omega))
    (add norm 100 (by abel))
    (add norm 100 (by zify))
    (add norm 0 (by bound))
    (add norm 0 (by ext))
    (add norm 100 (by exfalso))
    (add norm 100 (by simp))
    (add norm 0 (by ring_nf at *))
    (add norm 100 (by norm_num [*] at *))
    (add norm 100 (by norm_cast at *))
    (add norm 100 (by rfl))
    (add norm 100 (by push_cast))
    (add norm 100 (by assumption_mod_cast))
    (add safe 0 (by ring_nf))
    (add safe 0 (by split))
    (add safe 1 (by field_simp [*] at *))
    (add unsafe 90% (by simp_all))
    (add norm 100 (by unfold Nat.cast_sub))
    (add norm 1 (by simp only [Nat.succ_le_of_lt]))
    (add norm 100 (by unfold Nat.cast_tsub))
    (add safe 100 (by simp_all [Nat.sub_add_cancel]))
    (add safe 100 (by simp_all [Nat.add_sub_of_le]))
    (add safe 100 (by simp_all [Nat.modEq_iff_dvd']))
    (add safe 100 (by simp_all [tsub_add_cancel_of_le]))
    (add safe 100 (by simp_all [sub_eq_add]))
    (add safe 100 (by simp_all [add_tsub_cancel_of_le]))
    (add safe 100 (by simp_all [tsub_tsub_cancel_of_le]))
    (add safe 100 (by simp_all [Nat.sub_le]))
    (add safe 100 (by simp_all [Nat.sub_sub_self]))
    (add safe 100 (by simp_all [Nat.le_sub_one_of_lt]))
    (add safe 100 (by simp_all [le_tsub_of_add_le_left]))
    (add safe 100 (by simp_all [eq_tsub_of_add_eq]))
    (add safe 100 (by simp_all [div_eq_iff_eq_mul]))
    (add safe 100 (by simp_all [Nat.exists_eq_add_of_le]))
    (add safe 100 (by simp_all [Nat.sub_add_comm]))
    (add safe 100 (by simp_all [Nat.sub_eq_zero_of_le]))
    (add safe 100 (by simp_all [Nat.add_sub_cancel']))
    (add safe 100 (by simp_all [Nat.add_sub_assoc]))
    (add safe 100 (by simp_all [eq_div_iff_mul_eq']))
    (add safe 100 (by simp_all [div_eq_iff_eq_mul']))
    (add safe 100 (by simp_all [Nat.psub_eq_sub]))
    (add safe 100 (by simp_all [eq_tsub_iff_add_eq_of_le]))
    (add safe 100 (by simp_all [tsub_eq_iff_eq_add_of_le]))
    (add safe 100 (by simp_all [Nat.mod_lt]))
    (add safe 100 (by simp_all [Pell.eq_of_xn_modEq_lem2]))
    (add safe 100 (by simp_all [Nat.even_sub]))
    (add safe 100 (by simp_all [Nat.dvd_sub]))
    (add safe 100 (by simp_all [add_tsub_cancel_left]))
    (add unsafe 90% (by unfold Int.ofNat_sub))