import Mathlib

theorem mathd_algebra_359 (y : ℝ) (h₀ : y + 6 + y = 2 * 12) : y = 9 := by

  aesop (config := {
    maxRuleApplications := 100
    maxRuleApplicationDepth := 10
    maxNormIterations := 60
    maxGoals := 128
    enableUnfold := false
  }) (rule_sets := [-builtin])
    (add norm 100 (by ring))
    (add norm 100 (by field_simp))
    (add norm 100 (by norm_num))
    (add norm 100 (by norm_cast))
    (add norm 0 (by linarith))
    (add norm 0 (by nlinarith))
    (add norm 0 (by omega))
    (add norm 100 (by abel))
    (add norm 100 (by zify))
    (add norm 100 (by bound))
    (add norm 100 (by interval_cases))
    (add norm 100 (by ext))
    (add norm 100 (by split))
    (add norm 100 (by exfalso))
    (add norm 100 (by ring_nf at *))
    (add norm 1 (by field_simp [*] at *))
    (add norm 100 (by norm_num [*] at *))
    (add norm 100 (by norm_cast at *))
    (add norm 100 (by rfl))
    (add norm 100 (by decide))
    (add norm 100 (by push_cast))
    (add norm 100 (by assumption_mod_cast))
    (add safe 1 (by ring_nf))
    (add safe 0 (by simp_all))
    (add norm 0 (by grind only [two_mul]))
    (add norm 0 (by grind only [mul_two]))
    (add norm 0 (by grind only [Quaternion.self_add_star]))
    (add norm 1 (by norm_num [Quaternion.star_add_self] at *))
    (add norm 0 (by grind only [Polynomial.natTrailingDegree_mul_mirror]))
    (add norm 0 (by grind only [ack_two]))
    (add norm 0 (by grind only [QuaternionAlgebra.self_add_star]))
    (add norm 0 (by grind only [Surreal.double_powHalf_succ_eq_powHalf]))
    (add norm 0 (by grind only [Polynomial.natDegree_mul_mirror]))
    (add norm 0 (by grind only [Quaternion.star_add_self']))
    (add norm 0 (by grind only [Nat.fib_two_mul_add_two]))
    (add norm 0 (by grind only [QuaternionAlgebra.star_add_self]))
    (add safe 0 (by simp_all [pow_two]))
    (add safe 1 (by linarith [zero_lt_two']))
    (add unsafe 90% (by grind only [Int.cast_two]))
    (add unsafe 90% (by norm_num [Nat.cast_two] at *))
    (add unsafe 90% (by grind only [Nat.factorial_two]))
    (add unsafe 90% (by grind only [CharTwo.two_eq_zero]))
    (add unsafe 90% (by grind only [Complex.cpow_two]))
    (add unsafe 90% (by grind only [one_add_one_eq_two]))
    (add unsafe 10% (by push_cast [two_ne_zero] at *))
    (add unsafe 90% (by grind only [InnerProductSpaceable]))
    (add unsafe 90% (by grind only [Real.sin_two_mul]))
    (add unsafe 90% (by grind only [zpow_two]))
    (add unsafe 90% (by grind only [Ring.multichoose_two]))
    (add unsafe 90% (by grind only [Nat.cast_descFactorial_two]))
    (add unsafe 90% (by grind only [Real.two_mul_arctan_sub_pi]))
    (add unsafe 90% (by grind only [Real.two_mul_arctan_add_pi]))
    (add unsafe 90% (by grind only [Cardinal.lift_two]))
    (add unsafe 90% (by grind only [Real.norm_two]))
    (add unsafe 90% (by grind only [Real.Angle.two_nsmul_toReal_eq_two_mul]))
    (add unsafe 90% (by grind only [Real.two_mul_arctan]))