import Mathlib

theorem mathd_algebra_263 (y : ℝ) (h₀ : 0 ≤ 19 + 3 * y) (h₁ : Real.sqrt (19 + 3 * y) = 7) :
    y = 10 := by

  aesop (config := {
    maxRuleApplications := 2400
    maxRuleApplicationDepth := 220
    maxNormIterations := 60
    maxGoals := 16
  }) (rule_sets := [-builtin])
    (add norm 100 (by ring))
    (add norm 100 (by field_simp))
    (add norm 100 (by norm_num))
    (add norm 0 (by linarith))
    (add norm 0 (by nlinarith))
    (add norm 0 (by omega))
    (add norm 100 (by abel))
    (add norm 100 (by zify))
    (add norm 0 (by bound))
    (add norm 100 (by interval_cases))
    (add norm 100 (by ext))
    (add norm 100 (by exfalso))
    (add norm 100 (by simp))
    (add norm 0 (by simp_all))
    (add norm 100 (by ring_nf at *))
    (add norm 100 (by norm_num [*] at *))
    (add norm 100 (by norm_cast at *))
    (add norm 100 (by rfl))
    (add norm 100 (by push_cast))
    (add norm 100 (by assumption_mod_cast))
    (add safe 1 (by norm_cast))
    (add safe 1 (by ring_nf))
    (add safe 0 (by split))
    (add unsafe 50% (by field_simp [*] at *))
    (add norm 0 (by grind only [sq_eq_sq]))
    (add norm 0 (by grind only [norm_add_eq_sqrt_iff_real_inner_eq_zero]))
    (add norm 0 (by grind only [mul_self_nonneg]))
    (add norm 0 (by grind only [Real.sqrt_mul_self]))
    (add norm 0 (by grind only [Real.mul_self_sqrt]))
    (add norm 0 (by grind only [mul_eq_one_iff']))
    (add norm 100 (by norm_num [Real.sqrt_eq_iff_mul_self_eq_of_pos] at *))
    (add norm 0 (by grind only [norm_sub_eq_sqrt_iff_real_inner_eq_zero]))
    (add norm 0 (by grind only [Real.sqrt_mul]))
    (add norm 0 (by grind only [Quaternion.sq_eq_normSq]))
    (add norm 0 (by grind only [norm_add_sq_eq_norm_sq_add_norm_sq_iff_real_inner_eq_zero]))
    (add norm 0 (by grind only [Real.sqrt_eq_iff_mul_self_eq]))
    (add norm 0 (by grind only [mul_self_inj_of_nonneg]))
    (add norm 0 (by grind only [norm_add_sq_eq_norm_sq_add_norm_sq_real]))
    (add norm 0 (by grind only [Real.sqrt_mul']))
    (add norm 100 (by rw [Real.arccos_eq_arctan]))
    (add norm 0 (by grind only [WithLp.prod_norm_eq_of_L2]))
    (add norm 0 (by grind only [Quaternion.sq_eq_neg_normSq]))
    (add norm 100 (by norm_num [sq_pos_iff] at *))
    (add norm 0 (by grind only [integral_gaussian]))
    (add norm 0 (by grind only [sq_eq_zero_iff]))
    (add safe 0 (by push_cast [Real.sqrt_eq_iff_sq_eq] at *))
    (add safe 0 (by push_cast [Real.sq_sqrt] at *))
    (add safe 100 (by simp_all [Real.arccos_eq_arcsin]))
    (add safe 100 (by simp_all [Real.sqrt_nonneg]))
    (add safe 100 (by simp_all [Real.sin_arccos]))
    (add safe 100 (by grind only [Real.arccos_of_one_le]))
    (add unsafe 90% (by unfold Real.sqrt_sq))
    (add unsafe 90% (by simp [Real.sqrt_inj] at *))
    (add unsafe 90% (by unfold sq_eq_sq_iff_abs_eq_abs))
    (add unsafe 90% (by grind only [Real.sqrt_pos]))
    (add unsafe 90% (by solve_by_elim [Real.sqrt_eq_cases]))