import Mathlib

theorem mathd_algebra_246 (a b : ℝ) (f : ℝ → ℝ) (h₀ : ∀ x, f x = a * x ^ 4 - b * x ^ 2 + x + 5)
    (h₂ : f (-3) = 2) : f 3 = 8 := by

  aesop (config := {
    maxRuleApplicationDepth := 120
    maxNormIterations := 520
    maxGoals := 16
  }) (rule_sets := [-builtin])
    (add norm 100 (by ring))
    (add norm 100 (by field_simp))
    (add norm 100 (by norm_num))
    (add norm 0 (by linarith))
    (add norm 0 (by nlinarith))
    (add norm 0 (by omega))
    (add norm 100 (by abel))
    (add norm 0 (by bound))
    (add norm 100 (by interval_cases))
    (add norm 1 (by ext))
    (add norm 100 (by split))
    (add norm 100 (by exfalso))
    (add norm 0 (by simp_all))
    (add norm 100 (by ring_nf at *))
    (add norm 100 (by field_simp [*] at *))
    (add norm 100 (by norm_cast at *))
    (add norm 100 (by rfl))
    (add norm 100 (by decide))
    (add norm 100 (by push_cast))
    (add safe 1 (by norm_cast))
    (add safe 1 (by zify))
    (add safe 1 (by ring_nf))
    (add safe 0 (by assumption_mod_cast))
    (add norm 0 (by positivity [one_eq_inv]))
    (add norm 1 (by simp_rw [Real.Angle.coe_neg]))
    (add norm 1 (by simp_rw [Complex.arg_ofReal_of_neg]))
    (add norm 0 (by simp [UpperHalfPlane.ext_iff] at *))
    (add norm 0 (by positivity [eq_false_intro]))
    (add norm 0 (by grind only [sq_eq_one_iff]))
    (add norm 1 (by simp_rw [Hyperreal.coe_neg]))
    (add norm 1 (by solve_by_elim [legendreSym.eq_zero_mod_of_eq_neg_one]))
    (add norm 0 (by grind only [Quaternion.normSq_eq_zero]))
    (add safe 1 (by simp_all [Quaternion.star_eq_neg]))
    (add safe 1 (by simp_all [Quaternion.star_eq_self]))
    (add safe 0 (by nlinarith [Complex.ofReal_neg]))
    (add safe 0 (by rw [← neg_eq]))
    (add safe 1 (by simp_all [Complex.ext_iff]))
    (add unsafe 10% (by nlinarith [eq_inv_iff_mul_eq_one]))
    (add unsafe 10% (by nlinarith [mul_eq_one_iff_eq_inv]))
    (add unsafe 10% (by nlinarith [Quaternion.coe_neg]))
    (add unsafe 10% (by solve_by_elim [eq_neg_self_iff]))
    (add unsafe 10% (by solve_by_elim [inv_eq_one]))
    (add unsafe 10% (by nlinarith [inv_eq_iff_mul_eq_one]))
    (add unsafe 10% (by nlinarith [inv_eq_iff_eq_inv]))
    (add unsafe 10% (by simp_all only [Int.cast_neg]))
    (add unsafe 10% (by nlinarith [QuaternionAlgebra.star_eq_neg]))
    (add unsafe 10% (by nlinarith [Quaternion.ext_iff]))
    (add unsafe 10% (by simp only [mul_self_eq_one_iff] at *))
    (add unsafe 10% (by simp only [sq_eq_sq_iff_eq_or_eq_neg] at *))
    (add unsafe 10% (by simp only [eq_or_eq_neg_of_sq_eq_sq] at *))
    (add unsafe 50% (by simp_rw [Complex.ofReal_inj]))
    (add unsafe 50% (by simp_rw [Complex.arg_ofReal_of_nonneg]))
    (add unsafe 10% (by simp only [quadratic_eq_zero_iff] at *))
    (add unsafe 10% (by nlinarith [Units.val_neg]))
    (add unsafe 10% (by simp_all only [Int.cast_eq_zero]))