import Mathlib

theorem mathd_numbertheory_314 (r n : ℕ) (h₀ : r = 1342 % 13) (h₁ : 0 < n) (h₂ : 1342 ∣ n)
    (h₃ : n % 13 < r) : 6710 ≤ n := by

  aesop (config := {
    maxRuleApplicationDepth := 10
    maxNormIterations := 60
    maxGoals := 128
  })
    (add norm 100 (by ring))
    (add norm 100 (by field_simp))
    (add norm 100 (by norm_num))
    (add norm 100 (by norm_cast))
    (add norm 0 (by linarith))
    (add norm 0 (by nlinarith))
    (add norm 0 (by omega))
    (add norm 100 (by abel))
    (add norm 100 (by zify))
    (add norm 100 (by bound))
    (add norm 100 (by interval_cases))
    (add norm 100 (by ext))
    (add norm 100 (by split))
    (add norm 100 (by exfalso))
    (add norm 100 (by ring_nf at *))
    (add norm 1 (by field_simp [*] at *))
    (add norm 100 (by norm_num [*] at *))
    (add norm 100 (by norm_cast at *))
    (add norm 100 (by rfl))
    (add norm 100 (by decide))
    (add norm 100 (by push_cast))
    (add norm 100 (by assumption_mod_cast))
    (add safe 0 (by ring_nf))
    (add safe 0 (by simp_all))
    (add norm 0 (by grind only [Nat.mod_lt]))
    (add norm 0 (by grind only [Nat.le_of_dvd]))
    (add norm 0 (by grind only [Pell.yn_ge_n]))
    (add norm 0 (by grind only [Nat.pos_of_ne_zero]))
    (add norm 0 (by grind only [MulAction.le_period]))
    (add norm 0 (by grind only [Nat.one_le_of_lt]))
    (add norm 0 (by grind only [ascPochhammer_pos]))
    (add norm 0 (by grind only [pos_of_gt]))
    (add norm 0 (by grind only [Nat.mod_le]))
    (add norm 0 (by grind only [Nat.succ_le_of_lt]))
    (add norm 0 (by grind only [pow_le_pow_right]))
    (add norm 0 (by grind only [Nat.dvd_factorial]))
    (add norm 0 (by grind only [Num.cast_le]))
    (add norm 0 (by grind only [Pell.eq_of_xn_modEq_lem3]))
    (add norm 0 (by grind only [Num.le_to_nat]))
    (add norm 0 (by grind only [tsub_pos_of_lt]))
    (add norm 0 (by grind only [Pell.strictMono_x]))
    (add norm 0 (by grind only [Nat.one_le_pow]))
    (add safe 1 (by rw [Pell.x_pos]))
    (add safe 1 (by rw [le_of_mul_le_mul_right]))
    (add safe 1 (by rw [Nat.mul_div_lt_iff_not_dvd]))
    (add safe 1 (by rw [Nat.div_pos]))
    (add safe 1 (by rw [le_of_mul_le_mul_left]))
    (add safe 1 (by rw [Pell.d_pos]))
    (add safe 1 (by rw [Ordnode.Sized.pos]))
    (add safe 1 (by rw [Nat.mul_le_mul_left]))
    (add safe 1 (by rw [Ordnode.Valid'.rotateL_lemma₂]))
    (add safe 1 (by rw [SzemerediRegularity.seven_le_initialBound]))
    (add safe 1 (by rw [Ordnode.Valid'.rotateL_lemma₄]))
    (add safe 1 (by rw [Nat.div_lt_self]))
    (add safe 1 (by rw [Zsqrtd.d_pos]))
    (add safe 1 (by rw [Ordnode.Valid'.node4L_lemma₁]))