import Mathlib

theorem mathd_algebra_80 (x : ℝ) (h₀ : x ≠ -1) (h₁ : (x - 9) / (x + 1) = 2) : x = -11 := by

  aesop (config := {
    maxRuleApplications := 100
    maxRuleApplicationDepth := 10
    maxNormIterations := 30
    maxGoals := 16
  }) (rule_sets := [-builtin])
    (add norm 100 (by ring))
    (add norm 100 (by field_simp))
    (add norm 100 (by norm_num))
    (add norm 100 (by norm_cast))
    (add norm 0 (by linarith))
    (add norm 0 (by nlinarith))
    (add norm 0 (by omega))
    (add norm 100 (by abel))
    (add norm 100 (by push_neg))
    (add norm 100 (by zify))
    (add norm 100 (by bound))
    (add norm 100 (by interval_cases))
    (add norm 100 (by ext))
    (add norm 100 (by split))
    (add norm 100 (by exfalso))
    (add norm 100 (by ring_nf at *))
    (add norm 1 (by field_simp [*] at *))
    (add norm 100 (by norm_num [*] at *))
    (add norm 100 (by norm_cast at *))
    (add norm 100 (by rfl))
    (add norm 100 (by decide))
    (add norm 100 (by push_cast))
    (add norm 100 (by assumption_mod_cast))
    (add safe 1 (by ring_nf))
    (add safe 0 (by simp_all))
    (add norm 0 (by grind only [div_eq_one]))
    (add norm 0 (by grind only [inv_eq_iff_eq_inv]))
    (add norm 0 (by grind only [mul_eq_one_iff_eq_inv]))
    (add norm 0 (by grind only [quadratic_eq_zero_iff]))
    (add norm 0 (by grind only [inv_eq_one]))
    (add norm 0 (by grind only [eq_inv_iff_mul_eq_one]))
    (add norm 0 (by grind only [neg_div]))
    (add norm 0 (by grind only [div_eq_iff_eq_mul]))
    (add norm 0 (by grind only [Real.pi_ne_zero]))
    (add norm 0 (by grind only [Quaternion.star_eq_self]))
    (add norm 0 (by grind only [div_eq_iff]))
    (add norm 0 (by grind only [Quaternion.star_eq_neg]))
    (add norm 0 (by grind only [inv_eq_iff_mul_eq_one]))
    (add norm 0 (by grind only [mul_self_eq_one_iff]))
    (add norm 0 (by grind only [neg_eq]))
    (add norm 0 (by grind only [Complex.I_ne_zero]))
    (add norm 0 (by grind only [eq_neg_self_iff]))
    (add norm 0 (by grind only [eq_div_iff]))
    (add norm 0 (by grind only [div_neg]))
    (add norm 0 (by grind only [div_eq_iff_eq_mul']))
    (add norm 0 (by grind only [two_ne_zero']))
    (add norm 0 (by grind only [div_eq_one_iff_eq]))
    (add norm 0 (by grind only [Complex.arctan]))
    (add norm 0 (by grind only [Complex.sin_eq_zero_iff]))
    (add norm 0 (by grind only [mul_neg_one]))
    (add norm 0 (by grind only [eq_false_intro]))
    (add norm 0 (by grind only [QuaternionAlgebra.star_eq_neg]))
    (add norm 0 (by grind only [Complex.cpow_neg_one]))
    (add norm 0 (by grind only [Complex.ofReal_inj]))
    (add norm 0 (by grind only [Quaternion.ext_iff]))
    (add norm 0 (by grind only [groupCohomology.mem_oneCocycles_def]))
    (add safe 100 (by grind only [Real.sin_eq_zero_iff]))