import Mathlib

theorem mathd_algebra_346 (f g : ℝ → ℝ) (h₀ : ∀ x, f x = 2 * x - 3) (h₁ : ∀ x, g x = x + 1) :
    g (f 5 - 1) = 7 := by

  aesop (config := {
    maxRuleApplications := 100
    maxRuleApplicationDepth := 10
    maxNormIterations := 520
    maxGoals := 256
  }) (rule_sets := [-builtin])
    (add norm 100 (by ring))
    (add norm 100 (by field_simp))
    (add norm 100 (by norm_num))
    (add norm 100 (by norm_cast))
    (add norm 0 (by linarith))
    (add norm 0 (by nlinarith))
    (add norm 0 (by omega))
    (add norm 100 (by abel))
    (add norm 100 (by zify))
    (add norm 100 (by bound))
    (add norm 100 (by interval_cases))
    (add norm 100 (by ext))
    (add norm 100 (by split))
    (add norm 100 (by exfalso))
    (add norm 100 (by ring_nf at *))
    (add norm 100 (by field_simp [*] at *))
    (add norm 100 (by norm_num [*] at *))
    (add norm 100 (by norm_cast at *))
    (add norm 100 (by rfl))
    (add norm 100 (by decide))
    (add norm 100 (by push_cast))
    (add norm 100 (by assumption_mod_cast))
    (add safe 1 (by ring_nf))
    (add norm 100 (by rw [div_eq_one] at *))
    (add norm 1 (by simp_all [two_mul]))
    (add norm 1 (by simp_all [div_eq_iff_eq_mul']))
    (add norm 1 (by simp_all [eq_div_iff_mul_eq']))
    (add norm 1 (by simp_all [mul_two]))
    (add norm 100 (by rw [Real.Angle.coe_sub] at *))
    (add norm 100 (by simp only [Quaternion.star_add_self]))
    (add norm 0 (by grind only [div_self']))
    (add norm 100 (by rw [Ideal.toCotangent_eq] at *))
    (add norm 100 (by simp only [Ring.multichoose_two]))
    (add norm 100 (by simp only [add_halves]))
    (add norm 0 (by grind only [mul_div_cancel_left]))
    (add norm 0 (by grind only [mul_div_cancel]))
    (add safe 0 (by simp_all [two_ne_zero]))
    (add safe 100 (by rw [two_ne_zero'] at *))
    (add safe 0 (by grind only [Quaternion.coe_sub]))
    (add safe 0 (by grind only [Quaternion.star_add_self']))
    (add safe 0 (by grind only [Quaternion.self_add_star']))
    (add unsafe 10% (by push_cast [div_eq_iff_eq_mul] at *))
    (add unsafe 90% (by grind only [Real.two_mul_arctan_sub_pi]))
    (add unsafe 10% (by apply Real.Angle.angle_eq_iff_two_pi_dvd_sub))
    (add unsafe 10% (by apply Quaternion.self_add_star))
    (add unsafe 90% (by grind only [Real.two_mul_arctan]))
    (add unsafe 90% (by grind only [one_add_one_eq_two]))
    (add unsafe 90% (by grind only [Real.two_mul_arctan_add_pi]))
    (add unsafe 90% (by grind only [Real.sin_two_mul]))
    (add unsafe 90% (by grind only [Int.cast_two]))
    (add unsafe 90% (by norm_num [Nat.cast_two] at *))
    (add unsafe 90% (by grind only [Nat.factorial_two]))
    (add unsafe 90% (by grind only [Nat.cast_descFactorial_two]))
    (add unsafe 90% (by grind only [Complex.sin_two_mul]))
    (add unsafe 90% (by grind only [CharTwo.two_eq_zero]))