import Mathlib

theorem mathd_numbertheory_34 (x : ℕ) (h₀ : x < 100) (h₁ : x * 9 % 100 = 1) : x = 89 := by

  aesop (config := {
    maxRuleApplicationDepth := 10
    maxNormIterations := 60
    maxGoals := 1024
    enableUnfold := false
  })
    (add norm 100 (by ring))
    (add norm 100 (by field_simp))
    (add norm 100 (by norm_num))
    (add norm 100 (by norm_cast))
    (add norm 0 (by linarith))
    (add norm 0 (by nlinarith))
    (add norm 0 (by omega))
    (add norm 100 (by abel))
    (add norm 100 (by zify))
    (add norm 100 (by bound))
    (add norm 100 (by interval_cases))
    (add norm 100 (by ext))
    (add norm 100 (by split))
    (add norm 100 (by exfalso))
    (add norm 100 (by simp))
    (add norm 100 (by ring_nf at *))
    (add norm 1 (by field_simp [*] at *))
    (add norm 100 (by norm_num [*] at *))
    (add norm 100 (by norm_cast at *))
    (add norm 100 (by rfl))
    (add norm 100 (by decide))
    (add norm 100 (by push_cast))
    (add norm 100 (by assumption_mod_cast))
    (add norm 0 (by grind only [Nat.mod_lt]))
    (add norm 0 (by grind only [Pell.eq_of_xn_modEq_lem3]))
    (add norm 0 (by grind only [Nat.mod_le]))
    (add norm 0 (by grind only [PNat.XgcdType.r]))
    (add norm 0 (by grind only [Nat.mod_injOn_Ico]))
    (add norm 0 (by grind only [Nat.dvd_iff_mod_eq_zero]))
    (add norm 0 (by grind only [Nat.add_mod_add_ite]))
    (add norm 0 (by grind only [Num.mod_to_nat]))
    (add norm 0 (by grind only [Nat.mod_mod]))
    (add norm 0 (by grind only [Nat.mod_mod_of_dvd]))
    (add norm 0 (by grind only [jacobiSym.mod_left]))
    (add norm 0 (by grind only [Nat.mod_add_div]))
    (add norm 0 (by grind only [Nat.mod_eq_of_lt]))
    (add norm 0 (by grind only [Nat.mod_eq_zero_of_dvd]))
    (add norm 100 (by rw [← Nat.add_div]))
    (add norm 0 (by grind only [Nat.one_mod_of_ne_one]))
    (add norm 0 (by grind only [Nat.add_mod]))
    (add norm 0 (by grind only [Pell.strictMono_x]))
    (add norm 0 (by grind only [Nat.zero_mod]))
    (add norm 0 (by grind only [Nat.ModEq]))
    (add norm 0 (by grind only [Pell.eq_of_xn_modEq_lem1]))
    (add norm 0 (by grind only [Num.dvd_iff_mod_eq_zero]))
    (add norm 100 (by linarith [Nat.mul_mod]))
    (add norm 0 (by grind only [Nat.le_of_mod_lt]))
    (add norm 0 (by grind only [Nat.mod_modEq]))
    (add norm 0 (by grind only [ZMod.eisenstein_lemma_aux]))
    (add safe 1 (by rw [Nat.ne_of_gt]))
    (add safe 1 (by rw [Nat.mod_mul_left_mod]))
    (add safe 1 (by rw [Pell.x_pos]))
    (add safe 1 (by rw [Nat.mod_mul_mod]))
    (add unsafe 10% (by push_cast [jacobiSym.even_odd] at *))
    (add unsafe 90% (by norm_num [fastJacobiSymAux] at *))