import Mathlib

theorem mathd_algebra_388 (x y z : ℝ) (h₀ : 3 * x + 4 * y - 12 * z = 10)
    (h₁ : -2 * x - 3 * y + 9 * z = -4) : x = 14 := by

  aesop (config := {
    maxRuleApplications := 100
    maxRuleApplicationDepth := 10
    maxNormIterations := 60
    maxGoals := 128
  })
    (add norm 100 (by ring))
    (add norm 100 (by field_simp))
    (add norm 100 (by norm_num))
    (add norm 100 (by norm_cast))
    (add norm 0 (by linarith))
    (add norm 0 (by nlinarith))
    (add norm 100 (by abel))
    (add norm 100 (by zify))
    (add norm 100 (by bound))
    (add norm 100 (by interval_cases))
    (add norm 100 (by ext))
    (add norm 100 (by split))
    (add norm 100 (by exfalso))
    (add norm 100 (by ring_nf at *))
    (add norm 100 (by norm_num [*] at *))
    (add norm 100 (by norm_cast at *))
    (add norm 100 (by rfl))
    (add norm 100 (by decide))
    (add norm 100 (by push_cast))
    (add norm 100 (by assumption_mod_cast))
    (add safe 0 (by omega))
    (add safe 0 (by simp_all))
    (add safe 0 (by field_simp [*] at *))
    (add norm 0 (by grind only [div_eq_one]))
    (add norm 0 (by grind only [div_eq_iff_eq_mul]))
    (add norm 0 (by grind only [div_eq_iff_eq_mul']))
    (add norm 0 (by grind only [Real.arctan_ne_mul_pi_div_two]))
    (add norm 0 (by grind only [soln_unique]))
    (add norm 0 (by grind only [Ideal.toCotangent_eq]))
    (add norm 0 (by grind only [quadratic_eq_zero_iff]))
    (add norm 0 (by grind only [div_eq_one_iff_eq]))
    (add norm 0 (by grind only [irrational_iff_ne_rational]))
    (add norm 0 (by grind only [div_ne_one]))
    (add norm 0 (by grind only [Iff]))
    (add norm 0 (by grind only [neg_div]))
    (add norm 0 (by grind only [div_eq_iff]))
    (add norm 0 (by grind only [two_ne_zero']))
    (add norm 0 (by grind only [mul_self_eq_one_iff]))
    (add norm 0 (by grind only [div_ne_one_of_ne]))
    (add norm 0 (by grind only [IsCyclotomicExtension.Rat.Three.lambda_sq]))
    (add norm 0 (by grind only [WeierstrassCurve.Affine.Y_eq_of_Y_ne]))
    (add norm 0 (by grind only [div_lt_iff]))
    (add norm 0 (by grind only [eq_div_iff]))
    (add norm 0 (by grind only [legendreSym.eq_zero_mod_of_eq_neg_one]))
    (add norm 0 (by grind only [Pell.Solution₁.eq_one_of_x_eq_one]))
    (add norm 0 (by grind only [Quaternion.star_eq_neg]))
    (add norm 0 (by grind only [eq_of_div_eq_one]))
    (add norm 0 (by grind only [Real.Angle.coe_sub]))
    (add norm 0 (by grind only [lt_div_iff]))
    (add norm 0 (by grind only [Real.pi_pos]))
    (add norm 0 (by grind only [div_inv_eq_mul]))
    (add norm 0 (by grind only [mul_left_inj']))
    (add norm 0 (by grind only [mul_lt_mul_left]))
    (add norm 0 (by grind only [mul_lt_mul_right]))
    (add unsafe 90% (by grind only [Real.sin_eq_zero_iff]))