import Mathlib

theorem mathd_algebra_398 (a b c : ℝ) (h₀ : 0 < a ∧ 0 < b ∧ 0 < c) (h₁ : 9 * b = 20 * c)
    (h₂ : 7 * a = 4 * b) : 63 * a = 80 * c := by

  aesop (config := {
    maxRuleApplicationDepth := 220
    maxNormIterations := 60
    enableUnfold := false
  }) (rule_sets := [-builtin])
    (add norm 100 (by ring))
    (add norm 100 (by field_simp))
    (add norm 100 (by norm_num))
    (add norm 0 (by linarith))
    (add norm 0 (by nlinarith))
    (add norm 0 (by omega))
    (add norm 100 (by abel))
    (add norm 100 (by zify))
    (add norm 0 (by bound))
    (add norm 100 (by interval_cases))
    (add norm 100 (by ext))
    (add norm 100 (by exfalso))
    (add norm 100 (by simp))
    (add norm 100 (by ring_nf at *))
    (add norm 100 (by field_simp [*] at *))
    (add norm 100 (by norm_num [*] at *))
    (add norm 100 (by norm_cast at *))
    (add norm 100 (by rfl))
    (add norm 100 (by push_cast))
    (add norm 100 (by assumption_mod_cast))
    (add safe 1 (by norm_cast))
    (add safe 1 (by ring_nf))
    (add safe 0 (by split))
    (add safe 0 (by simp_all))
    (add norm 100 (by rw [← mul_div_cancel₀]))
    (add norm 1 (by simp_all [zero_lt_two]))
    (add norm 0 (by grind only [Real.pi_pos]))
    (add norm 100 (by rw [← div_mul_cancel₀]))
    (add norm 0 (by grind only [Real.exp_half]))
    (add safe 1 (by linarith [zero_lt_two']))
    (add safe 100 (by rw [two_ne_zero'] at *))
    (add unsafe 10% (by push_cast [sq_pos_of_pos] at *))
    (add unsafe 90% (by grind only [mul_pos_iff_of_pos_left]))
    (add unsafe 90% (by grind only [Real.sqrt_pos]))
    (add unsafe 50% (by solve_by_elim [mul_lt_mul_left]))
    (add unsafe 10% (by push_cast [Real.sq_sqrt] at *))
    (add unsafe 10% (by push_cast [two_ne_zero] at *))
    (add unsafe 90% (by grind only [Real.mul_pos]))
    (add unsafe 90% (by grind only [Real.aux₀]))
    (add unsafe 50% (by solve_by_elim [div_lt_iff]))
    (add unsafe 90% (by grind only [mul_pos_iff_of_pos_right]))
    (add unsafe 90% (by grind only [EisensteinSeries.r1_pos]))
    (add unsafe 90% (by grind only [mul_self_pos]))
    (add unsafe 50% (by solve_by_elim [div_lt_iff']))
    (add unsafe 90% (by grind only [Real.rpow_pos_of_pos]))
    (add unsafe 90% (by grind only [mul_lt_mul_right]))
    (add unsafe 90% (by grind only [mul_nonneg_iff_of_pos_left]))
    (add unsafe 90% (by grind only [Real.pi_div_two_pos]))
    (add unsafe 90% (by grind only [EisensteinSeries.r1]))
    (add unsafe 90% (by grind only [Real.log_rpow]))
    (add unsafe 90% (by grind only [one_half_pos]))
    (add unsafe 90% (by grind only [Hyperreal.coe_pos]))
    (add unsafe 90% (by grind only [bernsteinApproximation.δ_pos]))
    (add unsafe 50% (by unfold Real.Gamma_mul_Gamma_add_half_of_pos))
    (add unsafe 90% (by grind only [Real.cosh_pos]))
    (add unsafe 90% (by grind only [one_lt_div]))