import Mathlib

theorem mathd_algebra_338 (a b c : ℝ) (h₀ : 3 * a + b + c = -3) (h₁ : a + 3 * b + c = 9)
    (h₂ : a + b + 3 * c = 19) : a * b * c = -56 := by

  aesop (config := {
    maxRuleApplications := 100
    maxRuleApplicationDepth := 10
    maxNormIterations := 800
    maxGoals := 128
  })
    (add norm 100 (by ring))
    (add norm 100 (by field_simp))
    (add norm 100 (by norm_num))
    (add norm 100 (by norm_cast))
    (add norm 0 (by linarith))
    (add norm 0 (by nlinarith))
    (add norm 100 (by abel))
    (add norm 100 (by push_neg))
    (add norm 100 (by zify))
    (add norm 100 (by bound))
    (add norm 100 (by interval_cases))
    (add norm 100 (by ext))
    (add norm 100 (by split))
    (add norm 100 (by exfalso))
    (add norm 100 (by ring_nf at *))
    (add norm 100 (by norm_num [*] at *))
    (add norm 100 (by norm_cast at *))
    (add norm 100 (by decide))
    (add norm 100 (by push_cast))
    (add norm 100 (by assumption_mod_cast))
    (add safe 0 (by omega))
    (add safe 0 (by simp_all))
    (add safe 0 (by field_simp [*] at *))
    (add safe 0 (by rfl))
    (add norm 100 (by simp only [mul_assoc] at *))
    (add norm 100 (by simp only [mul_left_comm] at *))
    (add norm 100 (by simp only [mul_comm] at *))
    (add norm 100 (by simp only [mul_right_comm] at *))
    (add norm 0 (by grind only [mul_inv]))
    (add norm 0 (by grind only [Quaternion.star_imI]))
    (add norm 0 (by grind only [Quaternion.star_imJ]))
    (add norm 0 (by grind only [Quaternion.coe_commutes]))
    (add norm 0 (by grind only [Pell.isPell_norm]))
    (add norm 0 (by grind only [QuaternionAlgebra.Basis]))
    (add norm 0 (by grind only [Real.Angle.coe_two_pi]))
    (add norm 0 (by grind only [Quaternion.star_mul_eq_coe]))
    (add norm 0 (by grind only [Quaternion.neg_imI]))
    (add safe 1 (by linarith [Quaternion.mul_re]))
    (add safe 1 (by linarith [Quaternion.mul_imK]))
    (add safe 1 (by linarith [QuaternionAlgebra.mul_re]))
    (add safe 1 (by linarith [Pell.Solution₁.x_mul]))
    (add unsafe 50% (by rw [← QuaternionAlgebra.mul_imJ] at *))
    (add unsafe 50% (by simp_all [mul_neg_one]))
    (add unsafe 50% (by simp_all [mul_neg]))
    (add unsafe 50% (by simp_all [neg_mul]))
    (add unsafe 50% (by rw [← QuaternionAlgebra.mul_imI] at *))
    (add unsafe 50% (by simp_all [Complex.I_mul_I]))
    (add unsafe 50% (by rw [← Quaternion.mul_imJ] at *))
    (add unsafe 50% (by simp_all [neg_one_mul]))
    (add unsafe 50% (by rw [← Quaternion.mul_imI] at *))
    (add unsafe 50% (by simp_all [Complex.I_sq]))
    (add unsafe 50% (by rw [← QuaternionAlgebra.mul_imK] at *))
    (add unsafe 50% (by simp_all [Quaternion.coe_mul_eq_smul]))
    (add unsafe 50% (by simp_all [Complex.I]))
    (add unsafe 50% (by simp_all [jacobiTheta₂_term]))
    (add unsafe 50% (by simp_all [Complex.exp_pi_mul_I]))