import Mathlib

theorem mathd_numbertheory_66 : 194 % 11 = 7 := by

  aesop (config := {
    maxRuleApplicationDepth := 10
    maxNormIterations := 520
    maxGoals := 64
    enableUnfold := false
  }) (rule_sets := [-builtin])
    (add norm 100 (by ring))
    (add norm 100 (by field_simp))
    (add norm 100 (by norm_num))
    (add norm 100 (by norm_cast))
    (add norm 0 (by linarith))
    (add norm 0 (by nlinarith))
    (add norm 0 (by omega))
    (add norm 100 (by abel))
    (add norm 100 (by zify))
    (add norm 100 (by bound))
    (add norm 100 (by interval_cases))
    (add norm 100 (by ext))
    (add norm 100 (by split))
    (add norm 100 (by exfalso))
    (add norm 100 (by ring_nf at *))
    (add norm 100 (by field_simp [*] at *))
    (add norm 100 (by norm_num [*] at *))
    (add norm 100 (by norm_cast at *))
    (add norm 100 (by rfl))
    (add norm 100 (by decide))
    (add norm 100 (by push_cast))
    (add norm 100 (by assumption_mod_cast))
    (add safe 1 (by ring_nf))
    (add unsafe 90% (by simp_all))
    (add safe 1 (by rw [Nat.mod_mul_mod]))
    (add unsafe 10% (by push_cast [Nat.mul_mod] at *))
    (add unsafe 10% (by push_cast [Nat.mul_mod_left] at *))
    (add unsafe 10% (by push_cast [jacobiSym.quadratic_reciprocity_one_mod_four] at *))
    (add unsafe 10% (by push_cast [GaussianInt.mod_four_eq_three_of_nat_prime_of_prime] at *))
    (add unsafe 10% (by push_cast [Nat.mod_mod_of_dvd] at *))
    (add unsafe 10% (by push_cast [Nat.mod_mod] at *))
    (add unsafe 10% (by push_cast [Nat.mod_mul_left_mod] at *))
    (add unsafe 10% (by push_cast [Nat.odd_iff] at *))
    (add unsafe 10% (by push_cast [Nat.mod_two_ne_zero] at *))
    (add unsafe 10% (by push_cast [neg_one_pow_eq_pow_mod_two] at *))
    (add unsafe 10% (by push_cast [jacobiSym.quadratic_reciprocity_one_mod_four'] at *))
    (add unsafe 10% (by push_cast [Nat.mul_mod_mod] at *))
    (add unsafe 10% (by push_cast [Nat.mod_eq_zero_of_dvd] at *))
    (add unsafe 10% (by push_cast [Nat.one_mod_of_ne_one] at *))
    (add unsafe 10% (by push_cast [Nat.mod_two_ne_one] at *))
    (add unsafe 10% (by push_cast [Nat.mul_mod_right] at *))
    (add unsafe 10% (by push_cast [Nat.pow_mod] at *))
    (add unsafe 10% (by push_cast [Nat.dvd_iff_mod_eq_zero] at *))
    (add unsafe 10% (by push_cast [Nat.even_iff] at *))
    (add unsafe 10% (by push_cast [Ordinal.mod_mod_of_dvd] at *))
    (add unsafe 10% (by push_cast [Nat.mul_mod_mul_left] at *))
    (add unsafe 10% (by push_cast [Nat.gcd.induction] at *))
    (add unsafe 10% (by push_cast [Num.dvd_iff_mod_eq_zero] at *))
    (add unsafe 10% (by push_cast [Ordinal.mod_mod] at *))
    (add unsafe 10% (by push_cast [jacobiSym.quadratic_reciprocity_three_mod_four] at *))
    (add unsafe 10% (by push_cast [Int.emod_two_ne_one] at *))
    (add unsafe 50% (by simp_rw [Int.mul_emod]))
    (add unsafe 10% (by push_cast [EuclideanDomain.zero_mod] at *))
    (add unsafe 50% (by simp_rw [Int.ofNat_emod]))
    (add unsafe 10% (by push_cast [Nat.mod_two_of_bodd] at *))
    (add unsafe 50% (by simp_rw [Nat.ofDigits_zmod]))