import Mathlib

theorem mathd_algebra_304 : 91 ^ 2 = 8281 := by

  aesop (config := {
    maxRuleApplications := 1100
    maxRuleApplicationDepth := 10
    maxNormIterations := 520
    maxGoals := 64
  }) (rule_sets := [-builtin])
    (add norm 100 (by ring))
    (add norm 100 (by field_simp))
    (add norm 100 (by norm_num))
    (add norm 100 (by norm_cast))
    (add norm 0 (by linarith))
    (add norm 0 (by nlinarith))
    (add norm 0 (by omega))
    (add norm 100 (by abel))
    (add norm 100 (by zify))
    (add norm 100 (by bound))
    (add norm 100 (by interval_cases))
    (add norm 100 (by ext))
    (add norm 100 (by split))
    (add norm 100 (by exfalso))
    (add norm 0 (by simp))
    (add norm 100 (by ring_nf at *))
    (add norm 100 (by field_simp [*] at *))
    (add norm 100 (by norm_num [*] at *))
    (add norm 100 (by norm_cast at *))
    (add norm 100 (by rfl))
    (add norm 0 (by decide))
    (add norm 100 (by push_cast))
    (add norm 100 (by assumption_mod_cast))
    (add safe 1 (by ring_nf))
    (add safe 0 (by simp_all))
    (add unsafe 10% (by rw [ArithmeticFunction.moebius_sq_eq_one_of_squarefree]))
    (add unsafe 10% (by push_cast [QuaternionGroup.xa_sq] at *))
    (add unsafe 10% (by push_cast [quadraticChar_sq_one] at *))
    (add unsafe 10% (by push_cast [quadraticChar_sq_one'] at *))
    (add unsafe 10% (by push_cast [neg_one_sq] at *))
    (add unsafe 10% (by push_cast [ArithmeticFunction.moebius_sq] at *))
    (add unsafe 10% (by rw [legendreSym.sq_one]))
    (add unsafe 10% (by push_cast [mul_pow] at *))
    (add unsafe 90% (by norm_num [MulChar.IsQuadratic.sq_eq_one] at *))
    (add unsafe 10% (by rw [euler_four_squares]))
    (add unsafe 10% (by push_cast [CoxeterSystem.simple_sq] at *))
    (add unsafe 90% (by norm_num [sq_add_sq_mul] at *))
    (add unsafe 10% (by rw [qrSign.sq_eq_one]))
    (add unsafe 10% (by push_cast [sq_sub_sq] at *))
    (add unsafe 10% (by push_cast [legendreSym.sq_one'] at *))
    (add unsafe 90% (by norm_num [pow_two] at *))
    (add unsafe 10% (by push_cast [Int.isUnit_sq] at *))
    (add unsafe 10% (by push_cast [one_pow] at *))
    (add unsafe 10% (by push_cast [even_two] at *))
    (add unsafe 10% (by push_cast [QuaternionGroup.a_one_pow_n] at *))
    (add unsafe 10% (by rw [pow_mul]))
    (add unsafe 10% (by rw [ZMod.χ₄_eq_neg_one_pow]))
    (add unsafe 10% (by rw [Pell.Solution₁.prop_x]))
    (add unsafe 90% (by norm_num [Int.cast_ofNat] at *))
    (add unsafe 10% (by rw [jacobiSym.quadratic_reciprocity]))
    (add unsafe 10% (by push_cast [Pell.Solution₁.prop] at *))
    (add unsafe 90% (by norm_num [gaussSum_sq] at *))
    (add unsafe 10% (by rw [Stirling.stirlingSeq_pow_four_div_stirlingSeq_pow_two_eq]))
    (add unsafe 10% (by push_cast [pow_two_pow_sub_pow_two_pow] at *))
    (add unsafe 10% (by push_cast [neg_sq] at *))
    (add unsafe 90% (by norm_num [Real.rpow_two] at *))
    (add unsafe 10% (by push_cast [ZMod.neg_one_pow_div_two_of_three_mod_four] at *))