import Mathlib

theorem mathd_algebra_188 (σ : Equiv ℝ ℝ) (h : σ.1 2 = σ.2 2) : σ.1 (σ.1 2) = 2 := by

  aesop (config := {
    maxRuleApplicationDepth := 10
    maxGoals := 16
  }) (rule_sets := [-builtin])
    (add norm 100 (by ring))
    (add norm 100 (by field_simp))
    (add norm 100 (by norm_num))
    (add norm 100 (by norm_cast))
    (add norm 0 (by linarith))
    (add norm 0 (by nlinarith))
    (add norm 0 (by omega))
    (add norm 100 (by abel))
    (add norm 0 (by bound))
    (add norm 100 (by interval_cases))
    (add norm 0 (by ext))
    (add norm 100 (by split))
    (add norm 100 (by exfalso))
    (add norm 100 (by ring_nf at *))
    (add norm 100 (by field_simp [*] at *))
    (add norm 100 (by norm_num [*] at *))
    (add norm 100 (by norm_cast at *))
    (add norm 100 (by rfl))
    (add norm 0 (by decide))
    (add norm 100 (by push_cast))
    (add norm 100 (by assumption_mod_cast))
    (add safe 1 (by zify))
    (add safe 1 (by ring_nf))
    (add safe 0 (by simp_all))
    (add norm 1 (by simp_all [funext]))
    (add norm 1 (by simp_all [Eq.symm]))
    (add norm 0 (by rw [← Set.BijOn.invOn_invFunOn]))
    (add norm 1 (by simp_all [congrArg]))
    (add norm 1 (by simp_all [Subtype.ext]))
    (add norm 1 (by simp_all [Eq.trans]))
    (add norm 0 (by rw [← DomMulAct.stabilizerEquiv_invFun]))
    (add norm 0 (by grind only [Pell.Solution₁.y_mk]))
    (add safe 1 (by simp only [Function.invFun_eq]))
    (add safe 0 (by field_simp [Function.leftInverse_invFun] at *))
    (add safe 1 (by simp only [Submodule.quotientPi_aux.invFun]))
    (add safe 0 (by grind only [congrFun]))
    (add safe 100 (by simp [Function.invFunOn_apply_mem] at *))
    (add safe 0 (by grind only [Set.InjOn.invFunOn_image]))
    (add safe 0 (by simp_all [two_ne_zero]))
    (add safe 100 (by simp [Function.invFun] at *))
    (add safe 0 (by grind only [PEquiv]))
    (add safe 100 (by grind only [vsub_left_cancel]))
    (add unsafe 10% (by apply Function.invFun_surjective))
    (add unsafe 10% (by apply Function.rightInverse_invFun))
    (add unsafe 10% (by apply Function.invFunOn_apply_eq))
    (add unsafe 10% (by apply Function.invFunOn_eq))
    (add unsafe 10% (by apply Nat.cast_two))
    (add unsafe 10% (by apply Trivialization.Prod.invFun'))
    (add unsafe 10% (by apply Function.invFunOn_mem))
    (add unsafe 10% (by apply Function.invFunOn_pos))
    (add unsafe 10% (by apply CharTwo.two_eq_zero))
    (add unsafe 10% (by apply QuaternionAlgebra.eq_re_of_eq_coe))
    (add unsafe 10% (by apply Nat.cast_descFactorial_two))
    (add unsafe 90% (by grind only [Nat.factorial_two]))
    (add unsafe 10% (by apply Cardinal.lift_two))
    (add unsafe 10% (by apply IsDedekindDomain.HeightOneSpectrum.adicValued_apply))