import Mathlib

theorem mathd_algebra_441 (x : ℝ) (h₀ : x ≠ 0) :
    12 / (x * x) * (x ^ 4 / (14 * x)) * (35 / (3 * x)) = 10 := by

  aesop (config := {
    maxRuleApplications := 1600
    maxRuleApplicationDepth := 10
    maxNormIterations := 180
    enableUnfold := false
    useDefaultSimpSet := false
  }) (rule_sets := [-builtin])
    (add norm 100 (by ring))
    (add norm 100 (by field_simp))
    (add norm 100 (by norm_num))
    (add norm 0 (by linarith))
    (add norm 0 (by nlinarith))
    (add norm 0 (by omega))
    (add norm 100 (by abel))
    (add norm 100 (by zify))
    (add norm 100 (by gcongr))
    (add norm 0 (by bound))
    (add norm 100 (by interval_cases))
    (add norm 100 (by ext))
    (add norm 100 (by split))
    (add norm 100 (by exfalso))
    (add norm 100 (by simp))
    (add norm 100 (by ring_nf at *))
    (add norm 1 (by field_simp [*] at *))
    (add norm 100 (by norm_num [*] at *))
    (add norm 100 (by norm_cast at *))
    (add norm 100 (by rfl))
    (add norm 100 (by decide))
    (add norm 100 (by push_cast))
    (add norm 100 (by assumption_mod_cast))
    (add safe 100 (by norm_cast))
    (add safe 0 (by ring_nf))
    (add norm 100 (by apply div_self))
    (add norm 100 (by apply div_mul_cancel₀))
    (add norm 100 (by apply mul_one_div))
    (add norm 100 (by apply mul_div_mul_left))
    (add norm 100 (by simp only [div_eq_one_iff_eq] at *))
    (add norm 100 (by simp only [mul_assoc] at *))
    (add norm 100 (by simp only [mul_comm] at *))
    (add norm 100 (by apply sub_div))
    (add norm 100 (by apply div_ne_zero))
    (add norm 100 (by apply mul_div_mul_right))
    (add norm 0 (by grind only [Complex.cpow_add]))
    (add norm 100 (by simp only [eq_div_iff_mul_eq] at *))
    (add norm 100 (by simp only [mul_right_comm] at *))
    (add norm 100 (by apply mul_ne_zero))
    (add norm 100 (by apply div_pow))
    (add norm 0 (by nlinarith [Complex.two_pi_I_ne_zero]))
    (add safe 100 (by rw [two_ne_zero'] at *))
    (add safe 0 (by linarith [one_div]))
    (add unsafe 50% (by apply mul_div_cancel₀))
    (add unsafe 10% (by linarith [mul_div_assoc]))
    (add unsafe 10% (by push_cast [mul_div_cancel_right₀] at *))
    (add unsafe 10% (by push_cast [mul_div_cancel_left₀] at *))
    (add unsafe 10% (by push_cast [div_eq_iff] at *))
    (add unsafe 10% (by push_cast [eq_div_iff] at *))
    (add unsafe 10% (by push_cast [two_ne_zero] at *))
    (add unsafe 10% (by linarith [mul_div]))
    (add unsafe 10% (by linarith [div_div]))
    (add unsafe 50% (by apply Complex.log_ofReal_mul))
    (add unsafe 50% (by simp_all [neg_div]))
    (add unsafe 10% (by linarith [mul_lt_mul_left]))
    (add unsafe 90% (by grind only [Real.Gamma_two]))
    (add unsafe 50% (by apply mul_le_mul_left))