import Mathlib

theorem mathd_numbertheory_135 (n A B C : ℕ) (h₀ : n = 3 ^ 17 + 3 ^ 10) (h₁ : 11 ∣ n + 1)
    (h₂ : [A, B, C].Pairwise (· ≠ ·)) (h₃ : {A, B, C} ⊂ Finset.Icc 0 9) (h₄ : Odd A ∧ Odd C)
    (h₅ : ¬3 ∣ B) (h₆ : Nat.digits 10 n = [B, A, B, C, C, A, C, B, A]) :
    100 * A + 10 * B + C = 129 := by

  aesop (config := {
    maxRuleApplicationDepth := 10
    maxNormIterations := 520
    maxGoals := 64
  })
    (add norm 100 (by ring))
    (add norm 100 (by field_simp))
    (add norm 100 (by norm_num))
    (add norm 100 (by norm_cast))
    (add norm 0 (by linarith))
    (add norm 0 (by nlinarith))
    (add norm 0 (by omega))
    (add norm 100 (by abel))
    (add norm 100 (by zify))
    (add norm 100 (by bound))
    (add norm 100 (by interval_cases))
    (add norm 100 (by ext))
    (add norm 100 (by exfalso))
    (add norm 100 (by simp))
    (add norm 100 (by ring_nf at *))
    (add norm 1 (by field_simp [*] at *))
    (add norm 100 (by norm_num [*] at *))
    (add norm 100 (by norm_cast at *))
    (add norm 100 (by rfl))
    (add norm 100 (by push_cast))
    (add norm 100 (by assumption_mod_cast))
    (add safe 1 (by ring_nf))
    (add safe 0 (by split))
    (add unsafe 90% (by simp_all))
    (add norm 0 (by simp [Zsqrtd.SqLe] at *))
    (add norm 100 (by solve_by_elim [Pell.pellZd]))
    (add norm 1 (by simp only [Pell.xz]))
    (add norm 100 (by solve_by_elim [Pell.pellZd_add]))
    (add norm 0 (by grind only [Pell.xn_modEq_x2n_sub]))
    (add norm 0 (by simp [Zsqrtd.sqLe_smul] at *))
    (add norm 0 (by grind only [Pell.eq_of_xn_modEq_lem2]))
    (add norm 0 (by simp [Zsqrtd.add_def] at *))
    (add norm 1 (by simp_all [two_mul]))
    (add norm 1 (by simp_all [primorial_add_le]))
    (add norm 0 (by grind only [Nat.add_sub_of_le]))
    (add norm 100 (by norm_num [Nat.add_le_add] at *))
    (add norm 100 (by norm_num [Pell.yz] at *))
    (add norm 0 (by grind only [Nat.mod_add_div]))
    (add norm 0 (by simp [Nat.succ_mul_centralBinom_succ] at *))
    (add norm 0 (by grind only [Pell.xn_modEq_x2n_sub_lem]))
    (add safe 0 (by norm_num [mul_add_mul] at *))
    (add safe 0 (by norm_num [Pell.isPell_norm] at *))
    (add safe 100 (by grind only [Zsqrtd.not_divides_sq]))
    (add safe 0 (by norm_num [Zsqrtd.divides_sq_eq_zero_z] at *))
    (add safe 100 (by grind only [Zsqrtd]))
    (add unsafe 10% (by push_cast [mul_left_comm] at *))
    (add unsafe 50% (by solve_by_elim [mul_right_comm]))
    (add unsafe 50% (by solve_by_elim [mul_comm]))
    (add unsafe 50% (by solve_by_elim [mul_assoc]))
    (add unsafe 50% (by simp_rw [Pell.d]))
    (add unsafe 90% (by simp [Nat.div_add_mod] at *))
    (add unsafe 50% (by simp_rw [Pell.dz_val]))
    (add unsafe 50% (by simp_rw [Pell.xn_add]))
    (add unsafe 90% (by simp [Nat.div_add_mod'] at *))
    (add unsafe 90% (by simp_rw [Pell.isPell_pellZd]))
    (add unsafe 50% (by simp_rw [Pell.yn_add]))