import Mathlib

theorem mathd_algebra_160 (n x : ℝ) (h₀ : n + x = 97) (h₁ : n + 5 * x = 265) : n + 2 * x = 139 := by

  aesop (config := {
    maxRuleApplicationDepth := 220
    maxNormIterations := 60
    maxGoals := 256
  }) (rule_sets := [-builtin])
    (add norm 100 (by ring))
    (add norm 100 (by field_simp))
    (add norm 100 (by norm_num))
    (add norm 100 (by norm_cast))
    (add norm 0 (by linarith))
    (add norm 0 (by nlinarith))
    (add norm 0 (by omega))
    (add norm 100 (by abel))
    (add norm 100 (by zify))
    (add norm 100 (by bound))
    (add norm 100 (by interval_cases))
    (add norm 100 (by ext))
    (add norm 100 (by split))
    (add norm 100 (by exfalso))
    (add norm 100 (by ring_nf at *))
    (add norm 100 (by norm_num [*] at *))
    (add norm 100 (by norm_cast at *))
    (add norm 100 (by rfl))
    (add norm 100 (by push_cast))
    (add norm 100 (by assumption_mod_cast))
    (add safe 1 (by ring_nf))
    (add safe 0 (by simp_all))
    (add safe 0 (by field_simp [*] at *))
    (add norm 100 (by simp only [mul_left_comm] at *))
    (add norm 100 (by simp only [mul_assoc] at *))
    (add norm 100 (by simp only [mul_right_comm] at *))
    (add norm 100 (by simp only [mul_comm] at *))
    (add norm 0 (by grind only [Quaternion.self_add_star]))
    (add norm 0 (by grind only [mul_two]))
    (add norm 0 (by grind only [mul_lt_mul_iff_left]))
    (add norm 0 (by grind only [QuaternionAlgebra.mul_imI]))
    (add norm 0 (by grind only [QuaternionAlgebra.self_add_star]))
    (add norm 1 (by norm_num [Surreal.double_powHalf_succ_eq_powHalf] at *))
    (add norm 100 (by rw [← ack_two]))
    (add norm 0 (by grind only [mul_lt_mul_iff_right]))
    (add norm 0 (by grind only [QuaternionAlgebra.mul_imJ]))
    (add norm 0 (by grind only [Pell.isPell_norm]))
    (add norm 0 (by grind only [QuaternionGroup.a_mul_a]))
    (add norm 0 (by grind only [mul_mul_mul_comm]))
    (add norm 100 (by simp only [mul_le_mul_iff_left]))
    (add safe 0 (by norm_num [mul_add_mul] at *))
    (add safe 1 (by simp_all [Quaternion.star_add_self]))
    (add safe 1 (by simp_all [Quaternion.star_add_self']))
    (add safe 1 (by simp_all [Quaternion.self_add_star']))
    (add safe 1 (by linarith [Pell.Solution₁.y_mul]))
    (add safe 1 (by linarith [Pell.Solution₁.x_mul]))
    (add safe 1 (by linarith [QuaternionAlgebra.mul_re]))
    (add safe 1 (by linarith [mul_le_mul_left]))
    (add unsafe 10% (by push_cast [two_mul] at *))
    (add unsafe 90% (by norm_num [Quaternion.coe_commutes] at *))
    (add unsafe 10% (by push_cast [mul_lt_mul_left] at *))
    (add unsafe 50% (by simp_all [jacobiTheta₂_term]))
    (add unsafe 90% (by grind only [mul_self]))
    (add unsafe 90% (by grind only [Real.Angle.coe_two_pi]))
    (add unsafe 50% (by simp_all [Quaternion.coe_add]))