import Mathlib

theorem mathd_algebra_296 : abs ((3491 - 60) * (3491 + 60) - 3491 ^ 2 : ℤ) = 3600 := by

  aesop (config := {
    maxNormIterations := 30
    useSimpAll := false
    enableUnfold := false
  })
    (add norm 100 (by ring))
    (add norm 100 (by field_simp))
    (add norm 100 (by norm_num))
    (add norm 0 (by linarith))
    (add norm 0 (by nlinarith))
    (add norm 0 (by positivity))
    (add norm 0 (by omega))
    (add norm 100 (by abel))
    (add norm 0 (by push_neg))
    (add norm 0 (by gcongr))
    (add norm 0 (by bound))
    (add norm 100 (by interval_cases))
    (add norm 0 (by ext))
    (add norm 100 (by exfalso))
    (add norm 0 (by simp))
    (add norm 0 (by ring_nf at *))
    (add norm 100 (by field_simp [*] at *))
    (add norm 100 (by norm_num [*] at *))
    (add norm 100 (by norm_cast at *))
    (add norm 100 (by rfl))
    (add norm 0 (by decide))
    (add norm 100 (by push_cast))
    (add safe 1 (by zify))
    (add safe 0 (by split))
    (add safe 0 (by assumption_mod_cast))
    (add unsafe 50% (by norm_cast))
    (add unsafe 10% (by ring_nf))
    (add unsafe 90% (by simp_all))
    (add norm 100 (by rw [← mabs_of_one_lt]))
    (add norm 0 (by grind only [Real.sq_sqrt]))
    (add norm 0 (by grind only [sq_add_sq_mul]))
    (add norm 0 (by grind only [Pell.Solution₁.prop_y]))
    (add norm 0 (by grind only [Complex.sq_abs]))
    (add norm 0 (by grind only [Real.sqrt_sq]))
    (add norm 0 (by grind only [UpperHalfPlane.dist_coe_center_sq]))
    (add norm 0 (by grind only [EisensteinSeries.auxbound1]))
    (add norm 0 (by grind only [EisensteinSeries.auxbound2]))
    (add safe 100 (by simp [Pell.Solution₁.prop] at *))
    (add safe 0 (by simp_all [Real.rpow_two]))
    (add safe 1 (by rw [aux_add]))
    (add safe 0 (by simp_all [pow_two]))
    (add safe 1 (by rw [norm_add_sq]))
    (add unsafe 10% (by push_cast [sq_sub_sq] at *))
    (add unsafe 50% (by simp only [abs_sq]))
    (add unsafe 10% (by push_cast [sq_lt_sq] at *))
    (add unsafe 10% (by push_cast [sq_abs] at *))
    (add unsafe 10% (by push_cast [sub_sq] at *))
    (add unsafe 50% (by simp only [sq_le_sq]))
    (add unsafe 50% (by simp only [Pell.Solution₁.prop_x]))
    (add unsafe 50% (by simp only [sq_add_sq_mul_sq_add_sq]))
    (add unsafe 50% (by simp only [norm_add_sq_real]))
    (add unsafe 50% (by simp only [Real.sqrt_sq_eq_abs]))
    (add unsafe 50% (by simp only [norm_sub_sq_real]))
    (add unsafe 50% (by simp only [abs_mul]))
    (add unsafe 50% (by simp only [Real.abs_sin_half]))
    (add unsafe 50% (by simp only [abs_two]))
    (add unsafe 50% (by simp only [sq_add_mul_sq_mul_sq_add_mul_sq]))
    (add unsafe 50% (by simp only [mabs_div_comm]))
    (add unsafe 50% (by simp only [Rel.abs_edgeDensity_sub_edgeDensity_le_two_mul_sub_sq]))
    (add unsafe 50% (by simp only [Int.sq_eq_one_of_sq_le_three]))