import Mathlib

theorem mathd_numbertheory_207 : 8 * 9 ^ 2 + 5 * 9 + 2 = 695 := by

  aesop (config := {
    maxRuleApplicationDepth := 220
    maxNormIterations := 520
  }) (rule_sets := [-builtin])
    (add norm 100 (by ring))
    (add norm 100 (by field_simp))
    (add norm 100 (by norm_num))
    (add norm 100 (by norm_cast))
    (add norm 0 (by linarith))
    (add norm 0 (by nlinarith))
    (add norm 0 (by omega))
    (add norm 100 (by abel))
    (add norm 100 (by zify))
    (add norm 0 (by bound))
    (add norm 100 (by interval_cases))
    (add norm 100 (by ext))
    (add norm 100 (by split))
    (add norm 100 (by exfalso))
    (add norm 100 (by ring_nf at *))
    (add norm 100 (by field_simp [*] at *))
    (add norm 100 (by norm_num [*] at *))
    (add norm 100 (by norm_cast at *))
    (add norm 100 (by rfl))
    (add norm 100 (by push_cast))
    (add norm 100 (by assumption_mod_cast))
    (add safe 1 (by ring_nf))
    (add safe 0 (by simp_all))
    (add safe 0 (by simp_all [sq_add_sq_mul]))
    (add safe 0 (by simp_all [euler_four_squares]))
    (add safe 1 (by simp only [Pell.Solution₁.prop_x] at *))
    (add safe 1 (by simp only [Pell.Solution₁.prop_y] at *))
    (add safe 0 (by simp_all [pow_two]))
    (add safe 0 (by simp_all [sum_four_sq_mul_sum_four_sq]))
    (add safe 0 (by simp_all [sum_eight_sq_mul_sum_eight_sq]))
    (add safe 0 (by simp_all [Real.cosh_sq']))
    (add safe 1 (by linarith [two_mul_le_add_sq]))
    (add safe 1 (by rw [Complex.sq_abs]))
    (add safe 1 (by rw [Quaternion.normSq_def']))
    (add safe 0 (by simp_all [Real.rpow_two]))
    (add safe 0 (by simp_all [Real.cosh_two_mul]))
    (add safe 1 (by linarith [Int.le_self_sq]))
    (add safe 0 (by simp_all [Real.sinh_two_mul]))
    (add unsafe 50% (by simp only [sq_add_mul_sq_mul_sq_add_mul_sq]))
    (add unsafe 50% (by simp only [sq_add_sq_mul_sq_add_sq]))
    (add unsafe 10% (by push_cast [sq_sub_sq] at *))
    (add unsafe 10% (by push_cast [add_sq] at *))
    (add unsafe 10% (by push_cast [QuaternionGroup.xa_sq] at *))
    (add unsafe 10% (by push_cast [Pell.Solution₁.prop] at *))
    (add unsafe 10% (by push_cast [CoxeterSystem.simple_sq] at *))
    (add unsafe 50% (by simp only [Int.sq_eq_one_of_sq_le_three]))
    (add unsafe 10% (by push_cast [sq_abs] at *))
    (add unsafe 10% (by push_cast [sq_nonneg] at *))
    (add unsafe 10% (by push_cast [sub_sq] at *))
    (add unsafe 10% (by push_cast [ArithmeticFunction.moebius_sq] at *))
    (add unsafe 10% (by push_cast [Real.sq_sqrt] at *))
    (add unsafe 10% (by push_cast [Real.cosh_sq] at *))
    (add unsafe 10% (by push_cast [even_two_mul] at *))
    (add unsafe 10% (by push_cast [UpperHalfPlane.dist_coe_center_sq] at *))
    (add unsafe 10% (by push_cast [sq_lt_sq] at *))