import Mathlib

theorem mathd_algebra_427 (x y z : ℝ) (h₀ : 3 * x + y = 17) (h₁ : 5 * y + z = 14)
    (h₂ : 3 * x + 5 * z = 41) : x + y + z = 12 := by

  aesop (config := {
    maxRuleApplications := 100
    maxRuleApplicationDepth := 10
    maxNormIterations := 60
    maxGoals := 128
    enableSimp := false
  }) (rule_sets := [-builtin])
    (add norm 100 (by ring))
    (add norm 100 (by field_simp))
    (add norm 100 (by norm_num))
    (add norm 100 (by norm_cast))
    (add norm 0 (by linarith))
    (add norm 0 (by nlinarith))
    (add norm 0 (by omega))
    (add norm 100 (by abel))
    (add norm 100 (by zify))
    (add norm 100 (by bound))
    (add norm 100 (by interval_cases))
    (add norm 100 (by ext))
    (add norm 100 (by split))
    (add norm 100 (by exfalso))
    (add norm 100 (by ring_nf at *))
    (add norm 100 (by norm_num [*] at *))
    (add norm 100 (by norm_cast at *))
    (add norm 100 (by rfl))
    (add norm 100 (by decide))
    (add norm 100 (by push_cast))
    (add norm 100 (by assumption_mod_cast))
    (add safe 0 (by simp_all))
    (add safe 0 (by field_simp [*] at *))
    (add norm 0 (by grind only [mul_add_mul]))
    (add norm 100 (by simp only [mul_left_comm] at *))
    (add norm 100 (by simp only [mul_comm] at *))
    (add norm 0 (by grind only [mul_lt_mul_left]))
    (add norm 100 (by simp only [mul_right_comm] at *))
    (add norm 0 (by grind only [Quaternion.star_add_self]))
    (add norm 0 (by grind only [two_mul]))
    (add norm 0 (by grind only [Real.mul_self_sqrt]))
    (add norm 0 (by grind only [Quaternion.self_add_star]))
    (add norm 0 (by grind only [sq_add_sq_mul]))
    (add norm 0 (by grind only [Real.sq_sqrt]))
    (add norm 100 (by simp only [mul_assoc] at *))
    (add norm 0 (by grind only [mul_lt_mul_right]))
    (add norm 0 (by grind only [mul_nonneg_iff_of_pos_left]))
    (add norm 0 (by grind only [EisensteinSeries.r1]))
    (add norm 0 (by grind only [mul_self_nonneg]))
    (add norm 0 (by grind only [mul_two]))
    (add norm 0 (by grind only [Real.sqrt_sq]))
    (add norm 0 (by grind only [QuaternionAlgebra.self_add_star]))
    (add norm 0 (by grind only [Zsqrtd.divides_sq_eq_zero_z]))
    (add norm 0 (by grind only [zero_lt_two]))
    (add safe 1 (by linarith [zero_lt_two']))
    (add safe 1 (by linarith [Pell.Solution₁.y_mul]))
    (add unsafe 90% (by grind only [Real.mul_pos]))
    (add unsafe 90% (by grind only [EisensteinSeries.r1_pos]))
    (add unsafe 90% (by grind only [mul_pos_iff_of_pos_left]))
    (add unsafe 10% (by push_cast [sq_pos_of_pos] at *))
    (add unsafe 50% (by rw [← div_lt_iff] at *))
    (add unsafe 90% (by grind only [pow_two]))
    (add unsafe 90% (by grind only [Real.sqrt_pos]))
    (add unsafe 90% (by grind only [abs_mul_abs_self]))
    (add unsafe 90% (by grind only [Real.add_lt_add_iff_left]))