import Mathlib

theorem mathd_algebra_412 (x y : ℝ) (h₀ : x + y = 25) (h₁ : x - y = 11) : x = 18 := by

  aesop (config := {
    maxRuleApplications := 100
    maxRuleApplicationDepth := 10
    maxNormIterations := 520
    maxGoals := 16
    enableSimp := false
  }) (rule_sets := [-builtin])
    (add norm 100 (by ring))
    (add norm 100 (by field_simp))
    (add norm 100 (by norm_num))
    (add norm 100 (by norm_cast))
    (add norm 0 (by linarith))
    (add norm 0 (by nlinarith))
    (add norm 0 (by omega))
    (add norm 100 (by abel))
    (add norm 100 (by zify))
    (add norm 100 (by bound))
    (add norm 100 (by interval_cases))
    (add norm 100 (by ext))
    (add norm 100 (by split))
    (add norm 100 (by exfalso))
    (add norm 100 (by ring_nf at *))
    (add norm 100 (by field_simp [*] at *))
    (add norm 100 (by norm_num [*] at *))
    (add norm 100 (by norm_cast at *))
    (add norm 100 (by rfl))
    (add norm 100 (by decide))
    (add norm 100 (by push_cast))
    (add norm 100 (by assumption_mod_cast))
    (add safe 1 (by ring_nf))
    (add norm 0 (by grind only [eq_div_iff_mul_eq']))
    (add norm 0 (by grind only [div_eq_one]))
    (add norm 0 (by grind only [two_mul]))
    (add norm 0 (by grind only [div_eq_iff_eq_mul']))
    (add norm 0 (by grind only [Real.Angle.coe_sub]))
    (add norm 0 (by grind only [mul_div_cancel_left]))
    (add norm 0 (by grind only [mul_two]))
    (add norm 0 (by grind only [Quaternion.coe_sub]))
    (add norm 0 (by grind only [mul_div_cancel]))
    (add norm 0 (by grind only [mul_div_cancel_right]))
    (add norm 0 (by grind only [Quaternion.star_add_self]))
    (add norm 0 (by grind only [eq_mul_of_div_eq']))
    (add norm 0 (by grind only [eq_div_iff_mul_eq]))
    (add norm 0 (by grind only [Real.Angle.angle_eq_iff_two_pi_dvd_sub]))
    (add norm 0 (by grind only [add_halves]))
    (add norm 0 (by grind only [Quaternion.self_add_star]))
    (add norm 0 (by grind only [groupCohomology.mem_twoCocycles_def]))
    (add norm 100 (by simp only [parallelogram_law_with_norm]))
    (add norm 0 (by grind only [Ideal.toCotangent_eq]))
    (add norm 0 (by grind only [Polynomial.natTrailingDegree_mul_mirror]))
    (add unsafe 10% (by push_cast [div_eq_iff_eq_mul] at *))
    (add unsafe 10% (by push_cast [two_ne_zero'] at *))
    (add unsafe 10% (by push_cast [two_ne_zero] at *))
    (add unsafe 90% (by grind only [Real.two_mul_arctan_sub_pi]))
    (add unsafe 90% (by grind only [Real.two_mul_arctan]))
    (add unsafe 90% (by grind only [pow_two]))
    (add unsafe 90% (by grind only [Real.two_mul_arctan_add_pi]))
    (add unsafe 90% (by grind only [Real.sin_two_mul]))
    (add unsafe 90% (by grind only [InnerProductSpaceable.add_left_aux4]))
    (add unsafe 90% (by grind only [InnerProductSpaceable]))
    (add unsafe 90% (by grind only [sub_half]))
    (add unsafe 90% (by grind only [Nat.factorial_two]))