import Mathlib

theorem mathd_algebra_148 (c : ℝ) (f : ℝ → ℝ) (h₀ : ∀ x, f x = c * x ^ 3 - 9 * x + 3)
    (h₁ : f 2 = 9) : c = 3 := by

  aesop (config := {
    maxRuleApplications := 1100
    maxRuleApplicationDepth := 220
    maxNormIterations := 520
    maxGoals := 16
  }) (rule_sets := [-builtin])
    (add norm 100 (by ring))
    (add norm 100 (by field_simp))
    (add norm 100 (by norm_num))
    (add norm 0 (by linarith))
    (add norm 0 (by nlinarith))
    (add norm 0 (by omega))
    (add norm 100 (by abel))
    (add norm 100 (by zify))
    (add norm 0 (by bound))
    (add norm 100 (by interval_cases))
    (add norm 100 (by ext))
    (add norm 100 (by split))
    (add norm 100 (by exfalso))
    (add norm 100 (by simp))
    (add norm 100 (by ring_nf at *))
    (add norm 100 (by field_simp [*] at *))
    (add norm 100 (by norm_cast at *))
    (add norm 100 (by rfl))
    (add norm 100 (by push_cast))
    (add norm 100 (by assumption_mod_cast))
    (add safe 1 (by norm_cast))
    (add safe 1 (by ring_nf))
    (add unsafe 90% (by simp_all))
    (add norm 0 (by grind only [sq_eq_one_iff]))
    (add norm 0 (by grind only [sq_add_sq_mul]))
    (add norm 1 (by simp_all [zero_lt_two]))
    (add norm 100 (by norm_num [div_eq_one] at *))
    (add norm 0 (by grind only [Quaternion.sq_eq_normSq]))
    (add norm 0 (by grind only [mul_eq_one_iff']))
    (add norm 0 (by grind only [CoxeterSystem.simple_sq]))
    (add norm 100 (by rw [← ArithmeticFunction.moebius_sq]))
    (add norm 1 (by simp_all [two_mul]))
    (add norm 1 (by simp_all [div_eq_iff_eq_mul']))
    (add norm 1 (by norm_num [Polynomial.natTrailingDegree_mul_mirror] at *))
    (add safe 0 (by simp_all [pow_two]))
    (add safe 1 (by simp_all [sq_eq_zero_iff]))
    (add safe 0 (by simp_all [two_ne_zero]))
    (add safe 1 (by simp_all [Quaternion.star_eq_self]))
    (add safe 0 (by simp_all [Nat.cast_two]))
    (add safe 0 (by nlinarith [even_two]))
    (add safe 0 (by simp_all [Int.sq_of_gcd_eq_one]))
    (add unsafe 90% (by unfold sq_eq_sq))
    (add unsafe 10% (by simp only [eq_or_eq_neg_of_sq_eq_sq] at *))
    (add unsafe 10% (by simp only [sq_eq_sq_iff_eq_or_eq_neg] at *))
    (add unsafe 90% (by unfold Real.sqrt_eq_iff_sq_eq))
    (add unsafe 90% (by unfold sq_pos_of_pos))
    (add unsafe 50% (by solve_by_elim [Quaternion.sq_eq_neg_normSq]))
    (add unsafe 90% (by grind only [Real.rpow_two]))
    (add unsafe 90% (by unfold sq_sub_sq))
    (add unsafe 90% (by unfold sq_abs))
    (add unsafe 10% (by rw [legendreSym.eq_zero_mod_of_eq_neg_one] at *))
    (add unsafe 90% (by unfold Real.sq_sqrt))
    (add unsafe 10% (by positivity [gaussSum_sq]))
    (add unsafe 10% (by rw [sq_nonneg] at *))
    (add unsafe 90% (by grind only [CharTwo.two_eq_zero]))