import Mathlib

theorem mathd_numbertheory_559 (x y : ℕ) (h₀ : x % 3 = 2) (h₁ : y % 5 = 4) (h₂ : x % 10 = y % 10) :
    14 ≤ x := by

  aesop (config := {
    maxRuleApplicationDepth := 10
    maxNormIterations := 60
    maxGoals := 128
    enableUnfold := false
  })
    (add norm 100 (by ring))
    (add norm 100 (by field_simp))
    (add norm 100 (by norm_num))
    (add norm 100 (by norm_cast))
    (add norm 0 (by linarith))
    (add norm 0 (by nlinarith))
    (add norm 0 (by omega))
    (add norm 100 (by abel))
    (add norm 100 (by zify))
    (add norm 100 (by bound))
    (add norm 100 (by interval_cases))
    (add norm 100 (by ext))
    (add norm 100 (by split))
    (add norm 100 (by exfalso))
    (add norm 100 (by ring_nf at *))
    (add norm 1 (by field_simp [*] at *))
    (add norm 100 (by norm_num [*] at *))
    (add norm 100 (by norm_cast at *))
    (add norm 100 (by rfl))
    (add norm 100 (by decide))
    (add norm 100 (by push_cast))
    (add norm 100 (by assumption_mod_cast))
    (add norm 0 (by grind only [Nat.mod_lt]))
    (add norm 0 (by grind only [Nat.mod_le]))
    (add norm 0 (by grind only [Pell.eq_of_xn_modEq_lem3]))
    (add norm 0 (by grind only [Pell.strictMono_x]))
    (add norm 0 (by grind only [Pell.d_pos]))
    (add norm 0 (by grind only [PNat.XgcdType.r]))
    (add norm 0 (by grind only [Nat.le_of_mod_lt]))
    (add norm 0 (by grind only [Nat.succ_le_of_lt]))
    (add norm 100 (by rw [← Nat.add_div]))
    (add norm 0 (by grind only [Num.cast_le]))
    (add norm 0 (by grind only [Num.mod_to_nat]))
    (add norm 0 (by grind only [Nat.mod_add_div]))
    (add norm 0 (by grind only [Num.le_to_nat]))
    (add norm 0 (by grind only [Nat.zero_le]))
    (add norm 0 (by grind only [Pell.yn_ge_n]))
    (add norm 0 (by grind only [MulAction.le_period]))
    (add norm 0 (by grind only [Nat.add_mod_add_ite]))
    (add norm 0 (by simp_all [Nat.le_div_iff_mul_le]))
    (add norm 0 (by grind only [Nat.mod_injOn_Ico]))
    (add norm 0 (by grind only [Pell.xn]))
    (add norm 0 (by grind only [Nat.succ_le_iff]))
    (add norm 0 (by grind only [Nat.mul_div_lt_iff_not_dvd]))
    (add norm 0 (by grind only [Nat.one_le_of_lt]))
    (add norm 0 (by grind only [Nat.pos_of_ne_zero]))
    (add norm 0 (by grind only [Pell.eq_of_xn_modEq_lem1]))
    (add safe 1 (by rw [Pell.x_pos]))
    (add safe 0 (by grind only [Nat.mul_le_mul_left]))
    (add safe 1 (by rw [Ordnode.Sized.pos]))
    (add safe 1 (by rw [Nat.div_pos]))
    (add safe 0 (by grind only [Nat.le_mul_of_pos_left]))
    (add safe 0 (by grind only [Ordnode.Valid'.rotateL_lemma₂]))
    (add safe 0 (by grind only [Ordnode.Valid'.rotateL_lemma₄]))