import Mathlib

theorem mathd_algebra_24 (x : ℝ) (h₀ : x / 50 = 40) : x = 2000 := by

  aesop (config := {
    maxRuleApplications := 1600
    maxRuleApplicationDepth := 20
    maxNormIterations := 1200
    maxGoals := 32
    enableUnfold := false
  }) (rule_sets := [-builtin])
    (add norm 100 (by ring))
    (add norm 100 (by norm_num))
    (add norm 0 (by linarith))
    (add norm 0 (by nlinarith))
    (add norm 0 (by omega))
    (add norm 100 (by zify))
    (add norm 0 (by bound))
    (add norm 100 (by interval_cases))
    (add norm 0 (by ext))
    (add norm 100 (by split))
    (add norm 0 (by simp))
    (add norm 100 (by field_simp [*] at *))
    (add norm 100 (by norm_cast at *))
    (add norm 100 (by rfl))
    (add norm 0 (by decide))
    (add norm 100 (by assumption_mod_cast))
    (add safe 1 (by norm_cast))
    (add safe 0 (by ring_nf))
    (add safe 0 (by exfalso))
    (add unsafe 90% (by abel))
    (add unsafe 90% (by simp_all))
    (add unsafe 90% (by ring_nf at *))
    (add unsafe 90% (by push_cast))
    (add norm 100 (by apply div_mul_cancel₀))
    (add norm 100 (by apply mul_div_cancel₀))
    (add norm 100 (by apply div_self))
    (add norm 1 (by rw [← eq_div_iff_mul_eq]))
    (add norm 1 (by rw [← div_eq_iff_mul_eq]))
    (add norm 100 (by apply div_eq_one_iff_eq))
    (add norm 100 (by apply div_ne_zero))
    (add norm 100 (by apply div_left_inj'))
    (add norm 100 (by apply mul_div_mul_left))
    (add norm 100 (by apply div_pow))
    (add norm 100 (by apply mul_div_mul_right))
    (add norm 100 (by apply div_sub_div))
    (add norm 100 (by apply mul_ne_zero))
    (add norm 1 (by linarith [Real.log_div]))
    (add norm 100 (by apply sub_div))
    (add norm 100 (by apply div_sub'))
    (add norm 100 (by apply div_eq_div_iff))
    (add safe 0 (by rw [← div_eq_iff]))
    (add safe 0 (by rw [← mul_div_cancel_right₀]))
    (add safe 0 (by rw [← mul_div_cancel_left₀]))
    (add safe 100 (by rw [two_ne_zero'] at *))
    (add safe 0 (by simp_all [two_ne_zero]))
    (add safe 0 (by rw [← EuclideanDomain.eq_div_of_mul_eq_left]))
    (add safe 0 (by simp_rw [Complex.log_ofReal_mul]))
    (add unsafe 90% (by simp_all only [eq_div_iff]))
    (add unsafe 10% (by linarith [Rat.num_div_den]))
    (add unsafe 10% (by linarith [mul_div_assoc]))
    (add unsafe 10% (by linarith [mul_div]))
    (add unsafe 90% (by grind only [LT.lt.ne']))
    (add unsafe 10% (by rw [← add_div] at *))
    (add unsafe 90% (by grind only [ne_of_gt]))
    (add unsafe 50% (by unfold div_ne_one))