import Mathlib

theorem mathd_algebra_419 (a b : ℝ) (h₀ : a = -1) (h₁ : b = 5) : -a - b ^ 2 + 3 * (a * b) = -39 := by

  aesop (config := {
    maxRuleApplications := 400
    maxRuleApplicationDepth := 220
    maxNormIterations := 180
    enableUnfold := false
  }) (rule_sets := [-builtin])
    (add norm 100 (by ring))
    (add norm 100 (by field_simp))
    (add norm 100 (by norm_num))
    (add norm 100 (by norm_cast))
    (add norm 0 (by linarith))
    (add norm 0 (by nlinarith))
    (add norm 0 (by omega))
    (add norm 100 (by abel))
    (add norm 100 (by zify))
    (add norm 100 (by gcongr))
    (add norm 100 (by bound))
    (add norm 100 (by interval_cases))
    (add norm 100 (by ext))
    (add norm 100 (by split))
    (add norm 100 (by exfalso))
    (add norm 100 (by ring_nf at *))
    (add norm 100 (by norm_num [*] at *))
    (add norm 100 (by norm_cast at *))
    (add norm 100 (by rfl))
    (add norm 100 (by push_cast))
    (add norm 100 (by assumption_mod_cast))
    (add safe 1 (by ring_nf))
    (add safe 0 (by simp_all))
    (add safe 0 (by field_simp [*] at *))
    (add norm 100 (by rw [← mul_pow]))
    (add norm 0 (by grind only [Quaternion.star_mul_self]))
    (add safe 0 (by rw [← mul_neg]))
    (add safe 1 (by rw [Quaternion.mul_imJ]))
    (add safe 0 (by rw [← neg_mul]))
    (add safe 1 (by rw [QuaternionAlgebra.mul_imJ]))
    (add safe 1 (by rw [Quaternion.mul_imI]))
    (add safe 1 (by rw [Quaternion.star_imI]))
    (add safe 1 (by linarith [Quaternion.mul_re]))
    (add safe 1 (by linarith [Quaternion.mul_imK]))
    (add safe 1 (by rw [Quaternion.star_imJ]))
    (add safe 1 (by rw [QuaternionAlgebra.mul_imI]))
    (add safe 1 (by rw [QuaternionAlgebra.mul_imK]))
    (add safe 1 (by rw [Quaternion.star_imK]))
    (add unsafe 10% (by push_cast [mul_neg_one] at *))
    (add unsafe 10% (by push_cast [neg_sq] at *))
    (add unsafe 10% (by push_cast [Complex.I_sq] at *))
    (add unsafe 50% (by simp_all [neg_one_mul]))
    (add unsafe 50% (by simp_all [Complex.I_mul_I]))
    (add unsafe 90% (by norm_num [Quaternion.coe_commutes] at *))
    (add unsafe 50% (by simp_all [neg_pow]))
    (add unsafe 10% (by push_cast [sq_sub_sq] at *))
    (add unsafe 50% (by simp_all [Quaternion.coe_mul_eq_smul]))
    (add unsafe 50% (by simp only [sq_add_sq_mul_sq_add_sq]))
    (add unsafe 50% (by simp only [sq_add_mul_sq_mul_sq_add_mul_sq]))
    (add unsafe 50% (by simp only [euler_four_squares]))
    (add unsafe 50% (by simp_all [Pell.Solution₁.prop]))
    (add unsafe 50% (by simp_all [Pell.Solution₁.prop_y]))
    (add unsafe 50% (by simp_all [mul_inv]))
    (add unsafe 50% (by simp_all [Quaternion.neg_imI]))
    (add unsafe 50% (by simp_all [neg_one_sq]))
    (add unsafe 50% (by simp only [Pell.Solution₁.prop_x]))