import Mathlib

theorem mathd_algebra_76 (f : ℤ → ℤ) (h₀ : ∀ n, Odd n → f n = n ^ 2)
    (h₁ : ∀ n, Even n → f n = n ^ 2 - 4 * n - 1) : f 4 = -1 := by

  aesop (config := {
    maxRuleApplications := 700
    maxRuleApplicationDepth := 120
    maxNormIterations := 320
    maxGoals := 128
    enableUnfold := false
  }) (rule_sets := [-builtin])
    (add norm 100 (by ring))
    (add norm 100 (by field_simp))
    (add norm 100 (by norm_num))
    (add norm 100 (by norm_cast))
    (add norm 100 (by abel))
    (add norm 100 (by push_neg))
    (add norm 100 (by zify))
    (add norm 100 (by bound))
    (add norm 100 (by interval_cases))
    (add norm 100 (by ext))
    (add norm 100 (by split))
    (add norm 100 (by exfalso))
    (add norm 0 (by simp_all))
    (add norm 100 (by ring_nf at *))
    (add norm 100 (by field_simp [*] at *))
    (add norm 100 (by norm_num [*] at *))
    (add norm 100 (by norm_cast at *))
    (add norm 100 (by rfl))
    (add norm 100 (by decide))
    (add norm 100 (by push_cast))
    (add norm 100 (by assumption_mod_cast))
    (add safe 0 (by omega))
    (add safe 0 (by ring_nf))
    (add unsafe 90% (by nlinarith))
    (add norm 0 (by grind only [even_iff_two_dvd]))
    (add norm 0 (by grind only [Odd]))
    (add norm 0 (by grind only [Int.natCast_inj]))
    (add norm 0 (by grind only [IsSquare]))
    (add norm 0 (by grind only [Int.odd_iff_not_even]))
    (add norm 0 (by grind only [Nat.even_or_odd]))
    (add norm 0 (by grind only [Nat.odd_iff_not_even]))
    (add norm 1 (by field_simp [irrational_sqrt_of_multiplicity_odd] at *))
    (add norm 0 (by grind only [ZMod.eq_zero_iff_even]))
    (add norm 0 (by grind only [Int.even_pow]))
    (add norm 0 (by grind only [Int.even_mul]))
    (add norm 0 (by grind only [Int.even_coe_nat]))
    (add norm 0 (by grind only [Nat.even_pow]))
    (add norm 1 (by field_simp [FiniteField.odd_card_of_char_ne_two] at *))
    (add norm 0 (by grind only [Nat.sum_four_squares_of_two_mul_sum_four_squares]))
    (add norm 100 (by rw [← Nat.odd_of_mod_four_eq_three]))
    (add norm 0 (by grind only [Int.ofNat_inj]))
    (add norm 0 (by grind only [Int.even_iff_not_odd]))
    (add norm 0 (by grind only [Int.cast_inj]))
    (add norm 0 (by grind only [jacobiSym.quadratic_reciprocity_one_mod_four]))
    (add safe 0 (by grind only [jacobiSym.at_two]))
    (add safe 0 (by simp_rw [Int.even_iff]))
    (add safe 0 (by rw [Nat.odd_iff] at *))
    (add safe 0 (by rw [Nat.even_iff] at *))
    (add safe 0 (by simp_rw [Nat.even_mul]))
    (add safe 0 (by simp_rw [jacobiSym.quadratic_reciprocity_three_mod_four]))
    (add safe 0 (by simp_rw [Int.odd_iff]))
    (add safe 0 (by rw [Nat.not_even_iff] at *))
    (add safe 0 (by simp_rw [Int.emod_two_eq_zero_or_one]))
    (add unsafe 50% (by simp_rw [Int.emod_eq_zero_of_dvd]))
    (add unsafe 50% (by simp_rw [Int.dvd_iff_emod_eq_zero]))
    (add unsafe 50% (by simp_rw [Fermat42.not_minimal]))