import Mathlib

theorem mathd_algebra_513 (a b : ℝ) (h₀ : 3 * a + 2 * b = 5) (h₁ : a + b = 2) : a = 1 ∧ b = 1 := by

  aesop (config := {
    maxRuleApplications := 100
    maxRuleApplicationDepth := 220
    maxNormIterations := 60
    maxGoals := 16
  }) (rule_sets := [-builtin])
    (add norm 100 (by ring))
    (add norm 100 (by field_simp))
    (add norm 100 (by norm_num))
    (add norm 0 (by linarith))
    (add norm 0 (by nlinarith))
    (add norm 0 (by omega))
    (add norm 100 (by abel))
    (add norm 100 (by zify))
    (add norm 0 (by bound))
    (add norm 100 (by interval_cases))
    (add norm 100 (by ext))
    (add norm 100 (by split))
    (add norm 100 (by exfalso))
    (add norm 100 (by simp))
    (add norm 100 (by ring_nf at *))
    (add norm 100 (by norm_num [*] at *))
    (add norm 100 (by norm_cast at *))
    (add norm 100 (by rfl))
    (add norm 100 (by decide))
    (add norm 100 (by push_cast))
    (add norm 100 (by assumption_mod_cast))
    (add safe 1 (by norm_cast))
    (add safe 1 (by ring_nf))
    (add safe 0 (by simp_all))
    (add safe 0 (by field_simp [*] at *))
    (add norm 0 (by grind only [Pell.eq_of_xn_modEq_lem2]))
    (add norm 0 (by grind only [two_mul]))
    (add norm 0 (by simp only [or_true] at *))
    (add norm 100 (by norm_num [and_self] at *))
    (add norm 0 (by grind only [mul_add_mul]))
    (add norm 0 (by grind only [mul_two]))
    (add norm 0 (by simp only [true_or] at *))
    (add norm 0 (by grind only [zero_lt_two]))
    (add norm 1 (by norm_num [Quaternion.star_add_self] at *))
    (add norm 0 (by simp only [and_true] at *))
    (add norm 0 (by grind only [mul_eq_one]))
    (add norm 0 (by grind only [Quaternion.self_add_star]))
    (add norm 0 (by grind only [mul_eq_one_iff]))
    (add norm 100 (by norm_num [and_true_iff] at *))
    (add norm 100 (by rw [← Nat.eq_zero_or_pos]))
    (add norm 0 (by grind only [EisensteinSeries.r]))
    (add norm 0 (by positivity [or_false]))
    (add safe 100 (by grind only [Zsqrtd.divides_sq_eq_zero_z]))
    (add safe 100 (by grind only [Zsqrtd.divides_sq_eq_zero]))
    (add safe 1 (by linarith [zero_lt_two']))
    (add unsafe 50% (by rw [← And] at *))
    (add unsafe 50% (by rw [← Or.elim] at *))
    (add unsafe 50% (by rw [← False.elim] at *))
    (add unsafe 50% (by rw [← Or] at *))
    (add unsafe 50% (by rw [← absurd] at *))
    (add unsafe 50% (by rw [← eq_or_eq_neg_of_sq_eq_sq] at *))
    (add unsafe 50% (by rw [← Polynomial.natDegree_mul_mirror] at *))
    (add unsafe 50% (by rw [← Set.not_mem_uIcc_of_lt] at *))
    (add unsafe 50% (by rw [← or_not] at *))
    (add unsafe 50% (by rw [← SimpleGraph.Walk.IsEulerian.card_filter_odd_degree] at *))
    (add unsafe 50% (by rw [← mul_lt_mul_left] at *))
    (add unsafe 50% (by rw [← Set.not_mem_uIcc_of_gt] at *))