import Mathlib

theorem mathd_numbertheory_254 : (239 + 174 + 83) % 10 = 6 := by

  aesop (config := {
    maxRuleApplications := 100
    maxRuleApplicationDepth := 10
    maxNormIterations := 520
    maxGoals := 1024
    enableUnfold := false
  })
    (add norm 100 (by ring))
    (add norm 100 (by field_simp))
    (add norm 100 (by norm_num))
    (add norm 100 (by norm_cast))
    (add norm 0 (by linarith))
    (add norm 0 (by nlinarith))
    (add norm 0 (by omega))
    (add norm 100 (by abel))
    (add norm 100 (by zify))
    (add norm 100 (by bound))
    (add norm 100 (by interval_cases))
    (add norm 100 (by ext))
    (add norm 100 (by split))
    (add norm 100 (by exfalso))
    (add norm 100 (by simp))
    (add norm 100 (by ring_nf at *))
    (add norm 1 (by field_simp [*] at *))
    (add norm 100 (by norm_num [*] at *))
    (add norm 100 (by norm_cast at *))
    (add norm 100 (by rfl))
    (add norm 100 (by decide))
    (add norm 100 (by push_cast))
    (add norm 100 (by assumption_mod_cast))
    (add norm 100 (by rw [← Nat.mul_mod_right]))
    (add norm 0 (by grind only [Nat.add_mod_left]))
    (add norm 0 (by grind only [Nat.add_mod]))
    (add safe 1 (by rw [Nat.mod_mul_left_mod]))
    (add safe 1 (by rw [Nat.mul_mod_mod]))
    (add safe 1 (by rw [Nat.mod_mul_mod]))
    (add safe 1 (by rw [Nat.add_mul_mod_self_left]))
    (add unsafe 10% (by push_cast [Nat.mod_two_add_succ_mod_two] at *))
    (add unsafe 10% (by push_cast [Nat.mul_mod] at *))
    (add unsafe 10% (by push_cast [Nat.mul_mod_left] at *))
    (add unsafe 10% (by push_cast [Nat.mod_mod] at *))
    (add unsafe 10% (by push_cast [Nat.mod_two_ne_zero] at *))
    (add unsafe 50% (by simp_rw [Nat.mul_mod_mul_left]))
    (add unsafe 50% (by simp_rw [Int.add_emod]))
    (add unsafe 10% (by push_cast [Nat.mod_two_ne_one] at *))
    (add unsafe 10% (by push_cast [Int.emod_two_ne_one] at *))
    (add unsafe 10% (by push_cast [GaussianInt.mod_four_eq_three_of_nat_prime_of_prime] at *))
    (add unsafe 50% (by simp_rw [Int.mul_emod]))
    (add unsafe 50% (by simp_rw [Int.emod_emod]))
    (add unsafe 50% (by simp_rw [Nat.pow_mod]))
    (add unsafe 10% (by push_cast [neg_one_pow_eq_pow_mod_two] at *))
    (add unsafe 10% (by push_cast [Nat.odd_iff] at *))
    (add unsafe 10% (by push_cast [Nat.mod_mod_of_dvd] at *))
    (add unsafe 10% (by push_cast [Nat.even_iff] at *))
    (add unsafe 10% (by push_cast [Nat.mod_two_of_bodd] at *))
    (add unsafe 10% (by push_cast [Int.emod_two_ne_zero] at *))
    (add unsafe 50% (by simp_rw [Nat.gcd.induction]))
    (add unsafe 50% (by simp_rw [Int.ofNat_emod]))
    (add unsafe 10% (by push_cast [Int.emod_two_eq_zero_or_one] at *))
    (add unsafe 10% (by push_cast [Int.odd_iff] at *))
    (add unsafe 50% (by simp_rw [Int.sq_ne_two_mod_four]))
    (add unsafe 50% (by simp_rw [Int.add_mul_emod_self]))