import Mathlib

theorem mathd_algebra_302 : (Complex.I / 2) ^ 2 = -(1 / 4) := by

  aesop (config := {
    maxRuleApplications := 400
    maxRuleApplicationDepth := 10
    maxNormIterations := 180
    maxGoals := 1024
  })
    (add norm 100 (by ring))
    (add norm 100 (by field_simp))
    (add norm 100 (by norm_num))
    (add norm 0 (by linarith))
    (add norm 0 (by nlinarith))
    (add norm 0 (by omega))
    (add norm 100 (by abel))
    (add norm 100 (by zify))
    (add norm 0 (by bound))
    (add norm 100 (by interval_cases))
    (add norm 1 (by ext))
    (add norm 100 (by split))
    (add norm 100 (by exfalso))
    (add norm 0 (by simp))
    (add norm 100 (by ring_nf at *))
    (add norm 100 (by field_simp [*] at *))
    (add norm 100 (by norm_num [*] at *))
    (add norm 100 (by norm_cast at *))
    (add norm 100 (by rfl))
    (add norm 0 (by decide))
    (add norm 100 (by push_cast))
    (add safe 0 (by ring_nf))
    (add safe 0 (by simp_all))
    (add safe 0 (by assumption_mod_cast))
    (add unsafe 50% (by norm_cast))
    (add norm 100 (by simp_rw [Complex.I_sq]))
    (add norm 0 (by nlinarith [Complex.two_pi_I_ne_zero]))
    (add norm 100 (by simp_rw [Complex.div_I]))
    (add norm 100 (by solve_by_elim [Complex.ofReal_div]))
    (add norm 100 (by simp_rw [Complex.I_mul_I]))
    (add norm 100 (by solve_by_elim [Complex.ofReal_mul]))
    (add norm 100 (by simp_rw [mul_neg_one]))
    (add norm 100 (by solve_by_elim [Complex.ofReal_pow]))
    (add norm 0 (by grind only [Complex.cpow_add]))
    (add norm 0 (by simp_all only [Complex.cpow_neg_one]))
    (add norm 100 (by solve_by_elim [Complex.cpow_one]))
    (add norm 100 (by solve_by_elim [Complex.cpow_neg]))
    (add norm 100 (by solve_by_elim [Complex.ofReal_add]))
    (add safe 0 (by nlinarith [Complex.I_ne_zero]))
    (add safe 0 (by nlinarith [Complex.ofReal_ofNat]))
    (add safe 0 (by nlinarith [Complex.ofReal_neg]))
    (add safe 1 (by rw [Complex.I_pow_four]))
    (add safe 0 (by nlinarith [Complex.ofReal_sin]))
    (add safe 0 (by nlinarith [Complex.ofReal_one]))
    (add safe 1 (by rw [mul_div_cancel_left₀]))
    (add safe 1 (by rw [mul_div_cancel_right₀]))
    (add safe 1 (by rw [mul_div_assoc]))
    (add safe 1 (by rw [div_eq_iff]))
    (add safe 100 (by rw [two_ne_zero'] at *))
    (add safe 0 (by nlinarith [Complex.ofReal_cos]))
    (add unsafe 50% (by simp_all [Complex.I]))
    (add unsafe 50% (by simp_all [Complex.exp_pi_mul_I]))
    (add unsafe 50% (by unfold Real.pi_ne_zero))
    (add unsafe 50% (by simp_all [Complex.sin]))
    (add unsafe 50% (by simp_all [HurwitzZeta.jacobiTheta₂'']))
    (add unsafe 10% (by simp_all only [neg_div]))
    (add unsafe 50% (by simp_all [Complex.exp_log]))