import Mathlib

theorem mathd_algebra_452 (a : ℕ → ℝ) (h₀ : ∀ n, a (n + 2) - a (n + 1) = a (n + 1) - a n)
    (h₁ : a 1 = 2 / 3) (h₂ : a 9 = 4 / 5) : a 5 = 11 / 15 := by

  aesop (config := {
    maxRuleApplications := 100
    maxRuleApplicationDepth := 10
    maxNormIterations := 60
    maxGoals := 128
    enableSimp := false
  })
    (add norm 100 (by ring))
    (add norm 100 (by field_simp))
    (add norm 100 (by norm_num))
    (add norm 100 (by norm_cast))
    (add norm 0 (by linarith))
    (add norm 0 (by nlinarith))
    (add norm 0 (by omega))
    (add norm 100 (by abel))
    (add norm 100 (by zify))
    (add norm 100 (by bound))
    (add norm 100 (by interval_cases))
    (add norm 100 (by ext))
    (add norm 100 (by split))
    (add norm 100 (by exfalso))
    (add norm 100 (by ring_nf at *))
    (add norm 100 (by field_simp [*] at *))
    (add norm 100 (by norm_num [*] at *))
    (add norm 100 (by norm_cast at *))
    (add norm 100 (by rfl))
    (add norm 100 (by decide))
    (add norm 100 (by push_cast))
    (add norm 100 (by assumption_mod_cast))
    (add safe 0 (by ring_nf))
    (add safe 0 (by simp_all))
    (add norm 0 (by grind only [one_div]))
    (add norm 100 (by apply sub_div))
    (add norm 100 (by apply div_self))
    (add norm 0 (by grind only [div_div]))
    (add norm 100 (by apply mul_one_div))
    (add norm 0 (by grind only [div_mul]))
    (add norm 0 (by grind only [div_eq_one_iff_eq]))
    (add norm 0 (by grind only [mul_div_cancel_left]))
    (add norm 0 (by grind only [div_sub']))
    (add norm 0 (by grind only [mul_div_assoc]))
    (add norm 0 (by grind only [mul_div_cancel_right]))
    (add norm 0 (by grind only [mul_div]))
    (add norm 0 (by grind only [div_one]))
    (add norm 100 (by apply div_mul_cancel₀))
    (add norm 0 (by grind only [add_div]))
    (add norm 0 (by grind only [eq_div_iff]))
    (add norm 100 (by apply Real.rpow_sub))
    (add norm 0 (by grind only [two_ne_zero']))
    (add norm 0 (by grind only [CircleDeg1Lift.transnumAuxSeq]))
    (add norm 0 (by grind only [div_eq_iff]))
    (add norm 0 (by grind only [mul_div_cancel_left₀]))
    (add norm 0 (by grind only [one_div_one]))
    (add norm 0 (by grind only [sub_div']))
    (add norm 0 (by grind only [div_lt_iff]))
    (add norm 0 (by grind only [div_right_comm]))
    (add norm 0 (by grind only [WeakFEPair.h_feq']))
    (add norm 0 (by grind only [mul_lt_mul_left]))
    (add safe 0 (by simp_all [two_ne_zero]))
    (add unsafe 50% (by apply mul_div_cancel₀))
    (add unsafe 50% (by simp_all [one_half_pos]))
    (add unsafe 50% (by simp_all [lt_div_iff]))
    (add unsafe 50% (by apply div_le_iff'))