import Mathlib

theorem mathd_numbertheory_12 :
    Finset.card (Finset.filter (fun x => 20 ∣ x) (Finset.Icc 15 85)) = 4 := by

  aesop (config := {
    maxRuleApplications := 1600
    maxRuleApplicationDepth := 20
    maxNormIterations := 520
    maxGoals := 64
    enableUnfold := false
    useDefaultSimpSet := false
  })
    (add norm 100 (by ring))
    (add norm 100 (by norm_num))
    (add norm 0 (by nlinarith))
    (add norm 0 (by positivity))
    (add norm 0 (by omega))
    (add norm 0 (by gcongr))
    (add norm 0 (by bound))
    (add norm 0 (by interval_cases))
    (add norm 0 (by ext))
    (add norm 0 (by simp))
    (add norm 0 (by ring_nf at *))
    (add norm 100 (by rfl))
    (add norm 0 (by decide))
    (add norm 100 (by push_cast))
    (add safe 1 (by zify))
    (add safe 0 (by ring_nf))
    (add safe 1 (by field_simp [*] at *))
    (add unsafe 50% (by field_simp))
    (add unsafe 50% (by norm_cast))
    (add unsafe 50% (by abel))
    (add unsafe 50% (by exfalso))
    (add unsafe 90% (by simp_all))
    (add unsafe 50% (by norm_num [*] at *))
    (add unsafe 50% (by norm_cast at *))
    (add norm 100 (by rw [Finset.card_eq_sum_card_fiberwise]))
    (add norm 100 (by rw [Finset.card_eq_sum_ones]))
    (add norm 0 (by apply Nat.card_Icc))
    (add norm 100 (by rw [Finset.filter_card_eq]))
    (add norm 0 (by apply PNat.card_Icc))
    (add norm 100 (by rw [sum_card_orderOf_eq_card_pow_eq_one]))
    (add norm 100 (by rw [Finset.filter_true_of_mem]))
    (add norm 100 (by rw [Finset.filter]))
    (add norm 0 (by apply Pi.card_Icc))
    (add norm 100 (by rw [Finset.prod_comp]))
    (add norm 100 (by rw [Fin.card_Icc]))
    (add norm 100 (by rw [Finset.card]))
    (add norm 100 (by rw [Finset.sum_card_fiberwise_eq_card_filter]))
    (add norm 100 (by rw [Finset.cast_card]))
    (add norm 100 (by rw [Nat.card_multiples']))
    (add norm 100 (by rw [Finset.filter_or]))
    (add norm 0 (by apply Int.card_Icc))
    (add norm 100 (by rw [Finset.filter_congr]))
    (add norm 1 (by simp_all [NumberField.InfinitePlace.card_filter_mk_eq]))
    (add norm 100 (by rw [Finset.filter_filter]))
    (add norm 1 (by simp_all [Finset.prod_ite]))
    (add norm 100 (by rw [Finset.sum_const_nat]))
    (add norm 100 (by rw [Finset.mulEnergy_eq_sum_sq']))
    (add norm 1 (by simp_all [Nat.card_Ico]))
    (add norm 1 (by simp_all [SimpleGraph.dart_edge_fiber_card]))
    (add norm 100 (by rw [Finset.slice]))
    (add norm 1 (by simp_all [Fintype.card_subtype]))
    (add norm 100 (by rw [Finset.filter_card_add_filter_neg_card_eq_card]))
    (add safe 1 (by apply Nat.Prime.multiplicity_choose_aux))
    (add safe 1 (by simp only [Finset.filter_eq']))
    (add unsafe 10% (by simp_all only [card_orderOf_eq_totient_aux₂]))
    (add unsafe 50% (by simp_rw [Finset.filter_ne']))