import Mathlib

theorem mathd_algebra_129 (a : ℝ) (h₀ : a ≠ 0) (h₁ : 8⁻¹ / 4⁻¹ - a⁻¹ = 1) : a = -2 := by

  aesop (config := {
    maxRuleApplications := 1600
    maxRuleApplicationDepth := 10
    maxNormIterations := 1200
    maxGoals := 32
    enableUnfold := false
  }) (rule_sets := [-builtin])
    (add norm 100 (by ring))
    (add norm 100 (by field_simp))
    (add norm 100 (by norm_num))
    (add norm 100 (by norm_cast))
    (add norm 0 (by linarith))
    (add norm 0 (by nlinarith))
    (add norm 0 (by omega))
    (add norm 100 (by abel))
    (add norm 100 (by push_neg))
    (add norm 100 (by zify))
    (add norm 100 (by bound))
    (add norm 100 (by interval_cases))
    (add norm 100 (by ext))
    (add norm 100 (by split))
    (add norm 100 (by exfalso))
    (add norm 100 (by ring_nf at *))
    (add norm 100 (by field_simp [*] at *))
    (add norm 100 (by norm_num [*] at *))
    (add norm 100 (by norm_cast at *))
    (add norm 100 (by rfl))
    (add norm 100 (by decide))
    (add norm 100 (by push_cast))
    (add norm 100 (by assumption_mod_cast))
    (add safe 0 (by ring_nf))
    (add safe 0 (by simp_all))
    (add norm 0 (by grind only [div_eq_one]))
    (add norm 0 (by grind only [div_ne_one]))
    (add norm 0 (by grind only [div_ne_one_of_ne]))
    (add norm 0 (by grind only [inv_eq_one]))
    (add norm 0 (by grind only [inv_eq_iff_eq_inv]))
    (add norm 0 (by grind only [inv_ne_one]))
    (add norm 0 (by grind only [quadratic_eq_zero_iff]))
    (add norm 0 (by grind only [WeierstrassCurve.Affine.slope_of_X_ne]))
    (add norm 0 (by grind only [Quaternion.star_eq_neg]))
    (add norm 100 (by apply div_ne_zero))
    (add norm 0 (by grind only [irrational_iff_ne_rational]))
    (add norm 0 (by grind only [eq_neg_self_iff]))
    (add norm 0 (by grind only [div_eq_iff]))
    (add norm 0 (by grind only [div_eq_one_iff_eq]))
    (add norm 0 (by grind only [inv_ne_zero]))
    (add norm 0 (by grind only [div_eq_zero_iff]))
    (add norm 0 (by grind only [neg_div]))
    (add norm 0 (by grind only [sq_eq_zero_iff]))
    (add norm 0 (by grind only [Quaternion.star_eq_self]))
    (add norm 0 (by grind only [eq_inv_iff_mul_eq_one]))
    (add norm 0 (by grind only [norm_div_eq_zero_iff]))
    (add norm 0 (by grind only [mul_eq_one_iff_eq_inv]))
    (add norm 0 (by grind only [WeierstrassCurve.Affine.slope]))
    (add norm 0 (by grind only [geom_sum_inv]))
    (add norm 0 (by grind only [mul_self_eq_one_iff]))
    (add norm 0 (by grind only [mul_eq_left₀]))
    (add norm 1 (by solve_by_elim [Real.sin_eq_zero_iff]))
    (add norm 0 (by grind only [WeierstrassCurve.Affine.Y_eq_of_Y_ne]))
    (add norm 0 (by grind only [mul_left_inj']))
    (add norm 0 (by grind only [div_eq_iff_mul_eq]))
    (add norm 0 (by grind only [neg_eq]))
    (add norm 0 (by grind only [Real.pi_ne_zero]))