import Mathlib

theorem mathd_algebra_270 (f : ℝ → ℝ) (h₀ : ∀ (x) (_ : x ≠ -2), f x = 1 / (x + 2)) :
    f (f 1) = 3 / 7 := by

  aesop (config := {
    maxRuleApplications := 1600
    maxRuleApplicationDepth := 10
    maxNormIterations := 30
    maxGoals := 16
  }) (rule_sets := [-builtin])
    (add norm 100 (by ring))
    (add norm 100 (by field_simp))
    (add norm 100 (by norm_num))
    (add norm 100 (by norm_cast))
    (add norm 0 (by linarith))
    (add norm 0 (by nlinarith))
    (add norm 0 (by omega))
    (add norm 100 (by abel))
    (add norm 100 (by push_neg))
    (add norm 100 (by zify))
    (add norm 100 (by bound))
    (add norm 100 (by interval_cases))
    (add norm 100 (by ext))
    (add norm 100 (by split))
    (add norm 100 (by exfalso))
    (add norm 100 (by ring_nf at *))
    (add norm 100 (by field_simp [*] at *))
    (add norm 100 (by norm_num [*] at *))
    (add norm 100 (by norm_cast at *))
    (add norm 100 (by rfl))
    (add norm 100 (by decide))
    (add norm 100 (by push_cast))
    (add norm 100 (by assumption_mod_cast))
    (add safe 1 (by ring_nf))
    (add safe 0 (by simp_all))
    (add norm 0 (by grind only [one_div]))
    (add norm 0 (by grind only [neg_div]))
    (add norm 100 (by apply div_self))
    (add norm 0 (by grind only [div_eq_mul_inv]))
    (add norm 0 (by grind only [inv_div]))
    (add norm 100 (by apply sub_div))
    (add norm 0 (by grind only [div_neg]))
    (add norm 0 (by grind only [two_ne_zero']))
    (add norm 0 (by grind only [div_one]))
    (add norm 0 (by grind only [div_inv_eq_mul]))
    (add norm 0 (by grind only [mul_inv]))
    (add norm 0 (by grind only [Complex.ofReal_inv]))
    (add norm 0 (by grind only [eq_div_iff]))
    (add norm 0 (by grind only [div_div]))
    (add norm 0 (by grind only [one_ne_zero]))
    (add norm 0 (by grind only [mul_div_assoc]))
    (add norm 0 (by grind only [Complex.Gammaℝ]))
    (add norm 0 (by grind only [LSeries.term_of_ne_zero]))
    (add norm 0 (by grind only [div_eq_iff]))
    (add norm 100 (by rw [mul_one_div]))
    (add norm 0 (by grind only [neg_eq]))
    (add norm 0 (by grind only [sub_half]))
    (add norm 0 (by grind only [HurwitzZeta.hurwitzZetaEven]))
    (add norm 0 (by grind only [div_eq_one_iff_eq]))
    (add norm 0 (by grind only [mul_div_cancel_left]))
    (add norm 0 (by grind only [div_self']))
    (add norm 0 (by grind only [harmonic_succ]))
    (add norm 0 (by grind only [Real.arctan]))
    (add norm 0 (by grind only [div_ne_one]))
    (add norm 0 (by grind only [Complex.arctan]))
    (add unsafe 10% (by linarith [div_eq_inv_mul]))
    (add unsafe 90% (by norm_num [two_ne_zero] at *))