import Mathlib

theorem mathd_numbertheory_1124 (n : ℕ) (h₀ : n ≤ 9) (h₁ : 18 ∣ 374 * 10 + n) : n = 4 := by

  aesop (config := {
    maxRuleApplicationDepth := 220
    maxNormIterations := 60
    maxGoals := 1024
  })
    (add norm 100 (by ring))
    (add norm 100 (by field_simp))
    (add norm 100 (by norm_num))
    (add norm 0 (by linarith))
    (add norm 0 (by nlinarith))
    (add norm 0 (by omega))
    (add norm 100 (by abel))
    (add norm 100 (by zify))
    (add norm 0 (by bound))
    (add norm 100 (by interval_cases))
    (add norm 100 (by exfalso))
    (add norm 100 (by simp))
    (add norm 0 (by ring_nf at *))
    (add norm 100 (by norm_num [*] at *))
    (add norm 100 (by norm_cast at *))
    (add norm 100 (by push_cast))
    (add norm 100 (by assumption_mod_cast))
    (add safe 1 (by norm_cast))
    (add safe 1 (by ring_nf))
    (add safe 0 (by split))
    (add unsafe 90% (by ext))
    (add unsafe 90% (by simp_all))
    (add unsafe 50% (by field_simp [*] at *))
    (add unsafe 50% (by rfl))
    (add norm 1 (by simp only [Nat.succ_le_of_lt]))
    (add norm 1 (by norm_num [Nat.Prime.one_lt] at *))
    (add norm 0 (by simp_all [Nat.one_le_of_lt]))
    (add norm 1 (by rw [Zsqrtd.d_pos]))
    (add norm 1 (by norm_num [Nat.Prime.two_le] at *))
    (add norm 1 (by norm_num [le_self_pow] at *))
    (add norm 1 (by simp only [Nat.exists_eq_succ_of_ne_zero]))
    (add norm 100 (by rw [← Nat.not_eq_zero_of_lt]))
    (add safe 0 (by simp_all [Nat.le_of_dvd]))
    (add safe 0 (by simp_all [Nat.pos_of_ne_zero]))
    (add safe 0 (by simp_all [Nat.dvd_two_of_totient_le_one]))
    (add safe 0 (by simp_all [pos_of_gt]))
    (add safe 100 (by simp_all [Pell.x_pos]))
    (add safe 0 (by simp_all [Nat.mod_lt]))
    (add safe 0 (by simp_all [Nat.pos_of_dvd_of_pos]))
    (add safe 100 (by simp_all [Nat.mul_div_lt_iff_not_dvd]))
    (add safe 0 (by simp_all [Nat.not_dvd_of_pos_of_lt]))
    (add safe 0 (by simp_all [Pell.eq_of_xn_modEq_lem2]))
    (add safe 0 (by simp_all [Pell.eq_of_xn_modEq_lem3]))
    (add safe 0 (by simp_all [ascPochhammer_pos]))
    (add safe 0 (by simp_all [Nat.dvd_factorial]))
    (add safe 0 (by simp_all [LucasLehmer.two_lt_q]))
    (add safe 100 (by simp_all [IsPrimePow.one_lt]))
    (add safe 0 (by simp_all [Nat.eq_zero_of_dvd_of_lt]))
    (add safe 0 (by simp_all [Pell.yn_ge_n]))
    (add safe 100 (by simp_all [Nat.not_dvd_of_between_consec_multiples]))
    (add safe 100 (by simp_all [Pell.eq_pow_of_pell_lem]))
    (add unsafe 90% (by grind only [lt_of_le_of_ne]))
    (add unsafe 50% (by push_cast [le_of_mul_le_mul_right] at *))
    (add unsafe 90% (by grind only [Nat.factorization_le_iff_dvd]))
    (add unsafe 90% (by grind only [Nat.totient_pos]))
    (add unsafe 50% (by push_cast [mul_le_iff_le_one_left] at *))