import Mathlib

theorem mathd_algebra_440 (x : ℝ) (h₀ : 3 / 2 / 3 = x / 10) : x = 5 := by

  aesop (config := {
    maxRuleApplications := 1600
    maxRuleApplicationDepth := 10
    maxNormIterations := 1200
    maxGoals := 1024
    enableUnfold := false
  }) (rule_sets := [-builtin])
    (add norm 100 (by ring))
    (add norm 100 (by field_simp))
    (add norm 100 (by norm_num))
    (add norm 0 (by linarith))
    (add norm 0 (by nlinarith))
    (add norm 0 (by omega))
    (add norm 100 (by abel))
    (add norm 0 (by bound))
    (add norm 100 (by interval_cases))
    (add norm 100 (by ext))
    (add norm 100 (by split))
    (add norm 100 (by exfalso))
    (add norm 100 (by ring_nf at *))
    (add norm 100 (by field_simp [*] at *))
    (add norm 100 (by norm_num [*] at *))
    (add norm 100 (by norm_cast at *))
    (add norm 100 (by rfl))
    (add norm 100 (by decide))
    (add norm 100 (by push_cast))
    (add norm 100 (by assumption_mod_cast))
    (add safe 1 (by norm_cast))
    (add safe 1 (by zify))
    (add safe 0 (by ring_nf))
    (add safe 0 (by simp_all))
    (add norm 100 (by apply div_self))
    (add norm 100 (by apply sub_div))
    (add norm 100 (by apply div_mul_cancel₀))
    (add norm 100 (by apply div_eq_one_iff_eq))
    (add norm 100 (by apply mul_div_cancel₀))
    (add norm 1 (by rw [← eq_div_iff_mul_eq]))
    (add norm 0 (by grind only [div_eq_iff_mul_eq]))
    (add norm 100 (by apply mul_one_div))
    (add norm 0 (by grind only [one_div]))
    (add norm 100 (by apply div_ne_zero))
    (add norm 100 (by rw [Rat.num_div_den]))
    (add norm 1 (by linarith [Real.log_div]))
    (add norm 0 (by grind only [div_left_inj']))
    (add norm 100 (by rw [CircleDeg1Lift.transnumAuxSeq]))
    (add safe 0 (by rw [← eq_div_iff]))
    (add safe 0 (by rw [← div_eq_iff]))
    (add safe 0 (by rw [← mul_div_cancel_left₀]))
    (add safe 100 (by rw [two_ne_zero'] at *))
    (add safe 0 (by rw [← mul_div_cancel_right₀]))
    (add safe 0 (by rw [← mul_div_mul_left]))
    (add safe 0 (by simp_all [two_ne_zero]))
    (add safe 0 (by rw [← neg_div]))
    (add safe 0 (by grind only [Quaternion.coe_div]))
    (add safe 0 (by rw [← mul_div_mul_right]))
    (add unsafe 10% (by linarith [mul_div_assoc]))
    (add unsafe 10% (by linarith [div_div]))
    (add unsafe 10% (by linarith [mul_div]))
    (add unsafe 10% (by rw [← add_div] at *))
    (add unsafe 50% (by simp_rw [Complex.ofReal_div]))
    (add unsafe 10% (by linarith [div_right_comm]))
    (add unsafe 90% (by rw [div_sub'] at *))
    (add unsafe 50% (by simp_rw [HurwitzZeta.completedHurwitzZetaEven_eq]))