import Mathlib

theorem mathd_numbertheory_233 (b : ZMod (11 ^ 2)) (h₀ : b = 24⁻¹) : b = 116 := by

  aesop (config := {
    maxRuleApplications := 2400
    maxRuleApplicationDepth := 10
    maxNormIterations := 30
    maxGoals := 32
  }) (rule_sets := [-builtin])
    (add norm 100 (by ring))
    (add norm 100 (by field_simp))
    (add norm 100 (by norm_num))
    (add norm 100 (by norm_cast))
    (add norm 100 (by linarith))
    (add norm 0 (by nlinarith))
    (add norm 0 (by omega))
    (add norm 100 (by abel))
    (add norm 1 (by bound))
    (add norm 100 (by interval_cases))
    (add norm 1 (by ext))
    (add norm 100 (by split))
    (add norm 100 (by exfalso))
    (add norm 100 (by ring_nf at *))
    (add norm 100 (by field_simp [*] at *))
    (add norm 100 (by norm_cast at *))
    (add norm 100 (by rfl))
    (add norm 100 (by decide))
    (add norm 100 (by push_cast))
    (add norm 100 (by assumption_mod_cast))
    (add safe 1 (by zify))
    (add safe 0 (by ring_nf))
    (add safe 0 (by simp_all))
    (add norm 0 (by grind only [Nat.prime_two]))
    (add norm 1 (by solve_by_elim [ZMod.sq_add_sq]))
    (add norm 100 (by push_cast [mul_left_cancel₀] at *))
    (add norm 0 (by grind only [zero_lt_two]))
    (add norm 0 (by grind only [ZMod.natCast_zmod_eq_zero_iff_dvd]))
    (add norm 0 (by grind only [ZMod.eq_zero_iff_even]))
    (add norm 1 (by norm_num [Polynomial.natTrailingDegree_mul_mirror] at *))
    (add norm 0 (by grind only [eq_or_eq_neg_of_sq_eq_sq]))
    (add norm 0 (by grind only [LucasLehmer.two_lt_q]))
    (add norm 1 (by solve_by_elim [legendreSym.eq_pow]))
    (add norm 0 (by grind only [quadraticChar_eq_one_of_char_two]))
    (add norm 1 (by solve_by_elim [Nat.sum_four_squares_of_two_mul_sum_four_squares]))
    (add norm 100 (by rw [Polynomial.natDegree_mul_mirror]))
    (add norm 100 (by push_cast [mul_right_inj'] at *))
    (add norm 0 (by grind only [MulChar.IsQuadratic]))
    (add norm 0 (by grind only [sq_eq_one_iff]))
    (add safe 0 (by field_simp [Char.card_pow_char_pow] at *))
    (add safe 0 (by field_simp [GaussianInt.sq_add_sq_of_nat_prime_of_not_irreducible] at *))
    (add safe 0 (by field_simp [ZMod] at *))
    (add safe 0 (by field_simp [FiniteField.two_pow_card] at *))
    (add safe 0 (by simp_all [two_ne_zero]))
    (add safe 1 (by simp only [sq_ne_two_fin_zmod_four]))
    (add unsafe 10% (by nlinarith [legendreSym.quadratic_reciprocity']))
    (add unsafe 10% (by nlinarith [Nat.eq_sq_add_sq_of_isSquare_mod_neg_one]))
    (add unsafe 10% (by positivity [gaussSum_sq]))
    (add unsafe 10% (by field_simp [CharP.cast_eq_zero_iff] at *))
    (add unsafe 10% (by nlinarith [FiniteField.odd_card_of_char_ne_two]))
    (add unsafe 10% (by nlinarith [ZMod.neg_one_ne_one]))
    (add unsafe 10% (by nlinarith [quadraticChar_neg_one]))
    (add unsafe 10% (by nlinarith [quadraticChar_eq_pow_of_char_ne_two']))
    (add unsafe 10% (by nlinarith [ZMod.isSquare_neg_one_of_eq_sq_add_sq_of_coprime]))
    (add unsafe 10% (by nlinarith [Int.isUnit_sq]))