import Mathlib

theorem mathd_algebra_171 (f : ℝ → ℝ) (h₀ : ∀ x, f x = 5 * x + 4) : f 1 = 9 := by

  aesop (config := {
    maxRuleApplications := 1100
    maxRuleApplicationDepth := 220
    maxNormIterations := 520
    maxGoals := 32
  }) (rule_sets := [-builtin])
    (add norm 100 (by ring))
    (add norm 100 (by field_simp))
    (add norm 100 (by norm_num))
    (add norm 0 (by linarith))
    (add norm 0 (by nlinarith))
    (add norm 0 (by omega))
    (add norm 100 (by abel))
    (add norm 100 (by zify))
    (add norm 0 (by bound))
    (add norm 100 (by interval_cases))
    (add norm 100 (by ext))
    (add norm 100 (by split))
    (add norm 100 (by exfalso))
    (add norm 100 (by ring_nf at *))
    (add norm 100 (by norm_cast at *))
    (add norm 100 (by rfl))
    (add norm 100 (by decide))
    (add norm 100 (by push_cast))
    (add norm 100 (by assumption_mod_cast))
    (add safe 1 (by norm_cast))
    (add safe 1 (by ring_nf))
    (add safe 0 (by simp_all))
    (add unsafe 50% (by field_simp [*] at *))
    (add norm 100 (by simp only [mul_one] at *))
    (add norm 100 (by simp only [one_mul] at *))
    (add norm 0 (by solve_by_elim [div_one]))
    (add norm 1 (by simp_all [ProbabilityTheory.mgf]))
    (add norm 100 (by simp_all only [integral_one]))
    (add norm 1 (by simp_all [MeasureTheory.hausdorffMeasure_real]))
    (add norm 100 (by simp_all only [Real.one_rpow]))
    (add norm 100 (by rw [Real.log_one]))
    (add norm 100 (by rw [Real.Gamma_one]))
    (add norm 0 (by grind only [sq_eq_one_iff]))
    (add norm 0 (by grind only [IsLprojection.coe_compl]))
    (add norm 1 (by simp_all [ProbabilityTheory.mgf_zero']))
    (add norm 0 (by grind only [mul_eq_one]))
    (add norm 0 (by grind only [mabs_one]))
    (add norm 0 (by grind only [mul_eq_one_iff']))
    (add norm 1 (by simp_all [ProbabilityTheory.mgf_zero]))
    (add norm 1 (by simp_all [ENNReal.ofReal_one]))
    (add norm 0 (by grind only [ENNReal.log_one]))
    (add safe 1 (by simp only [Real.exp_zero]))
    (add safe 1 (by simp only [Pi.one_apply]))
    (add safe 0 (by simp only [one_ne_zero]))
    (add safe 1 (by simp only [Real.exp_eq_one_iff]))
    (add safe 0 (by simp only [ContinuousMap.one_apply]))
    (add safe 1 (by simp only [Real.exp_eq_exp]))
    (add safe 1 (by simp only [ENNReal.one_toReal]))
    (add safe 1 (by simp only [ContinuousMap.coe_one]))
    (add safe 1 (by simp only [MeasureTheory.lintegral_one]))
    (add safe 1 (by simp only [NNReal.coe_one]))
    (add unsafe 10% (by rw [← abs_one] at *))
    (add unsafe 90% (by solve_by_elim [Real.rpow_zero]))
    (add unsafe 90% (by solve_by_elim [TrivSqZeroExt.inl_one]))
    (add unsafe 90% (by solve_by_elim [LSeries.term_delta]))