import Mathlib

theorem mathd_numbertheory_430 (a b c : ℕ) (h₀ : 1 ≤ a ∧ a ≤ 9) (h₁ : 1 ≤ b ∧ b ≤ 9)
    (h₂ : 1 ≤ c ∧ c ≤ 9) (h₃ : a ≠ b) (h₄ : a ≠ c) (h₅ : b ≠ c) (h₆ : a + b = c)
    (h₇ : 10 * a + a - b = 2 * c) (h₈ : c * b = 10 * a + a + a) : a + b + c = 8 := by

  aesop (config := {
    maxRuleApplications := 100
    maxRuleApplicationDepth := 220
    maxNormIterations := 60
    maxGoals := 16
    enableSimp := false
  })
    (add norm 100 (by ring))
    (add norm 100 (by field_simp))
    (add norm 100 (by norm_num))
    (add norm 0 (by linarith))
    (add norm 0 (by nlinarith))
    (add norm 0 (by omega))
    (add norm 100 (by abel))
    (add norm 100 (by zify))
    (add norm 100 (by bound))
    (add norm 100 (by interval_cases))
    (add norm 100 (by ext))
    (add norm 100 (by split))
    (add norm 100 (by exfalso))
    (add norm 100 (by simp))
    (add norm 100 (by ring_nf at *))
    (add norm 1 (by field_simp [*] at *))
    (add norm 100 (by norm_num [*] at *))
    (add norm 100 (by norm_cast at *))
    (add norm 100 (by rfl))
    (add norm 100 (by decide))
    (add norm 100 (by push_cast))
    (add norm 100 (by assumption_mod_cast))
    (add safe 1 (by norm_cast))
    (add safe 1 (by ring_nf))
    (add unsafe 90% (by simp_all))
    (add norm 0 (by grind only [Nat.add_sub_of_le]))
    (add norm 100 (by simp only [mul_comm] at *))
    (add norm 0 (by grind only [add_tsub_cancel_of_le]))
    (add norm 0 (by grind only [tsub_add_cancel_of_le]))
    (add norm 1 (by norm_num [two_mul] at *))
    (add norm 1 (by norm_num [Pell.eq_of_xn_modEq_lem2] at *))
    (add norm 1 (by simp_all [Eq.symm]))
    (add norm 100 (by simp only [mul_left_comm] at *))
    (add norm 0 (by grind only [Nat.add_sub_cancel']))
    (add norm 0 (by grind only [Nat.add_sub_assoc]))
    (add norm 0 (by grind only [add_tsub_assoc_of_le]))
    (add norm 0 (by grind only [tsub_add_eq_add_tsub]))
    (add norm 0 (by grind only [add_tsub_cancel_left]))
    (add norm 1 (by norm_num [mul_two] at *))
    (add norm 100 (by simp only [mul_assoc] at *))
    (add norm 0 (by grind only [Nat.sub_add_cancel]))
    (add norm 0 (by grind only [tsub_add_tsub_cancel]))
    (add norm 100 (by simp only [mul_right_comm] at *))
    (add norm 0 (by grind only [add_tsub_cancel_right]))
    (add norm 100 (by rw [← ack_two]))
    (add norm 0 (by grind only [Nat.div_add_mod]))
    (add norm 1 (by simp_all [Eq.trans]))
    (add norm 0 (by grind only [Nat.add_sub_cancel]))
    (add norm 1 (by norm_num [Polynomial.natDegree_mul_mirror] at *))
    (add norm 0 (by grind only [sub_eq_add]))
    (add norm 0 (by grind only [Nat.add_sub_cancel_left]))
    (add safe 100 (by simp_all [Finset.mulETransformRight.card]))
    (add safe 0 (by norm_num [mul_add_mul] at *))
    (add safe 100 (by simp_all [Sym2.two_mul_card_image_offDiag]))