import Mathlib

theorem mathd_algebra_208 : Real.sqrt 1000000 - 1000000 ^ ((1 : ℝ) / 3) = 900 := by

  aesop (config := {
    maxNormIterations := 30
    maxGoals := 32
    enableUnfold := false
  })
    (add norm 100 (by ring))
    (add norm 100 (by field_simp))
    (add norm 100 (by norm_num))
    (add norm 0 (by linarith))
    (add norm 0 (by nlinarith))
    (add norm 0 (by omega))
    (add norm 100 (by abel))
    (add norm 100 (by zify))
    (add norm 0 (by gcongr))
    (add norm 0 (by bound))
    (add norm 0 (by interval_cases))
    (add norm 0 (by ext))
    (add norm 100 (by exfalso))
    (add norm 0 (by simp))
    (add norm 0 (by ring_nf at *))
    (add norm 100 (by field_simp [*] at *))
    (add norm 100 (by norm_num [*] at *))
    (add norm 100 (by norm_cast at *))
    (add norm 100 (by rfl))
    (add norm 0 (by decide))
    (add norm 100 (by push_cast))
    (add norm 100 (by assumption_mod_cast))
    (add safe 0 (by split))
    (add unsafe 50% (by norm_cast))
    (add unsafe 10% (by ring_nf))
    (add unsafe 90% (by simp_all))
    (add norm 1 (by simp_all [Real.sqrt_one]))
    (add norm 0 (by grind only [Real.sqrt_sq]))
    (add norm 0 (by grind only [Real.sqrt_div]))
    (add norm 0 (by grind only [Real.mul_self_sqrt]))
    (add norm 0 (by grind only [Real.sqrt_mul_self]))
    (add norm 0 (by grind only [integral_gaussian]))
    (add norm 100 (by rw [Real.cos_pi_over_two_pow] at *))
    (add norm 100 (by rw [Real.cos_half] at *))
    (add norm 0 (by grind only [Real.sqrt_mul]))
    (add norm 1 (by simp_all [Real.log_div]))
    (add norm 0 (by grind only [Real.sqrt_mul']))
    (add norm 1 (by simp_all [zero_lt_two]))
    (add norm 100 (by rw [Real.sin_sq_pi_over_two_pow_succ] at *))
    (add norm 0 (by grind only [Real.exp_half]))
    (add norm 0 (by grind only [Real.sqrt_nonneg]))
    (add norm 100 (by rw [Real.cos_arctan] at *))
    (add norm 0 (by grind only [Real.sqrt]))
    (add norm 0 (by grind only [Real.sqrt_zero]))
    (add norm 100 (by rw [Real.sin_pi_over_two_pow_succ] at *))
    (add safe 1 (by rw [Real.sqrt_eq_rpow]))
    (add safe 0 (by push_cast [Real.sq_sqrt] at *))
    (add safe 1 (by rw [Real.sqrt_inv]))
    (add safe 1 (by rw [← Real.hasDerivAt_sqrt]))
    (add safe 1 (by rw [Real.rpow_div_two_eq_sqrt]))
    (add safe 0 (by simp_all [two_ne_zero]))
    (add safe 1 (by grind only [Real.inv_sqrt_one_add_tan_sq]))
    (add unsafe 50% (by field_simp [Real.sqrt_pos] at *))
    (add unsafe 50% (by field_simp [Real.div_sqrt] at *))
    (add unsafe 50% (by simp_rw [Stirling.stirlingSeq]))
    (add unsafe 50% (by field_simp [Real.deriv_arccos] at *))
    (add unsafe 50% (by simp_rw [Real.Gamma_pos_of_pos]))
    (add unsafe 50% (by simp_rw [Real.doublingGamma]))