import Mathlib

theorem mathd_numbertheory_321 (n : ZMod 1399) (h₁ : n = 160⁻¹) : n = 1058 := by

  aesop (config := {
    maxRuleApplicationDepth := 10
    maxNormIterations := 320
    maxGoals := 32
    enableUnfold := false
  }) (rule_sets := [-builtin])
    (add norm 100 (by ring))
    (add norm 100 (by field_simp))
    (add norm 100 (by norm_num))
    (add norm 0 (by linarith))
    (add norm 0 (by nlinarith))
    (add norm 0 (by omega))
    (add norm 100 (by abel))
    (add norm 100 (by zify))
    (add norm 0 (by gcongr))
    (add norm 0 (by bound))
    (add norm 0 (by interval_cases))
    (add norm 0 (by ext))
    (add norm 100 (by split))
    (add norm 100 (by exfalso))
    (add norm 0 (by simp))
    (add norm 0 (by ring_nf at *))
    (add norm 100 (by field_simp [*] at *))
    (add norm 100 (by norm_cast at *))
    (add norm 100 (by rfl))
    (add norm 0 (by decide))
    (add norm 100 (by push_cast))
    (add norm 100 (by assumption_mod_cast))
    (add safe 0 (by ring_nf))
    (add unsafe 50% (by norm_cast))
    (add unsafe 90% (by simp_all))
    (add norm 0 (by grind only [DualNumber.inv_eps]))
    (add norm 0 (by grind only [Int.ofNat_zero]))
    (add norm 100 (by linarith [ZMod]))
    (add unsafe 50% (by simp_rw [inv_one]))
    (add unsafe 50% (by simp_rw [Hyperreal.st_inv]))
    (add unsafe 50% (by simp_rw [TrivSqZeroExt.inv_one]))
    (add unsafe 10% (by nlinarith [inv_gold]))
    (add unsafe 50% (by simp_rw [TrivSqZeroExt.fst_inv]))
    (add unsafe 50% (by simp_rw [GroupWithZero]))
    (add unsafe 50% (by simp_rw [one_eq_inv]))
    (add unsafe 50% (by simp_rw [TrivSqZeroExt.inv_inr]))
    (add unsafe 50% (by simp_rw [TrivSqZeroExt.inv_inv]))
    (add unsafe 50% (by simp_rw [Nat.floor_one]))
    (add unsafe 50% (by simp_rw [TrivSqZeroExt.inv_inl]))
    (add unsafe 50% (by simp_rw [inv_eq_one_div]))
    (add unsafe 10% (by nlinarith [neg_inv]))
    (add unsafe 10% (by simp_all only [one_div]))
    (add unsafe 50% (by simp_rw [inv_eq_one]))
    (add unsafe 10% (by nlinarith [inv_eq_iff_eq_inv]))
    (add unsafe 10% (by nlinarith [RatFunc.single_inv]))
    (add unsafe 50% (by simp_rw [TrivSqZeroExt.fst_one]))
    (add unsafe 50% (by simp_rw [TrivSqZeroExt.mul_inv_cancel]))
    (add unsafe 10% (by nlinarith [map_inv₀]))
    (add unsafe 10% (by nlinarith [inv_neg]))
    (add unsafe 10% (by nlinarith [inv_goldConj]))
    (add unsafe 50% (by simp_rw [Nat.ceil_one]))
    (add unsafe 90% (by rw [one_ne_zero] at *))
    (add unsafe 50% (by simp_rw [Hyperreal.Infinite.st_eq]))
    (add unsafe 50% (by simp_rw [Int.floor_one]))
    (add unsafe 50% (by simp_rw [TrivSqZeroExt.inv_mul_cancel]))
    (add unsafe 50% (by simp_rw [TrivSqZeroExt.inl_one]))
    (add unsafe 10% (by nlinarith [PadicInt.valuation_p]))