import Mathlib

theorem mathd_numbertheory_341 (a b c : ℕ) (h₀ : a ≤ 9 ∧ b ≤ 9 ∧ c ≤ 9)
    (h₁ : Nat.digits 10 (5 ^ 100 % 1000) = [c, b, a]) : a + b + c = 13 := by

  aesop (config := {
    maxRuleApplicationDepth := 60
    maxNormIterations := 520
    maxGoals := 1024
  })
    (add norm 100 (by ring))
    (add norm 100 (by field_simp))
    (add norm 100 (by norm_num))
    (add norm 100 (by norm_cast))
    (add norm 0 (by linarith))
    (add norm 0 (by nlinarith))
    (add norm 0 (by omega))
    (add norm 100 (by abel))
    (add norm 100 (by zify))
    (add norm 0 (by gcongr))
    (add norm 100 (by bound))
    (add norm 0 (by interval_cases))
    (add norm 100 (by exfalso))
    (add norm 0 (by simp))
    (add norm 0 (by ring_nf at *))
    (add norm 100 (by norm_num [*] at *))
    (add norm 100 (by norm_cast at *))
    (add norm 100 (by rfl))
    (add norm 0 (by decide))
    (add norm 100 (by push_cast))
    (add norm 100 (by assumption_mod_cast))
    (add safe 0 (by ring_nf))
    (add safe 0 (by split))
    (add safe 1 (by field_simp [*] at *))
    (add unsafe 90% (by ext))
    (add unsafe 90% (by simp_all))
    (add norm 100 (by rw [← Nat.digits_of_lt]))
    (add norm 100 (by rw [← Nat.NormDigits.digits_one]))
    (add norm 0 (by simp [Nat.one_mul] at *))
    (add norm 100 (by rw [← Nat.digits_add]))
    (add norm 100 (by rw [← Nat.add_div]))
    (add norm 100 (by rw [← Nat.digits_add_two_add_one]))
    (add norm 100 (by rw [← Nat.digits_def']))
    (add norm 100 (by norm_num [Nat.zero_add] at *))
    (add norm 100 (by rw [Nat.ofDigits_one] at *))
    (add norm 100 (by rw [← Nat.digits_eq_cons_digits_div]))
    (add norm 0 (by rw [← Nat.div_eq_of_lt]))
    (add norm 100 (by rw [← Nat.pow_one]))
    (add norm 0 (by simp [Nat.mul_one] at *))
    (add norm 100 (by rw [← Nat.div_mod_unique]))
    (add norm 100 (by norm_num [Nat.add_zero] at *))
    (add norm 0 (by rw [← Nat.div_one]))
    (add safe 0 (by grind only [Nat.le_add_left]))
    (add safe 0 (by grind only [Zsqrtd.SqLe]))
    (add unsafe 90% (by simp [Nat.digits] at *))
    (add unsafe 90% (by simp [Nat.div_add_mod] at *))
    (add unsafe 90% (by simp [Nat.mod_add_div] at *))
    (add unsafe 90% (by simp_rw [Nat.le_add_right]))
    (add unsafe 90% (by apply Nat.digits_zero))
    (add unsafe 90% (by simp [Nat.add_comm] at *))
    (add unsafe 90% (by simp [PNat.XgcdType.r] at *))
    (add unsafe 90% (by apply Nat.digits_one))
    (add unsafe 90% (by solve_by_elim [Num.cast_one]))
    (add unsafe 10% (by push_cast [Nat] at *))
    (add unsafe 10% (by push_cast [Nat.one_add] at *))
    (add unsafe 90% (by simp [Matrix.get_node_cy] at *))
    (add unsafe 90% (by simp [Nat.mod_lt] at *))
    (add unsafe 90% (by simp [Nat.add_le_add] at *))