import Mathlib

theorem mathd_numbertheory_342 : 54 % 6 = 0 := by

  aesop (config := {
    maxRuleApplications := 100
    maxRuleApplicationDepth := 10
    maxNormIterations := 60
    enableUnfold := false
  }) (rule_sets := [-builtin])
    (add norm 100 (by ring))
    (add norm 100 (by field_simp))
    (add norm 100 (by norm_num))
    (add norm 100 (by norm_cast))
    (add norm 0 (by linarith))
    (add norm 0 (by nlinarith))
    (add norm 0 (by omega))
    (add norm 100 (by abel))
    (add norm 100 (by zify))
    (add norm 0 (by bound))
    (add norm 100 (by interval_cases))
    (add norm 100 (by ext))
    (add norm 100 (by split))
    (add norm 100 (by exfalso))
    (add norm 100 (by ring_nf at *))
    (add norm 100 (by norm_num [*] at *))
    (add norm 100 (by norm_cast at *))
    (add norm 100 (by rfl))
    (add norm 100 (by push_cast))
    (add norm 100 (by assumption_mod_cast))
    (add safe 0 (by ring_nf))
    (add safe 0 (by field_simp [*] at *))
    (add unsafe 90% (by simp_all))
    (add norm 100 (by rw [← Nat.mul_mod]))
    (add norm 100 (by rw [← Nat.mul_mod_left]))
    (add norm 100 (by rw [← Nat.mod_mod_of_dvd]))
    (add norm 100 (by rw [← Nat.mul_mod_mod]))
    (add norm 100 (by rw [← Nat.pow_mod]))
    (add norm 100 (by rw [← Int.emod_two_ne_zero]))
    (add norm 100 (by rw [← neg_one_pow_eq_pow_mod_two]))
    (add norm 100 (by rw [← Nat.mul_mod_right]))
    (add norm 100 (by rw [← Nat.mod_mod]))
    (add norm 100 (by rw [← Nat.gcd.induction]))
    (add norm 100 (by rw [← Nat.mod_two_of_bodd]))
    (add norm 100 (by rw [← EuclideanDomain.zero_mod]))
    (add norm 100 (by rw [← Nat.mod_mul_left_mod]))
    (add unsafe 10% (by push_cast [Nat.mod_two_ne_zero] at *))
    (add unsafe 10% (by push_cast [Nat.mod_two_ne_one] at *))
    (add unsafe 50% (by simp_rw [GaussianInt.mod_four_eq_three_of_nat_prime_of_prime]))
    (add unsafe 50% (by simp_rw [Int.mul_emod]))
    (add unsafe 10% (by push_cast [Int.emod_two_ne_one] at *))
    (add unsafe 10% (by push_cast [Nat.even_iff] at *))
    (add unsafe 10% (by push_cast [Nat.odd_iff] at *))
    (add unsafe 10% (by push_cast [Int.emod_two_eq_zero_or_one] at *))
    (add unsafe 10% (by push_cast [coprime_sq_sub_sq_sum_of_odd_odd] at *))
    (add unsafe 10% (by push_cast [Int.odd_iff] at *))
    (add unsafe 50% (by simp_rw [Int.emod_emod]))
    (add unsafe 10% (by push_cast [ZMod.χ₈_nat_eq_if_mod_eight] at *))
    (add unsafe 50% (by simp_rw [Int.sq_ne_two_mod_four]))
    (add unsafe 10% (by push_cast [ZMod.χ₈'_nat_eq_if_mod_eight] at *))
    (add unsafe 10% (by push_cast [Nat.not_even_iff] at *))
    (add unsafe 50% (by simp_rw [Int.emod_eq_emod_iff_emod_sub_eq_zero]))
    (add unsafe 10% (by push_cast [Int.even_iff] at *))
    (add unsafe 50% (by simp_rw [Int.ofNat_emod]))
    (add unsafe 50% (by simp_rw [Int.add_emod]))