import Mathlib

theorem mathd_algebra_176 (x : ℝ) : (x + 1) ^ 2 * x = x ^ 3 + 2 * x ^ 2 + x := by

  aesop (config := {
    maxRuleApplications := 400
    maxRuleApplicationDepth := 220
    maxNormIterations := 520
  }) (rule_sets := [-builtin])
    (add norm 100 (by ring))
    (add norm 100 (by field_simp))
    (add norm 100 (by norm_num))
    (add norm 100 (by norm_cast))
    (add norm 0 (by linarith))
    (add norm 0 (by nlinarith))
    (add norm 0 (by omega))
    (add norm 100 (by abel))
    (add norm 100 (by zify))
    (add norm 100 (by bound))
    (add norm 100 (by interval_cases))
    (add norm 100 (by ext))
    (add norm 100 (by split))
    (add norm 100 (by exfalso))
    (add norm 100 (by ring_nf at *))
    (add norm 100 (by field_simp [*] at *))
    (add norm 100 (by norm_num [*] at *))
    (add norm 100 (by norm_cast at *))
    (add norm 100 (by rfl))
    (add norm 100 (by push_cast))
    (add norm 100 (by assumption_mod_cast))
    (add safe 1 (by ring_nf))
    (add safe 0 (by simp_all))
    (add norm 0 (by grind only [euler_four_squares]))
    (add norm 0 (by grind only [sq_add_sq_mul]))
    (add norm 1 (by field_simp [Real.rpow_two] at *))
    (add norm 1 (by field_simp [Quaternion.star_coe] at *))
    (add norm 0 (by grind only [integral_gaussian]))
    (add norm 100 (by solve_by_elim [Quaternion.coeComplex_mul]))
    (add norm 0 (by rw [← sq_add_sq_mul_sq_add_sq]))
    (add norm 1 (by field_simp [Quaternion.coe_mul_eq_smul] at *))
    (add norm 0 (by rw [← Pell.Solution₁.prop_x]))
    (add norm 100 (by rw [← mul_pow]))
    (add norm 0 (by grind only [Quaternion.normSq_exp]))
    (add norm 1 (by field_simp [Quaternion.normSq] at *))
    (add safe 1 (by rw [Quaternion.inner_self]))
    (add safe 0 (by nlinarith [Complex.ofReal_pow]))
    (add unsafe 50% (by simp [Quaternion.coe_mul] at *))
    (add unsafe 10% (by push_cast [sq_sub_sq] at *))
    (add unsafe 10% (by push_cast [Quaternion.normSq_coe] at *))
    (add unsafe 10% (by push_cast [Real.sq_sqrt] at *))
    (add unsafe 90% (by norm_num [Quaternion.coe_commutes] at *))
    (add unsafe 10% (by push_cast [Quaternion.exp_coe] at *))
    (add unsafe 10% (by push_cast [ArithmeticFunction.moebius_sq] at *))
    (add unsafe 10% (by push_cast [Real.sqrt_eq_rpow] at *))
    (add unsafe 10% (by push_cast [Quaternion.normSq_smul] at *))
    (add unsafe 10% (by push_cast [Quaternion.normSq_ratCast] at *))
    (add unsafe 10% (by push_cast [sq_abs] at *))
    (add unsafe 10% (by push_cast [QuaternionGroup.xa_sq] at *))
    (add unsafe 50% (by solve_by_elim [Quaternion.normSq_def']))
    (add unsafe 10% (by push_cast [Quaternion.normSq_natCast] at *))
    (add unsafe 10% (by push_cast [Real.sqrt_sq] at *))
    (add unsafe 50% (by simp only [norm_add_sq_real]))
    (add unsafe 10% (by push_cast [EuclideanSpace.norm_eq] at *))
    (add unsafe 10% (by push_cast [pow_two] at *))