import Mathlib

theorem mathd_numbertheory_765 (x : ℤ) (h₀ : x < 0) (h₁ : 24 * x % 1199 = 15) : x ≤ -449 := by

  aesop (config := {
    maxRuleApplicationDepth := 60
    maxNormIterations := 60
    maxGoals := 128
    enableUnfold := false
  })
    (add norm 100 (by ring))
    (add norm 100 (by field_simp))
    (add norm 100 (by norm_num))
    (add norm 100 (by norm_cast))
    (add norm 0 (by linarith))
    (add norm 0 (by nlinarith))
    (add norm 0 (by positivity))
    (add norm 100 (by abel))
    (add norm 0 (by push_neg))
    (add norm 0 (by gcongr))
    (add norm 0 (by bound))
    (add norm 0 (by interval_cases))
    (add norm 0 (by ext))
    (add norm 100 (by exfalso))
    (add norm 0 (by simp))
    (add norm 0 (by ring_nf at *))
    (add norm 100 (by norm_cast at *))
    (add norm 100 (by rfl))
    (add norm 0 (by decide))
    (add norm 100 (by push_cast))
    (add safe 0 (by omega))
    (add safe 1 (by zify))
    (add safe 0 (by ring_nf))
    (add safe 0 (by split))
    (add safe 0 (by simp_all))
    (add safe 0 (by field_simp [*] at *))
    (add safe 0 (by assumption_mod_cast))
    (add unsafe 50% (by norm_num [*] at *))
    (add norm 0 (by grind only [Int.emod_nonneg]))
    (add safe 1 (by rw [Int.ofNat_zero_le]))
    (add safe 0 (by rw [← one_le_inv_of_le_one]))
    (add safe 1 (by rw [Int.cast_nonpos]))
    (add safe 0 (by field_simp [Real.logb_le_logb_of_base_lt_one] at *))
    (add safe 0 (by field_simp [Real.logb_le_logb] at *))
    (add safe 1 (by rw [Real.logb_le_logb_of_le]))
    (add safe 1 (by rw [Int.ofNat_nonneg]))
    (add safe 1 (by rw [Real.log_neg_natCast_nonneg]))
    (add safe 0 (by rw [← inv_le_inv_iff]))
    (add safe 1 (by rw [Real.norm_of_nonpos]))
    (add unsafe 50% (by simp [Int.cast_nonneg] at *))
    (add unsafe 10% (by simp_all only [Int.cast_le_neg_one_or_one_le_cast_of_ne_zero]))
    (add unsafe 50% (by simp_rw [Real.logb_nonpos]))
    (add unsafe 50% (by simp [Int.cast_le_neg_one_of_neg] at *))
    (add unsafe 50% (by simp [Int.cast_one_le_of_pos] at *))
    (add unsafe 50% (by simp [Int.natCast_nonneg] at *))
    (add unsafe 50% (by simp [Int.le_of_dvd] at *))
    (add unsafe 50% (by unfold Int.le_iff_pos_of_dvd))
    (add unsafe 50% (by simp [Int.ofNat_le] at *))
    (add unsafe 50% (by unfold Int.natCast_nonpos_iff))
    (add unsafe 50% (by simp_rw [Real.mul_log_nonpos]))
    (add unsafe 50% (by push_cast [Int.exists_greatest_of_bdd] at *))
    (add unsafe 10% (by simp_all only [Int.ofNat_natAbs_of_nonpos]))
    (add unsafe 50% (by unfold Int.le_of_lt))
    (add unsafe 50% (by simp [Left.inv_le_one_iff] at *))
    (add unsafe 50% (by simp [Int.ofNat_lt] at *))
    (add unsafe 50% (by simp [Right.inv_le_one_iff] at *))
    (add unsafe 50% (by simp_rw [Real.log_nonpos]))
    (add unsafe 10% (by simp_all only [le_inv']))
    (add unsafe 50% (by simp [mul_le_mul_left_of_neg] at *))
    (add unsafe 50% (by simp [Int.natAbs_of_nonneg] at *))