import Mathlib

theorem mathd_algebra_114 (a : ℝ) (h₀ : a = 8) :
    (16 * (a ^ 2) ^ ((1 : ℝ) / 3)) ^ ((1 : ℝ) / 3) = 4 := by

  aesop (config := {
    maxRuleApplications := 400
    maxRuleApplicationDepth := 220
    maxNormIterations := 180
    enableUnfold := false
  }) (rule_sets := [-builtin])
    (add norm 100 (by ring))
    (add norm 100 (by field_simp))
    (add norm 100 (by norm_num))
    (add norm 0 (by linarith))
    (add norm 0 (by nlinarith))
    (add norm 0 (by omega))
    (add norm 100 (by abel))
    (add norm 100 (by zify))
    (add norm 0 (by gcongr))
    (add norm 0 (by bound))
    (add norm 100 (by interval_cases))
    (add norm 0 (by ext))
    (add norm 100 (by exfalso))
    (add norm 0 (by simp))
    (add norm 100 (by ring_nf at *))
    (add norm 100 (by norm_num [*] at *))
    (add norm 100 (by norm_cast at *))
    (add norm 100 (by rfl))
    (add norm 0 (by decide))
    (add norm 100 (by push_cast))
    (add norm 100 (by assumption_mod_cast))
    (add safe 0 (by ring_nf))
    (add safe 0 (by split))
    (add safe 0 (by field_simp [*] at *))
    (add unsafe 50% (by norm_cast))
    (add unsafe 90% (by simp_all))
    (add norm 1 (by simp_all [mul_inv_cancel]))
    (add norm 100 (by rw [← MeasureTheory.integral_comp_rpow_Ioi_of_pos]))
    (add norm 100 (by solve_by_elim [Complex.mul_cpow_ofReal_nonneg]))
    (add norm 100 (by rw [← MeasureTheory.integral_comp_rpow_Ioi]))
    (add norm 100 (by rw [← inv_mul_cancel]))
    (add norm 0 (by rw [← one_div_mul_cancel]))
    (add norm 100 (by solve_by_elim [Complex.ofReal_log]))
    (add norm 100 (by solve_by_elim [Complex.ofReal_cpow]))
    (add norm 100 (by rw [← Real.rpow_add]))
    (add norm 100 (by rw [← Complex.HadamardThreeLines.sSupNormIm_eps_pos]))
    (add safe 0 (by simp_rw [mul_one_div]))
    (add safe 1 (by rw [Real.sqrt_eq_rpow]))
    (add safe 0 (by simp_all [two_ne_zero]))
    (add unsafe 50% (by apply Real.rpow_one))
    (add unsafe 50% (by apply Real.rpow_mul))
    (add unsafe 90% (by simp_rw [Real.inv_rpow]))
    (add unsafe 50% (by apply Real.mul_rpow))
    (add unsafe 10% (by simp_all only [one_div]))
    (add unsafe 90% (by grind only [ne_of_gt]))
    (add unsafe 90% (by grind only [Real.rpow_pos_of_pos]))
    (add unsafe 10% (by simp_all [Real.doublingGamma]))
    (add unsafe 90% (by simp_rw [WeakFEPair.h_feq']))
    (add unsafe 90% (by simp_rw [Real.rpow_neg]))
    (add unsafe 50% (by unfold Real.Gamma_mul_Gamma_add_half_of_pos))
    (add unsafe 10% (by simp_all only [mul_one_div_cancel]))
    (add unsafe 50% (by unfold Real.Gamma))
    (add unsafe 10% (by simp_all [Real.doublingGamma_eq_Gamma]))
    (add unsafe 90% (by simp_rw [Real.rpow_neg_one]))
    (add unsafe 90% (by grind only [Real.Gamma_two]))
    (add unsafe 50% (by solve_by_elim [div_self]))
    (add unsafe 50% (by simp_rw [Complex.Gamma_one_half_eq]))
    (add unsafe 90% (by simp_rw [mellinInv_eq_fourierIntegralInv]))