import Mathlib

theorem mathd_numbertheory_320 (n : ℕ) (h₀ : n < 101) (h₁ : 101 ∣ 123456 - n) : n = 34 := by

  aesop (config := {
    maxRuleApplicationDepth := 220
    maxNormIterations := 60
    maxGoals := 1024
    enableUnfold := false
  })
    (add norm 100 (by ring))
    (add norm 100 (by field_simp))
    (add norm 100 (by norm_num))
    (add norm 0 (by linarith))
    (add norm 0 (by nlinarith))
    (add norm 0 (by omega))
    (add norm 100 (by abel))
    (add norm 100 (by zify))
    (add norm 0 (by gcongr))
    (add norm 0 (by bound))
    (add norm 0 (by interval_cases))
    (add norm 0 (by ext))
    (add norm 100 (by exfalso))
    (add norm 0 (by simp))
    (add norm 0 (by ring_nf at *))
    (add norm 100 (by field_simp [*] at *))
    (add norm 100 (by norm_num [*] at *))
    (add norm 100 (by norm_cast at *))
    (add norm 100 (by rfl))
    (add norm 0 (by decide))
    (add norm 100 (by push_cast))
    (add norm 100 (by assumption_mod_cast))
    (add safe 0 (by ring_nf))
    (add safe 0 (by split))
    (add unsafe 50% (by norm_cast))
    (add unsafe 90% (by simp_all))
    (add norm 1 (by simp only [Nat.sub_lt]))
    (add norm 100 (by rw [PNat.eq_one_of_lt_two] at *))
    (add norm 0 (by grind only [lt_of_le_of_ne]))
    (add norm 1 (by rw [← Nat.sub_pos_of_lt] at *))
    (add norm 100 (by rw [← Nat.not_eq_zero_of_lt]))
    (add norm 100 (by unfold Nat.clog))
    (add safe 1 (by rw [← Pell.eq_pell] at *))
    (add safe 0 (by simp_all [Nat.pos_of_dvd_of_pos]))
    (add safe 0 (by simp_all [IsPrimePow.one_lt]))
    (add safe 100 (by simp_rw [tsub_pos_of_lt]))
    (add safe 1 (by rw [Nat.eq_zero_of_dvd_of_lt]))
    (add safe 0 (by simp_all [Nat.le_of_dvd]))
    (add safe 0 (by simp_all [ascPochhammer_pos]))
    (add safe 0 (by simp_all [Pell.x_pos]))
    (add safe 1 (by rw [← le_of_not_lt] at *))
    (add safe 1 (by rw [← not_lt_of_ge] at *))
    (add safe 1 (by rw [← lt_of_not_ge] at *))
    (add safe 0 (by simp_all [Nat.pos_of_ne_zero]))
    (add safe 1 (by rw [← pow_eq_zero_of_le] at *))
    (add safe 1 (by rw [← not_le_of_gt] at *))
    (add safe 0 (by simp_all [Nat.dist_pos_of_ne]))
    (add safe 0 (by simp_all [Pell.eq_pow_of_pell_lem]))
    (add safe 1 (by rw [← exists_nat_pow_near] at *))
    (add safe 0 (by simp_all [Nat.dvd_two_of_totient_le_one]))
    (add safe 0 (by simp_all [Nat.zero_lt_of_ne_zero]))
    (add safe 0 (by simp_all [one_lt_mersenne]))
    (add safe 0 (by simp_all [pos_of_gt]))
    (add safe 1 (by rw [← Nat.le_sub_one_of_lt] at *))
    (add safe 1 (by rw [← le_of_not_gt] at *))
    (add safe 0 (by simp_all [mersenne_pos]))
    (add safe 1 (by rw [← Nat.succ_le_of_lt] at *))
    (add unsafe 10% (by push_cast [pow_unbounded_of_one_lt] at *))