import Mathlib

theorem mathd_numbertheory_293 (n : ℕ) (h₀ : n ≤ 9) (h₁ : 11 ∣ 20 * 100 + 10 * n + 7) : n = 5 := by

  aesop (config := {
    maxRuleApplicationDepth := 220
    maxNormIterations := 520
    maxGoals := 32
  })
    (add norm 100 (by ring))
    (add norm 100 (by field_simp))
    (add norm 100 (by norm_num))
    (add norm 100 (by norm_cast))
    (add norm 0 (by linarith))
    (add norm 0 (by nlinarith))
    (add norm 0 (by omega))
    (add norm 100 (by abel))
    (add norm 100 (by zify))
    (add norm 0 (by bound))
    (add norm 100 (by interval_cases))
    (add norm 100 (by ext))
    (add norm 100 (by split))
    (add norm 100 (by exfalso))
    (add norm 100 (by simp))
    (add norm 100 (by ring_nf at *))
    (add norm 100 (by norm_num [*] at *))
    (add norm 100 (by norm_cast at *))
    (add norm 100 (by rfl))
    (add norm 100 (by push_cast))
    (add norm 100 (by assumption_mod_cast))
    (add safe 1 (by ring_nf))
    (add unsafe 90% (by simp_all))
    (add unsafe 50% (by field_simp [*] at *))
    (add norm 1 (by simp only [Nat.one_le_iff_ne_zero]))
    (add norm 0 (by grind only [Nat.mod_lt]))
    (add norm 0 (by grind only [lt_of_le_of_ne]))
    (add norm 0 (by grind only [Nat.exists_eq_succ_of_ne_zero]))
    (add norm 1 (by norm_num [Nat.factorization_le_iff_dvd] at *))
    (add safe 0 (by simp_all [Nat.le_of_dvd]))
    (add safe 0 (by simp_all [Nat.pos_of_ne_zero]))
    (add safe 0 (by simp_all [Nat.dvd_two_of_totient_le_one]))
    (add safe 0 (by simp_all [Nat.pos_of_dvd_of_pos]))
    (add safe 0 (by unfold Nat.dvd_factorial))
    (add safe 0 (by unfold Nat.Prime.one_lt))
    (add safe 0 (by simp_all [Nat.not_dvd_of_pos_of_lt]))
    (add safe 1 (by rw [Nat.mul_div_lt_iff_not_dvd]))
    (add safe 0 (by simp_all [pos_of_gt]))
    (add safe 1 (by rw [← Nat.one_le_of_lt] at *))
    (add safe 1 (by rw [Nat.eq_zero_of_dvd_of_lt]))
    (add safe 1 (by rw [← Nat.succ_le_of_lt] at *))
    (add safe 1 (by rw [Nat.pos_iff_ne_zero]))
    (add safe 1 (by rw [Nat.not_eq_zero_of_lt]))
    (add safe 1 (by rw [Ordnode.Sized.pos]))
    (add safe 0 (by simp_all [Pell.y_dvd_iff]))
    (add safe 0 (by simp_all [dvd_trans]))
    (add safe 0 (by unfold Nat.minSqFacProp_div))
    (add safe 0 (by simp_all [Nat.not_dvd_of_between_consec_multiples]))
    (add safe 0 (by nlinarith [IsPrimePow.one_lt]))
    (add safe 0 (by simp_all [Nat.totient_pos]))
    (add unsafe 50% (by push_cast [Pell.x_pos] at *))
    (add unsafe 50% (by push_cast [Zsqrtd.d_pos] at *))
    (add unsafe 50% (by push_cast [Pell.yn_ge_n] at *))
    (add unsafe 50% (by push_cast [Pell.d_pos] at *))
    (add unsafe 90% (by grind only [padicNorm.nat_lt_one_iff]))
    (add unsafe 10% (by field_simp [LucasLehmer.two_lt_q] at *))