import Mathlib

theorem mathd_algebra_400 (x : ℝ) (h₀ : 5 + 500 / 100 * 10 = 110 / 100 * x) : x = 50 := by

  aesop (config := {
    maxRuleApplications := 1600
    maxRuleApplicationDepth := 10
    maxNormIterations := 60
    maxGoals := 32
    enableUnfold := false
  }) (rule_sets := [-builtin])
    (add norm 100 (by ring))
    (add norm 100 (by field_simp))
    (add norm 100 (by norm_num))
    (add norm 0 (by linarith))
    (add norm 0 (by nlinarith))
    (add norm 0 (by omega))
    (add norm 100 (by abel))
    (add norm 100 (by zify))
    (add norm 0 (by bound))
    (add norm 100 (by interval_cases))
    (add norm 100 (by ext))
    (add norm 100 (by split))
    (add norm 100 (by exfalso))
    (add norm 0 (by simp))
    (add norm 100 (by ring_nf at *))
    (add norm 100 (by field_simp [*] at *))
    (add norm 100 (by norm_num [*] at *))
    (add norm 100 (by norm_cast at *))
    (add norm 100 (by rfl))
    (add norm 0 (by decide))
    (add norm 100 (by push_cast))
    (add norm 100 (by assumption_mod_cast))
    (add safe 1 (by norm_cast))
    (add safe 0 (by ring_nf))
    (add unsafe 90% (by simp_all))
    (add norm 100 (by apply div_self))
    (add norm 100 (by apply div_mul_cancel₀))
    (add norm 100 (by apply div_eq_one_iff_eq))
    (add norm 100 (by apply mul_div_cancel₀))
    (add norm 100 (by apply mul_div_cancel_right₀))
    (add norm 100 (by apply mul_div_mul_left))
    (add norm 100 (by apply sub_div))
    (add norm 0 (by grind only [mul_div]))
    (add norm 100 (by apply mul_div_assoc))
    (add norm 0 (by grind only [div_eq_iff_mul_eq]))
    (add norm 100 (by apply div_sub'))
    (add norm 100 (by apply div_left_inj'))
    (add norm 100 (by apply mul_div_mul_right))
    (add norm 0 (by grind only [eq_div_iff_mul_eq]))
    (add norm 100 (by apply Real.log_div))
    (add norm 0 (by grind only [Stirling.stirlingSeq]))
    (add norm 100 (by apply mul_one_div))
    (add norm 100 (by apply Rat.num_div_den))
    (add norm 0 (by grind only [one_div]))
    (add norm 0 (by grind only [Real.div_sqrt]))
    (add norm 100 (by simp only [mul_one] at *))
    (add norm 0 (by grind only [goldenConj]))
    (add norm 100 (by simp only [one_mul] at *))
    (add norm 100 (by apply div_sub_div))
    (add safe 0 (by simp_all [mul_div_cancel_left₀]))
    (add safe 0 (by simp_all [two_ne_zero']))
    (add unsafe 10% (by push_cast [eq_div_iff] at *))
    (add unsafe 10% (by push_cast [div_eq_iff] at *))
    (add unsafe 10% (by rw [← add_div] at *))
    (add unsafe 10% (by linarith [div_div]))
    (add unsafe 10% (by linarith [div_mul]))
    (add unsafe 90% (by grind only [div_right_comm]))