import Mathlib

theorem mathd_algebra_141 (a b : ℝ) (h₁ : a * b = 180) (h₂ : 2 * (a + b) = 54) :
    a ^ 2 + b ^ 2 = 369 := by

  aesop (config := {
    maxRuleApplicationDepth := 220
    maxNormIterations := 60
    enableUnfold := false
  }) (rule_sets := [-builtin])
    (add norm 100 (by ring))
    (add norm 100 (by field_simp))
    (add norm 100 (by norm_num))
    (add norm 0 (by linarith))
    (add norm 0 (by nlinarith))
    (add norm 0 (by omega))
    (add norm 100 (by abel))
    (add norm 100 (by zify))
    (add norm 0 (by gcongr))
    (add norm 0 (by bound))
    (add norm 100 (by interval_cases))
    (add norm 100 (by ext))
    (add norm 100 (by exfalso))
    (add norm 0 (by simp))
    (add norm 100 (by ring_nf at *))
    (add norm 100 (by field_simp [*] at *))
    (add norm 100 (by norm_num [*] at *))
    (add norm 100 (by norm_cast at *))
    (add norm 100 (by rfl))
    (add norm 100 (by push_cast))
    (add norm 100 (by assumption_mod_cast))
    (add safe 1 (by norm_cast))
    (add safe 1 (by ring_nf))
    (add safe 0 (by split))
    (add safe 0 (by simp_all))
    (add norm 0 (by grind only [sq_add_sq_mul]))
    (add norm 100 (by norm_num [euler_four_squares] at *))
    (add norm 100 (by norm_num [Pell.Solution₁.prop_y] at *))
    (add norm 0 (by grind only [UpperHalfPlane.dist_coe_center_sq]))
    (add norm 0 (by grind only [Complex.sq_abs]))
    (add norm 100 (by rw [← EuclideanSpace.norm_eq]))
    (add norm 1 (by rw [norm_add_sq]))
    (add norm 100 (by rw [← QuaternionGroup.xa_sq]))
    (add safe 0 (by simp_all [Real.rpow_two]))
    (add safe 0 (by simp_all [CoxeterSystem.simple_sq]))
    (add safe 1 (by linarith [zero_le_two]))
    (add unsafe 10% (by push_cast [sq_sub_sq] at *))
    (add unsafe 10% (by push_cast [Real.sq_sqrt] at *))
    (add unsafe 10% (by push_cast [sq_pos_of_pos] at *))
    (add unsafe 10% (by push_cast [sq_abs] at *))
    (add unsafe 10% (by push_cast [pow_two] at *))
    (add unsafe 10% (by push_cast [sq_lt_sq] at *))
    (add unsafe 10% (by push_cast [sq_nonneg] at *))
    (add unsafe 10% (by push_cast [Real.sqrt_sq] at *))
    (add unsafe 50% (by simp only [Pell.Solution₁.prop_x]))
    (add unsafe 10% (by push_cast [sq_eq_sq] at *))
    (add unsafe 10% (by push_cast [EisensteinSeries.r1] at *))
    (add unsafe 10% (by push_cast [sq_le_sq] at *))
    (add unsafe 10% (by push_cast [zero_lt_two] at *))
    (add unsafe 10% (by push_cast [two_ne_zero] at *))
    (add unsafe 10% (by push_cast [Pell.Solution₁.prop] at *))
    (add unsafe 10% (by push_cast [ArithmeticFunction.moebius_sq] at *))
    (add unsafe 50% (by simp only [norm_add_sq_real]))
    (add unsafe 10% (by push_cast [Real.sqrt_lt] at *))
    (add unsafe 10% (by push_cast [sub_sq] at *))
    (add unsafe 50% (by simp only [abs_sq]))
    (add unsafe 10% (by push_cast [EisensteinSeries.auxbound1] at *))