import Mathlib

theorem mathd_algebra_139 (s : ℝ → ℝ → ℝ)
    (h₀ : ∀ (x) (_ : x ≠ 0), ∀ (y) (_ : y ≠ 0), s x y = (1 / y - 1 / x) / (x - y)) :
    s 3 11 = 1 / 33 := by

  aesop (config := {
    maxRuleApplications := 1600
    maxRuleApplicationDepth := 10
    maxNormIterations := 30
    maxGoals := 1024
    enableUnfold := false
  }) (rule_sets := [-builtin])
    (add norm 100 (by ring))
    (add norm 100 (by field_simp))
    (add norm 100 (by norm_num))
    (add norm 100 (by norm_cast))
    (add norm 0 (by linarith))
    (add norm 0 (by nlinarith))
    (add norm 0 (by omega))
    (add norm 100 (by abel))
    (add norm 100 (by zify))
    (add norm 100 (by bound))
    (add norm 100 (by interval_cases))
    (add norm 100 (by ext))
    (add norm 100 (by split))
    (add norm 100 (by exfalso))
    (add norm 100 (by ring_nf at *))
    (add norm 100 (by field_simp [*] at *))
    (add norm 100 (by norm_num [*] at *))
    (add norm 100 (by norm_cast at *))
    (add norm 100 (by rfl))
    (add norm 100 (by decide))
    (add norm 100 (by push_cast))
    (add norm 100 (by assumption_mod_cast))
    (add safe 0 (by ring_nf))
    (add unsafe 90% (by simp_all))
    (add norm 100 (by apply div_self))
    (add norm 0 (by grind only [one_div]))
    (add norm 0 (by grind only [div_ne_one]))
    (add norm 100 (by apply mul_one_div))
    (add norm 100 (by apply div_eq_one_iff_eq))
    (add norm 100 (by apply sub_div))
    (add norm 100 (by apply div_ne_zero))
    (add norm 100 (by apply div_mul_cancel₀))
    (add norm 0 (by grind only [div_one]))
    (add norm 0 (by grind only [div_sub']))
    (add norm 0 (by grind only [div_ne_one_of_ne]))
    (add norm 100 (by apply mul_div_cancel₀))
    (add norm 0 (by grind only [neg_div]))
    (add norm 0 (by grind only [one_div_one]))
    (add norm 0 (by grind only [eq_div_iff]))
    (add norm 0 (by grind only [div_eq_iff]))
    (add norm 0 (by grind only [one_ne_zero]))
    (add norm 0 (by grind only [div_neg]))
    (add norm 100 (by rw [integral_one_div_of_pos]))
    (add norm 0 (by grind only [Real.div_rpow]))
    (add norm 0 (by grind only [WeierstrassCurve.Affine.slope_of_X_ne]))
    (add norm 0 (by grind only [WeierstrassCurve.Affine.slope]))
    (add norm 0 (by grind only [sub_div']))
    (add norm 0 (by grind only [two_ne_zero']))
    (add norm 0 (by grind only [Real.Gamma_one]))
    (add norm 100 (by rw [Complex.Gammaℝ_one]))
    (add norm 0 (by grind only [div_self']))
    (add norm 1 (by linarith [Real.log_div]))
    (add norm 0 (by grind only [div_div]))
    (add norm 0 (by grind only [WeakFEPair.h_feq']))
    (add norm 0 (by grind only [mul_div_assoc]))
    (add unsafe 10% (by linarith [div_eq_inv_mul]))