import Mathlib

theorem mathd_algebra_487 (a b c d : ℝ) (h₀ : b = a ^ 2) (h₁ : a + b = 1) (h₂ : d = c ^ 2)
    (h₃ : c + d = 1) (h₄ : a ≠ c) : Real.sqrt ((a - c) ^ 2 + (b - d) ^ 2) = Real.sqrt 10 := by

  aesop (config := {
    maxRuleApplications := 100
    maxRuleApplicationDepth := 220
    maxNormIterations := 60
    maxGoals := 16
    useDefaultSimpSet := false
  }) (rule_sets := [-builtin])
    (add norm 100 (by ring))
    (add norm 100 (by field_simp))
    (add norm 100 (by norm_num))
    (add norm 100 (by norm_cast))
    (add norm 0 (by linarith))
    (add norm 0 (by nlinarith))
    (add norm 0 (by omega))
    (add norm 100 (by abel))
    (add norm 100 (by zify))
    (add norm 100 (by bound))
    (add norm 100 (by interval_cases))
    (add norm 100 (by ext))
    (add norm 100 (by split))
    (add norm 100 (by exfalso))
    (add norm 0 (by simp_all))
    (add norm 100 (by ring_nf at *))
    (add norm 100 (by field_simp [*] at *))
    (add norm 100 (by norm_num [*] at *))
    (add norm 100 (by norm_cast at *))
    (add norm 100 (by rfl))
    (add norm 100 (by push_cast))
    (add norm 100 (by assumption_mod_cast))
    (add norm 0 (by grind only [Real.sqrt_mul]))
    (add norm 0 (by grind only [Real.mul_self_sqrt]))
    (add norm 0 (by grind only [Real.sqrt_mul_self]))
    (add norm 0 (by grind only [sq_eq_sq]))
    (add norm 0 (by grind only [Real.sqrt_mul']))
    (add norm 0 (by grind only [Real.sqrt_sq_eq_abs]))
    (add norm 0 (by grind only [norm_add_sq]))
    (add norm 0 (by grind only [Real.sqrt_nonneg]))
    (add norm 0 (by grind only [WithLp.prod_norm_eq_of_L2]))
    (add norm 0 (by grind only [EuclideanSpace.norm_eq]))
    (add norm 0 (by grind only [EuclideanSpace.dist_eq]))
    (add norm 0 (by grind only [sq_add_sq_mul]))
    (add norm 0 (by grind only [Real.sqrt_le_sqrt]))
    (add norm 0 (by grind only [norm_sub_sq]))
    (add norm 0 (by grind only [Real.sqrt]))
    (add norm 0 (by grind only [Real.sqrt_eq_rpow]))
    (add norm 0 (by grind only [UpperHalfPlane.dist_coe_center_sq]))
    (add norm 0 (by grind only [Real.cos_half]))
    (add norm 0 (by grind only [sq_add_sq_mul_sq_add_sq]))
    (add safe 0 (by simp_all [Real.rpow_two]))
    (add safe 0 (by simp_all [pow_two]))
    (add safe 1 (by rw [norm_add_sq_real]))
    (add safe 100 (by simp_all [sq_le_sq]))
    (add safe 1 (by rw [norm_sub_sq_real]))
    (add safe 1 (by rw [aux_add]))
    (add unsafe 10% (by push_cast [Real.sq_sqrt] at *))
    (add unsafe 10% (by push_cast [Real.sqrt_sq] at *))
    (add unsafe 10% (by push_cast [sq_sub_sq] at *))
    (add unsafe 90% (by unfold sq_abs))
    (add unsafe 90% (by simp [sq_nonneg] at *))
    (add unsafe 90% (by unfold sub_sq))
    (add unsafe 90% (by unfold sq_lt_sq))