import Mathlib

theorem mathd_algebra_143 (f g : ℝ → ℝ) (h₀ : ∀ x, f x = x + 1) (h₁ : ∀ x, g x = x ^ 2 + 3) :
    f (g 2) = 8 := by

  aesop (config := {
    maxRuleApplicationDepth := 220
    maxNormIterations := 520
    maxGoals := 1024
  }) (rule_sets := [-builtin])
    (add norm 100 (by ring))
    (add norm 100 (by field_simp))
    (add norm 100 (by norm_num))
    (add norm 0 (by linarith))
    (add norm 0 (by nlinarith))
    (add norm 0 (by omega))
    (add norm 100 (by abel))
    (add norm 100 (by zify))
    (add norm 0 (by bound))
    (add norm 100 (by interval_cases))
    (add norm 100 (by ext))
    (add norm 100 (by split))
    (add norm 100 (by exfalso))
    (add norm 100 (by ring_nf at *))
    (add norm 100 (by field_simp [*] at *))
    (add norm 100 (by norm_num [*] at *))
    (add norm 100 (by norm_cast at *))
    (add norm 100 (by rfl))
    (add norm 100 (by push_cast))
    (add norm 100 (by assumption_mod_cast))
    (add safe 1 (by norm_cast))
    (add safe 1 (by ring_nf))
    (add safe 0 (by simp_all))
    (add norm 100 (by rw [← ArithmeticFunction.moebius_sq]))
    (add norm 1 (by simp_all [zero_lt_two]))
    (add norm 0 (by grind only [integral_gaussian]))
    (add norm 0 (by grind only [sq_eq_one_iff]))
    (add norm 0 (by grind only [sq_add_sq_mul]))
    (add norm 0 (by grind only [sq_eq_sq]))
    (add norm 0 (by grind only [CoxeterSystem.simple_sq]))
    (add norm 0 (by grind only [Real.sqrt_eq_rpow]))
    (add norm 0 (by grind only [Real.exp_half]))
    (add norm 100 (by rw [← Real.rpow_one]))
    (add norm 1 (by simp_all [Real.exp_zero]))
    (add norm 0 (by grind only [EuclideanSpace.norm_eq]))
    (add norm 0 (by grind only [Quaternion.sq_eq_normSq]))
    (add norm 1 (by simp_all [two_mul]))
    (add safe 0 (by simp_all [Real.Gamma_two]))
    (add safe 0 (by simp_all [Real.rpow_two]))
    (add safe 0 (by simp_all [pow_two]))
    (add safe 0 (by nlinarith [Quaternion.coe_one]))
    (add safe 0 (by simp_all [Nat.cast_two]))
    (add safe 0 (by simp_all [two_ne_zero]))
    (add safe 0 (by unfold Real.Gamma))
    (add safe 1 (by linarith [zero_le_two]))
    (add unsafe 10% (by push_cast [even_two] at *))
    (add unsafe 90% (by grind only [Nat.factorial_two]))
    (add unsafe 90% (by unfold Real.sq_sqrt))
    (add unsafe 90% (by unfold sq_abs))
    (add unsafe 90% (by unfold Real.sqrt_sq))
    (add unsafe 50% (by simp [Quaternion.coe_re] at *))
    (add unsafe 90% (by grind only [Polynomial.derivative_sq]))
    (add unsafe 10% (by push_cast [sq_sub_sq] at *))
    (add unsafe 90% (by grind only [Polynomial.cyclotomic_two]))
    (add unsafe 10% (by push_cast [integral_id] at *))