import Mathlib

theorem mathd_algebra_432 (x : ℝ) : (x + 3) * (2 * x - 6) = 2 * x ^ 2 - 18 := by

  aesop (config := {
    maxRuleApplications := 400
    maxRuleApplicationDepth := 220
    maxNormIterations := 60
    maxGoals := 256
    enableUnfold := false
  }) (rule_sets := [-builtin])
    (add norm 100 (by ring))
    (add norm 100 (by field_simp))
    (add norm 100 (by norm_num))
    (add norm 100 (by norm_cast))
    (add norm 0 (by linarith))
    (add norm 0 (by nlinarith))
    (add norm 0 (by omega))
    (add norm 100 (by abel))
    (add norm 100 (by zify))
    (add norm 100 (by bound))
    (add norm 100 (by interval_cases))
    (add norm 100 (by ext))
    (add norm 100 (by split))
    (add norm 100 (by exfalso))
    (add norm 100 (by ring_nf at *))
    (add norm 100 (by field_simp [*] at *))
    (add norm 100 (by norm_num [*] at *))
    (add norm 100 (by norm_cast at *))
    (add norm 100 (by rfl))
    (add norm 100 (by push_cast))
    (add norm 100 (by assumption_mod_cast))
    (add safe 1 (by ring_nf))
    (add safe 0 (by simp_all))
    (add norm 100 (by simp only [Real.Gamma_two]))
    (add norm 0 (by grind only [zero_lt_two]))
    (add norm 0 (by grind only [two_mul]))
    (add norm 0 (by grind only [mul_two]))
    (add norm 0 (by grind only [Real.sqrt_eq_rpow]))
    (add norm 1 (by field_simp [mul_div_assoc] at *))
    (add norm 100 (by rw [← mul_div_cancel₀]))
    (add norm 0 (by grind only [Quaternion.star_add_self]))
    (add norm 0 (by grind only [Real.Gamma_mul_Gamma_add_half_of_pos]))
    (add norm 0 (by grind only [Quaternion.self_add_star]))
    (add norm 0 (by grind only [Real.Gamma_add_one]))
    (add norm 100 (by rw [← div_self] at *))
    (add norm 1 (by field_simp [mul_div_cancel_left₀] at *))
    (add norm 0 (by grind only [Real.Gamma_mul_Gamma_add_half]))
    (add norm 100 (by rw [CircleDeg1Lift.transnumAuxSeq]))
    (add norm 0 (by simp only [sub_div] at *))
    (add safe 1 (by linarith [zero_lt_two']))
    (add safe 0 (by simp_all [Nat.cast_two]))
    (add unsafe 10% (by push_cast [two_ne_zero] at *))
    (add unsafe 10% (by push_cast [two_ne_zero'] at *))
    (add unsafe 10% (by push_cast [sq_sub_sq] at *))
    (add unsafe 10% (by push_cast [mul_div] at *))
    (add unsafe 10% (by push_cast [div_div] at *))
    (add unsafe 10% (by push_cast [Real.sq_sqrt] at *))
    (add unsafe 10% (by push_cast [integral_id] at *))
    (add unsafe 10% (by push_cast [eq_div_iff_mul_eq] at *))
    (add unsafe 10% (by simp_all [Real.doublingGamma]))
    (add unsafe 10% (by push_cast [even_two] at *))
    (add unsafe 10% (by push_cast [sq_pos_of_pos] at *))
    (add unsafe 10% (by push_cast [div_mul] at *))
    (add unsafe 90% (by grind only [Nat.factorial_two]))
    (add unsafe 10% (by push_cast [Real.cos_sq] at *))