import Mathlib

theorem mathd_algebra_314 (n : ℕ) (h₀ : n = 11) : (1 / 4) ^ (n + 1) * 2 ^ (2 * n) = 1 / 4 := by

  aesop (config := {
    maxRuleApplications := 400
    maxRuleApplicationDepth := 10
    maxNormIterations := 520
    maxGoals := 64
  }) (rule_sets := [-builtin])
    (add norm 100 (by ring))
    (add norm 100 (by field_simp))
    (add norm 100 (by norm_num))
    (add norm 100 (by norm_cast))
    (add norm 0 (by linarith))
    (add norm 0 (by nlinarith))
    (add norm 0 (by omega))
    (add norm 100 (by abel))
    (add norm 100 (by zify))
    (add norm 100 (by bound))
    (add norm 100 (by interval_cases))
    (add norm 100 (by ext))
    (add norm 100 (by split))
    (add norm 100 (by exfalso))
    (add norm 100 (by ring_nf at *))
    (add norm 100 (by field_simp [*] at *))
    (add norm 100 (by norm_num [*] at *))
    (add norm 100 (by norm_cast at *))
    (add norm 100 (by rfl))
    (add norm 100 (by decide))
    (add norm 100 (by push_cast))
    (add norm 100 (by assumption_mod_cast))
    (add safe 0 (by ring_nf))
    (add safe 0 (by simp_all))
    (add norm 100 (by simp only [one_mul] at *))
    (add norm 100 (by simp only [mul_one] at *))
    (add norm 100 (by simp only [mul_assoc] at *))
    (add unsafe 10% (by rw [one_pow]))
    (add unsafe 10% (by rw [pow_add]))
    (add unsafe 10% (by rw [pow_mul]))
    (add unsafe 10% (by rw [neg_one_sq]))
    (add unsafe 10% (by rw [LucasLehmer.X.ω]))
    (add unsafe 10% (by rw [mul_pow]))
    (add unsafe 10% (by rw [Even.neg_one_pow]))
    (add unsafe 10% (by rw [pow_one]))
    (add unsafe 10% (by rw [ArithmeticFunction.moebius_sq_eq_one_of_squarefree]))
    (add unsafe 10% (by rw [pow_succ]))
    (add unsafe 10% (by rw [FractionalIdeal.count_pow]))
    (add unsafe 10% (by rw [pow_succ']))
    (add unsafe 10% (by rw [PerfectClosure.mk_pow]))
    (add unsafe 10% (by rw [LucasLehmer.X.ωb]))
    (add unsafe 10% (by rw [neg_pow]))
    (add unsafe 10% (by rw [Stirling.stirlingSeq_pow_four_div_stirlingSeq_pow_two_eq]))
    (add unsafe 10% (by push_cast [ZMod.neg_one_pow_div_two_of_three_mod_four] at *))
    (add unsafe 10% (by rw [LucasLehmer.ω_pow_eq_one]))
    (add unsafe 10% (by rw [geom_sum₂_with_one]))
    (add unsafe 10% (by rw [quadraticChar_sq_one]))
    (add unsafe 10% (by rw [QuaternionGroup.a_one_pow]))
    (add unsafe 10% (by rw [legendreSym.sq_one]))
    (add unsafe 10% (by rw [Nat.pow_succ']))
    (add unsafe 10% (by rw [QuaternionGroup.a_one_pow_n]))
    (add unsafe 10% (by rw [LucasLehmer.ω_pow_eq_neg_one]))
    (add unsafe 10% (by rw [IsNilpotent.pow_succ]))
    (add unsafe 10% (by rw [qrSign.sq_eq_one]))
    (add unsafe 10% (by rw [ZMod.χ₄_eq_neg_one_pow]))
    (add unsafe 10% (by push_cast [one_div] at *))