import Mathlib

theorem mathd_algebra_153 (n : ℝ) (h₀ : n = 1 / 3) :
    Int.floor (10 * n) + Int.floor (100 * n) + Int.floor (1000 * n) + Int.floor (10000 * n) = 3702 := by

  aesop (config := {
    maxRuleApplications := 40
    maxRuleApplicationDepth := 10
    maxNormIterations := 320
    maxGoals := 64
    enableUnfold := false
  })
    (add norm 100 (by ring))
    (add norm 100 (by field_simp))
    (add norm 100 (by norm_num))
    (add norm 100 (by norm_cast))
    (add norm 0 (by linarith))
    (add norm 0 (by nlinarith))
    (add norm 0 (by omega))
    (add norm 100 (by abel))
    (add norm 100 (by zify))
    (add norm 0 (by gcongr))
    (add norm 0 (by bound))
    (add norm 0 (by interval_cases))
    (add norm 100 (by ext))
    (add norm 100 (by exfalso))
    (add norm 0 (by simp))
    (add norm 100 (by ring_nf at *))
    (add norm 100 (by field_simp [*] at *))
    (add norm 100 (by norm_num [*] at *))
    (add norm 100 (by norm_cast at *))
    (add norm 100 (by rfl))
    (add norm 0 (by decide))
    (add norm 100 (by push_cast))
    (add norm 100 (by assumption_mod_cast))
    (add safe 1 (by ring_nf))
    (add safe 0 (by split))
    (add unsafe 90% (by simp_all))
    (add norm 100 (by simp only [one_mul] at *))
    (add norm 100 (by simp only [mul_one] at *))
    (add norm 100 (by simp only [mul_assoc] at *))
    (add norm 100 (by simp only [mul_left_comm] at *))
    (add norm 100 (by simp only [mul_comm] at *))
    (add norm 100 (by simp only [mul_right_comm] at *))
    (add norm 0 (by grind only [AddChar.mulShift_apply]))
    (add norm 0 (by grind only [Zsqrtd.smul_val]))
    (add safe 1 (by grind only [Int.cast_one]))
    (add safe 1 (by grind only [Int.floor_add_int]))
    (add safe 1 (by grind only [mul_lt_mul_iff_left]))
    (add safe 1 (by rw [QuaternionAlgebra.mul_imJ]))
    (add safe 1 (by grind only [Int.cast_add]))
    (add safe 1 (by rw [Int.ceil_add_int]))
    (add safe 0 (by rw [← mul_neg]))
    (add safe 0 (by simp_all [Real.Angle.coe_two_pi]))
    (add safe 1 (by grind only [mul_add_mul]))
    (add safe 1 (by grind only [Int.floor_intCast]))
    (add unsafe 50% (by simp_rw [mul_self]))
    (add unsafe 50% (by simp_rw [Pell.isPell_norm]))
    (add unsafe 50% (by simp_rw [Pell.d]))
    (add unsafe 50% (by simp_rw [FractionalIdeal.dual_eq_mul_inv]))
    (add unsafe 50% (by simp_rw [Quaternion.coe_commutes]))
    (add unsafe 50% (by simp_rw [QuaternionAlgebra.coe_commutes]))
    (add unsafe 50% (by simp_all [jacobiTheta₂_term]))
    (add unsafe 10% (by solve_by_elim [ModularGroup.coe_S]))
    (add unsafe 50% (by simp_rw [add_self]))
    (add unsafe 50% (by simp_rw [QuaternionAlgebra.mul_imI]))
    (add unsafe 10% (by solve_by_elim [LaurentPolynomial.T_zero]))
    (add unsafe 50% (by simp_rw [FractionalIdeal.dual_mul_self]))
    (add unsafe 50% (by simp_rw [FractionalIdeal.dual_dual]))
    (add unsafe 10% (by positivity [Quaternion.coe_one]))